Require Import chapters.
Require Import Stdlib.QArith.Qcanon.
Require Import Stdlib.QArith.QArith.
Require Import Stdlib.Lists.List.
Import ListNotations.
Definition chapters := [(1%nat,Decisions [none (Goto 36%nat); none (Goto 176%nat); none (Goto 104%nat)]);
  (2%nat,can_take (GenBackpack S2) 1%nat (none (Simple [ClearFlag LimbDeath] (Goto 67%nat))));
  (3%nat,can_take StrengthPotion 1%nat (can_take Gold 4%nat (can_take (Weapon Dagger) 1%nat (can_take (Weapon Sword) 1%nat (can_take (GenSpecial S1) 1%nat (none (Simple [SetFlag Knowledge01] (Goto 67%nat))))))));
  (5%nat,none (GameLost));
  (6%nat,Decisions [none (Goto 103%nat); none (Goto 71%nat)]);
  (7%nat,none (Goto 176%nat));
  (8%nat,none (Simple [DamagePlayer 2%nat] (Randomly [(Goto 67%nat , (Q2Qc (1 / 2)%Q)); (Goto 76%nat , (Q2Qc (1 / 2)%Q))])));
  (9%nat,none (Goto 78%nat));
  (10%nat,none (Goto 69%nat));
  (11%nat,none (Conditionally [(COr (HasDiscipline (Camouflage)) (HasDiscipline (Hunting)) , Randomly [(Goto 167%nat , (Q2Qc (1 / 2)%Q)); (Goto 190%nat , (Q2Qc (1 / 2)%Q))]); (Always true , Randomly [(Goto 167%nat , (Q2Qc (3 / 10)%Q)); (Goto 190%nat , (Q2Qc (7 / 10)%Q))])]));
  (13%nat,Decisions [conditional (HasDiscipline (AnimalKinship)) (none (Goto 187%nat)); conditional (Not (HasDiscipline (AnimalKinship))) (Decisions [none (Goto 110%nat)])]);
  (14%nat,retrieve_equipment (Decisions [none (Goto 58%nat); none (Goto 131%nat)]));
  (15%nat,none (Conditionally [(HasLevel Guardian , Randomly [(Goto 151%nat , (Q2Qc (9 / 10)%Q)); (Goto 175%nat , (Q2Qc (1 / 10)%Q))]); (Always true , Randomly [(Goto 151%nat , (Q2Qc (4 / 5)%Q)); (Goto 175%nat , (Q2Qc (1 / 5)%Q))])]));
  (16%nat,Decisions [none (Goto 51%nat); none (Goto 123%nat)]);
  (17%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 47%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 73%nat); none (Goto 112%nat); none (Goto 128%nat)])]);
  (18%nat,none (GameLost));
  (19%nat,Decisions [remove_item_from SBackpack 2%nat (none (Goto 137%nat)); none (Goto 49%nat)]);
  (20%nat,Decisions [none (Goto 142%nat); none (Goto 176%nat); none (Fight (Details ((21)%Z)%Z 28%nat [OnLose 161%nat; Timed 3%nat (StopFight 82%nat)]) (Goto 125%nat))]);
  (21%nat,none (Goto 168%nat));
  (22%nat,Decisions [none (Simple [DamagePlayer 8%nat] (Goto 107%nat)); none (Simple [DamagePlayer 8%nat] (Goto 63%nat))]);
  (23%nat,none (Simple [DamagePlayer 1%nat] (Conditionally [(CAnd (HasDiscipline (Hunting)) (HasFlag LimbDeath) , Randomly [(Goto 77%nat , (Q2Qc (1 / 10)%Q)); (Goto 192%nat , (Q2Qc (7 / 10)%Q)); (Goto 114%nat , (Q2Qc (1 / 5)%Q))]); (HasDiscipline (Hunting) , Randomly [(Goto 192%nat , (Q2Qc (1 / 2)%Q)); (Goto 114%nat , (Q2Qc (1 / 2)%Q))]); (HasFlag LimbDeath , Randomly [(Goto 77%nat , (Q2Qc (3 / 10)%Q)); (Goto 192%nat , (Q2Qc (7 / 10)%Q))]); (Always true , Randomly [(Goto 77%nat , (Q2Qc (7 / 10)%Q)); (Goto 114%nat , (Q2Qc (3 / 10)%Q))])])));
  (24%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 147%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 196%nat)])]);
  (25%nat,none (Goto 69%nat));
  (26%nat,Decisions [conditional (HasDiscipline (MindOverMatter)) (none (Goto 48%nat)); conditional (Not (HasDiscipline (MindOverMatter))) (Decisions [none (Goto 127%nat); none (Goto 93%nat)])]);
  (27%nat,can_buy Potion6Hp 7%nat (can_buy Laumspur 5%nat (can_buy Potion2Hp 3%nat (none (Goto 160%nat)))));
  (28%nat,none (Goto 153%nat));
  (29%nat,none (Goto 55%nat));
  (30%nat,Decisions [conditional (HasLevel Guardian) (none (Goto 62%nat)); conditional (Not (HasLevel Guardian)) (Decisions [none (Goto 152%nat); none (Goto 124%nat)])]);
  (31%nat,none (Conditionally [(HasItem (GenSpecial S2) 1%nat , Goto 143%nat); (Always true , Goto 183%nat)]));
  (32%nat,none (Goto 169%nat));
  (33%nat,Decisions [none (Goto 94%nat); none (Goto 185%nat)]);
  (34%nat,Decisions [none (Simple [DamagePlayer 1%nat] (Goto 127%nat)); none (Simple [DamagePlayer 1%nat] (Goto 93%nat))]);
  (35%nat,can_take (Weapon Mace) 1%nat (can_take (GenSpecial S3) 1%nat (none (Simple [SetFlag Special01] (Goto 14%nat)))));
  (36%nat,none (Goto 176%nat));
  (37%nat,none (Goto 149%nat));
  (38%nat,none (Simple [DamagePlayer 1%nat] (Goto 87%nat)));
  (39%nat,Decisions [none (Goto 9%nat); none (Goto 78%nat)]);
  (40%nat,none (LoseItemFrom SBackpack 1%nat (Simple [DamagePlayer 2%nat; LoseItemKind [SPouch]] (Goto 17%nat))));
  (41%nat,Decisions [none (Goto 103%nat); none (Goto 71%nat)]);
  (42%nat,Decisions [none (Goto 75%nat); none (Goto 169%nat)]);
  (43%nat,Decisions [none (Goto 33%nat); none (Goto 185%nat)]);
  (44%nat,Decisions [none (Goto 83%nat); none (Goto 181%nat)]);
  (45%nat,Decisions [none (Goto 78%nat); none (Goto 199%nat)]);
  (47%nat,Decisions [none (Goto 73%nat); none (Goto 128%nat)]);
  (48%nat,none (Conditionally [(HasLevel Guardian , Randomly [(Goto 34%nat , (Q2Qc (1 / 5)%Q)); (Goto 80%nat , (Q2Qc (4 / 5)%Q))]); (Always true , Randomly [(Goto 34%nat , (Q2Qc (1 / 2)%Q)); (Goto 80%nat , (Q2Qc (1 / 2)%Q))])]));
  (49%nat,none (Conditionally [(CAnd (HasLevel Guardian) (HasDiscipline (Hunting)) , Randomly [(Goto 106%nat , (Q2Qc (1 / 5)%Q)); (Goto 189%nat , (Q2Qc (4 / 5)%Q))]); (HasLevel Guardian , Randomly [(Goto 106%nat , (Q2Qc (3 / 10)%Q)); (Goto 189%nat , (Q2Qc (7 / 10)%Q))]); (HasDiscipline (Hunting) , Randomly [(Goto 106%nat , (Q2Qc (1 / 2)%Q)); (Goto 189%nat , (Q2Qc (1 / 2)%Q))]); (Always true , Randomly [(Goto 106%nat , (Q2Qc (3 / 5)%Q)); (Goto 189%nat , (Q2Qc (2 / 5)%Q))])]));
  (50%nat,none (Simple [DamagePlayer 2%nat] (Goto 176%nat)));
  (51%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Simple [DamagePlayer 1%nat] (Goto 173%nat))); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Simple [DamagePlayer 1%nat] (Goto 96%nat)); none (Simple [DamagePlayer 1%nat] (Goto 145%nat)); none (Simple [DamagePlayer 1%nat] (Goto 13%nat))])]);
  (52%nat,can_take Gold 4%nat (can_take (GenSpecial S4) 1%nat (can_take (Weapon Dagger) 1%nat (can_take (Weapon Sword) 1%nat (none (Goto 140%nat))))));
  (53%nat,Decisions [none (Goto 157%nat); none (Goto 188%nat)]);
  (54%nat,Decisions [conditional (HasFlag LimbDeath) (none (Goto 68%nat)); conditional (Not (HasFlag LimbDeath)) (none (Goto 154%nat)); conditional (Not (HasFlag LimbDeath)) (none (Goto 179%nat))]);
  (55%nat,Decisions [conditional (HasFlag LimbDeath) (none (Goto 68%nat)); conditional (Not (HasFlag LimbDeath)) (Decisions [none (Goto 154%nat); none (Goto 179%nat)])]);
  (56%nat,none (Conditionally [(COr (COr (COr (COr (COr (COr (COr (COr (COr (COr (HasDiscipline (WeaponSkill Dagger)) (HasDiscipline (WeaponSkill Spear))) (HasDiscipline (WeaponSkill Mace))) (HasDiscipline (WeaponSkill ShortSword))) (HasDiscipline (WeaponSkill Warhammer))) (HasDiscipline (WeaponSkill Sword))) (HasDiscipline (WeaponSkill Axe))) (HasDiscipline (WeaponSkill Quarterstaff))) (HasDiscipline (WeaponSkill BroadSword))) (HasDiscipline (WeaponSkill MagicSpear))) (HasDiscipline (WeaponSkill Sommerswerd)) , Randomly [(Goto 7%nat , (Q2Qc (1 / 5)%Q)); (Goto 28%nat , (Q2Qc (4 / 5)%Q))]); (Always true , Randomly [(Goto 7%nat , (Q2Qc (2 / 5)%Q)); (Goto 28%nat , (Q2Qc (3 / 5)%Q))])]));
  (57%nat,none (Conditionally [(HasFlag FoughtElix , Fight (Details ((17)%Z)%Z 32%nat [CombatBonus (2)%Z]) (Goto 2%nat)); (Always true , Fight (Details ((17)%Z)%Z 32%nat []) (Goto 2%nat))]));
  (58%nat,Decisions [conditional (HasFlag Knowledge01) (none (Goto 67%nat)); conditional (Not (HasFlag Knowledge01)) (Decisions [none (Goto 98%nat); none (Goto 156%nat)])]);
  (59%nat,Decisions [none (Goto 4%nat); none (Goto 91%nat)]);
  (60%nat,none (Goto 25%nat));
  (61%nat,none (Goto 176%nat));
  (62%nat,none (Goto 152%nat));
  (63%nat,Decisions [none (Simple [SetFlag Poisonned2] (Goto 102%nat)); none (Simple [SetFlag Poisonned2] (Goto 150%nat))]);
  (64%nat,none (Conditionally [(HasDiscipline (MindBlast) , Fight (Details ((20)%Z)%Z 30%nat [CombatBonus (2)%Z]) (Goto 177%nat)); (Always true , Fight (Details ((20)%Z)%Z 30%nat []) (Goto 177%nat))]));
  (65%nat,Decisions [none (Goto 78%nat); none (Goto 199%nat)]);
  (66%nat,Decisions [none (Goto 149%nat); none (Goto 124%nat)]);
  (67%nat,can_take (Weapon Quarterstaff) 1%nat (none (Goto 200%nat)));
  (68%nat,Decisions [none (Goto 27%nat); none (Goto 160%nat)]);
  (69%nat,Decisions [none (Simple [StoreEquipment] (Goto 138%nat)); none (Simple [StoreEquipment] (Goto 85%nat))]);
  (70%nat,Decisions [none (Goto 43%nat); none (Goto 60%nat)]);
  (71%nat,none (Goto 54%nat));
  (72%nat,Decisions [none (Simple [DamagePlayer 1%nat] (Goto 36%nat)); none (Simple [DamagePlayer 1%nat] (Goto 176%nat))]);
  (73%nat,none (Goto 94%nat));
  (74%nat,Decisions [none (Goto 44%nat); none (Goto 167%nat)]);
  (75%nat,Decisions [none (Goto 24%nat); none (Goto 169%nat); none (Goto 117%nat)]);
  (76%nat,none (Goto 98%nat));
  (77%nat,none (GameLost));
  (78%nat,Decisions [none (Goto 150%nat); none (Goto 102%nat)]);
  (79%nat,Decisions [conditional (CAnd (HasDiscipline (Camouflage)) (HasDiscipline (Hunting))) (none (Goto 170%nat)); conditional (Not (CAnd (HasDiscipline (Camouflage)) (HasDiscipline (Hunting)))) (Decisions [none (Goto 86%nat); none (Goto 119%nat)])]);
  (80%nat,none (Goto 136%nat));
  (81%nat,none (Simple [SetFlag LimbDeath] (Goto 166%nat)));
  (82%nat,none (Goto 176%nat));
  (83%nat,none (Simple [SetFlag Knowledge01] (Goto 181%nat)));
  (84%nat,none (Goto 81%nat));
  (85%nat,Decisions [none (Goto 59%nat); none (Goto 163%nat)]);
  (86%nat,none (Simple [DamagePlayer 1%nat] (Goto 137%nat)));
  (87%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 105%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 158%nat)])]);
  (88%nat,none (Goto 113%nat));
  (89%nat,none (Goto 18%nat));
  (90%nat,Decisions [conditional (HasDiscipline (Healing)) (none (Goto 6%nat)); conditional (Not (HasDiscipline (Healing))) (Decisions [none (Goto 41%nat); none (Goto 103%nat); none (Goto 71%nat)])]);
  (92%nat,none (Goto 25%nat));
  (93%nat,Decisions [none (Simple [HealPlayer 1%nat] (Goto 155%nat)); none (Simple [HealPlayer 1%nat] (Goto 182%nat))]);
  (94%nat,none (Goto 81%nat));
  (95%nat,Decisions [conditional (HasDiscipline (MindOverMatter)) (none (Goto 184%nat)); conditional (Not (HasDiscipline (MindOverMatter))) (Decisions [none (Goto 56%nat)])]);
  (96%nat,Decisions [none (Goto 135%nat); none (Goto 164%nat)]);
  (97%nat,Decisions [none (Goto 194%nat); none (Goto 14%nat)]);
  (98%nat,Decisions [none (Goto 168%nat); none (Goto 118%nat)]);
  (99%nat,Decisions [none (Goto 36%nat); none (Goto 176%nat)]);
  (100%nat,can_take (GenSpecial S3) 1%nat (can_take (GenSpecial S5) 1%nat (none (Goto 57%nat))));
  (101%nat,can_take Gold 4%nat (can_take (Weapon Dagger) 1%nat (can_take (Weapon Sword) 1%nat (can_take StrengthPotion 1%nat (can_take (GenSpecial S1) 1%nat (none (Simple [SetFlag Knowledge01] (Goto 67%nat))))))));
  (102%nat,can_take (Weapon Sword) 1%nat (can_take (Weapon Dagger) 1%nat (can_take (Weapon Warhammer) 1%nat (can_take Gold 6%nat (can_take (GenSpecial S4) 1%nat (none (Goto 150%nat)))))));
  (103%nat,none (Simple [HealPlayer 2%nat] (Goto 71%nat)));
  (104%nat,Decisions [none (Goto 20%nat); none (Goto 142%nat); none (Goto 176%nat)]);
  (105%nat,Decisions [none (Goto 171%nat); none (Goto 158%nat)]);
  (107%nat,Decisions [none (Goto 102%nat); none (Goto 150%nat)]);
  (108%nat,none (Simple [DamagePlayer 2%nat] (Goto 112%nat)));
  (109%nat,Decisions [none (Goto 32%nat); none (Goto 169%nat); none (Goto 129%nat)]);
  (110%nat,none (Conditionally [(HasDiscipline (MindBlast) , Fight (Details ((19)%Z)%Z 30%nat [CombatBonus (2)%Z]) (Goto 40%nat)); (Always true , Fight (Details ((19)%Z)%Z 30%nat []) (Goto 40%nat))]));
  (111%nat,can_take (GenSpecial S3) 1%nat (can_take Gold 3%nat (Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 74%nat)); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Goto 167%nat); none (Goto 44%nat)])])));
  (112%nat,Decisions [conditional (HasDiscipline (AnimalKinship)) (none (Goto 133%nat)); conditional (Not (HasDiscipline (AnimalKinship))) (Decisions [none (Goto 64%nat); none (Goto 116%nat)])]);
  (113%nat,Decisions [conditional (HasDiscipline (Healing)) (none (Goto 53%nat)); conditional (Not (HasDiscipline (Healing))) (Decisions [none (Goto 157%nat); none (Goto 188%nat)])]);
  (114%nat,none (Goto 90%nat));
  (115%nat,none (Goto 132%nat));
  (116%nat,Decisions [none (Goto 33%nat); none (Goto 64%nat)]);
  (117%nat,none (Goto 176%nat));
  (118%nat,none (Conditionally [(CAnd (HasDiscipline (Hunting)) (HasLevel Warmarn) , Randomly [(Goto 89%nat , (Q2Qc (1 / 10)%Q)); (Goto 21%nat , (Q2Qc (9 / 10)%Q))]); (HasLevel Warmarn , Randomly [(Goto 89%nat , (Q2Qc (1 / 5)%Q)); (Goto 21%nat , (Q2Qc (4 / 5)%Q))]); (HasDiscipline (Hunting) , Randomly [(Goto 89%nat , (Q2Qc (3 / 10)%Q)); (Goto 21%nat , (Q2Qc (7 / 10)%Q))]); (Always true , Randomly [(Goto 89%nat , (Q2Qc (2 / 5)%Q)); (Goto 21%nat , (Q2Qc (3 / 5)%Q))])]));
  (120%nat,none (Goto 22%nat));
  (121%nat,Decisions [none (Goto 60%nat); none (Goto 84%nat)]);
  (122%nat,Decisions [conditional (HasItem (GenSpecial S4) 1%nat) (none (Goto 136%nat)); conditional (Not (HasItem (GenSpecial S4) 1%nat)) (Decisions [none (Goto 26%nat)])]);
  (123%nat,evade_fight 0%nat 51%nat (Details ((18)%Z)%Z 28%nat []) (Goto 198%nat));
  (124%nat,none (Goto 18%nat));
  (125%nat,none (Conditionally [(HasDiscipline (Hunting) , Randomly [(Goto 50%nat , (Q2Qc (1 / 5)%Q)); (Goto 191%nat , (Q2Qc (4 / 5)%Q))]); (Always true , Randomly [(Goto 50%nat , (Q2Qc (2 / 5)%Q)); (Goto 191%nat , (Q2Qc (3 / 5)%Q))])]));
  (126%nat,Decisions [conditional (CAnd (HasDiscipline (Camouflage)) (HasDiscipline (Hunting))) (none (Goto 170%nat)); conditional (Not (CAnd (HasDiscipline (Camouflage)) (HasDiscipline (Hunting)))) (Decisions [none (Goto 19%nat); none (Goto 119%nat)])]);
  (127%nat,(special B05S127));
  (128%nat,Decisions [conditional (HasItem (GenBackpack S0) 1%nat) (none (Goto 29%nat)); none (Goto 84%nat); none (Goto 121%nat)]);
  (129%nat,Decisions [none (Goto 36%nat); none (Goto 176%nat)]);
  (130%nat,Decisions [conditional (HasDiscipline (Camouflage)) (none (Simple [HealPlayer 1%nat] (Goto 151%nat))); conditional (Not (HasDiscipline (Camouflage))) (Decisions [none (Simple [HealPlayer 1%nat] (Goto 15%nat))])]);
  (131%nat,can_take Meal 3%nat (can_take (GenSpecial S5) 1%nat (can_take Laumspur 1%nat (can_take (Weapon Dagger) 1%nat (none (Goto 58%nat))))));
  (132%nat,Decisions [none (Goto 195%nat); none (Goto 30%nat)]);
  (133%nat,Decisions [none (Goto 33%nat); none (Goto 64%nat)]);
  (134%nat,none (Goto 95%nat));
  (136%nat,Decisions [conditional (HasDiscipline (Camouflage)) (none (Goto 186%nat)); conditional (Not (HasDiscipline (Camouflage))) (Decisions [none (Goto 178%nat); none (Goto 93%nat)])]);
  (137%nat,Decisions [conditional (COr (HasDiscipline (Tracking)) (HasDiscipline (SixthSense))) (none (Simple [MustEat NoHunt] (Goto 37%nat))); conditional (Not (COr (HasDiscipline (Tracking)) (HasDiscipline (SixthSense)))) (Decisions [none (Simple [MustEat NoHunt] (Goto 66%nat)); none (Simple [MustEat NoHunt] (Goto 149%nat))])]);
  (138%nat,Decisions [none (Goto 4%nat); none (Goto 91%nat)]);
  (139%nat,none (Goto 94%nat));
  (140%nat,Decisions [none (Goto 83%nat); none (Goto 181%nat)]);
  (141%nat,Decisions [none (Goto 51%nat); none (Goto 10%nat)]);
  (142%nat,Decisions [conditional (HasDiscipline (AnimalKinship)) (none (Goto 134%nat)); conditional (Not (HasDiscipline (AnimalKinship))) (Decisions [none (Goto 12%nat); none (Goto 95%nat)])]);
  (143%nat,none (Goto 90%nat));
  (144%nat,none (Goto 174%nat));
  (145%nat,Decisions [none (Goto 108%nat); none (Goto 70%nat)]);
  (146%nat,none (Conditionally [(COr (HasDiscipline (Camouflage)) (HasDiscipline (Hunting)) , Randomly [(Goto 44%nat , (Q2Qc (1 / 2)%Q)); (Goto 190%nat , (Q2Qc (1 / 2)%Q))]); (Always true , Randomly [(Goto 44%nat , (Q2Qc (3 / 10)%Q)); (Goto 190%nat , (Q2Qc (7 / 10)%Q))])]));
  (147%nat,Decisions [none (Goto 61%nat); none (Goto 109%nat)]);
  (148%nat,none (Goto 14%nat));
  (149%nat,Decisions [none (Goto 57%nat); none (Goto 100%nat)]);
  (150%nat,Decisions [none (Goto 93%nat); none (Goto 122%nat)]);
  (151%nat,none (Goto 94%nat));
  (152%nat,none (Conditionally [(CAnd (HasDiscipline (Hunting)) (HasLevel Savant) , Randomly [(Goto 38%nat , (Q2Qc (1 / 2)%Q)); (Goto 87%nat , (Q2Qc (1 / 2)%Q))]); (COr (HasLevel Savant) (HasDiscipline (Hunting)) , Randomly [(Goto 5%nat , (Q2Qc (1 / 10)%Q)); (Goto 38%nat , (Q2Qc (3 / 5)%Q)); (Goto 87%nat , (Q2Qc (3 / 10)%Q))]); (Always true , Randomly [(Goto 5%nat , (Q2Qc (3 / 10)%Q)); (Goto 38%nat , (Q2Qc (3 / 5)%Q)); (Goto 87%nat , (Q2Qc (1 / 10)%Q))])]));
  (153%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 42%nat)); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Goto 75%nat); none (Goto 117%nat); none (Goto 169%nat)])]);
  (154%nat,can_buy Laumspur 5%nat (can_buy StrengthPotion 4%nat (can_buy Potion2Hp 3%nat (can_buy (GenBackpack S1) 1%nat (none (Goto 179%nat))))));
  (155%nat,none (Goto 182%nat));
  (156%nat,Decisions [conditional (CAnd (HasDiscipline (MindOverMatter)) (HasDiscipline (SixthSense))) (none (Goto 8%nat)); conditional (Not (CAnd (HasDiscipline (MindOverMatter)) (HasDiscipline (SixthSense)))) (Decisions [none (Goto 98%nat)])]);
  (157%nat,Decisions [none (Goto 16%nat); none (Goto 99%nat)]);
  (158%nat,none (Goto 58%nat));
  (159%nat,none (Simple [DamagePlayer 2%nat] (Fight (Details ((16)%Z)%Z 22%nat [Timed 3%nat (CombatBonus (-2)%Z)]) (Goto 52%nat))));
  (160%nat,Decisions [none (Goto 126%nat); none (Goto 79%nat); none (Goto 49%nat)]);
  (161%nat,none (Simple [HalfHeal] (Goto 69%nat)));
  (162%nat,none (Conditionally [(HasFlag LimbDeath , Randomly [(Simple [DamagePlayer 2%nat] (Goto 114%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 3%nat] (Goto 114%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 4%nat] (Goto 114%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 5%nat] (Goto 114%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 6%nat] (Goto 114%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 7%nat] (Goto 114%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 8%nat] (Goto 114%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 9%nat] (Goto 114%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 10%nat] (Goto 114%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 11%nat] (Goto 114%nat) , (Q2Qc (1 / 10)%Q))]); (Always true , Simple [DamagePlayer 1%nat] (Fight (Details ((10)%Z)%Z 35%nat []) (Goto 114%nat)))]));
  (163%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Simple [DamagePlayer 1%nat] (Goto 144%nat))); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Simple [DamagePlayer 1%nat] (Goto 174%nat)); none (Simple [DamagePlayer 1%nat] (Goto 18%nat))])]);
  (164%nat,Decisions [none (Simple [DamagePlayer 1%nat] (Goto 31%nat)); none (Simple [DamagePlayer 1%nat] (Goto 139%nat))]);
  (165%nat,Decisions [none (Goto 78%nat); none (Goto 199%nat)]);
  (166%nat,none (Goto 55%nat));
  (167%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 105%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 158%nat)])]);
  (169%nat,can_buy (GenSpecial S6) 2%nat (Decisions [none (Goto 88%nat); none (Goto 113%nat)]));
  (170%nat,none (Goto 137%nat));
  (171%nat,Decisions [none (Goto 148%nat); none (Goto 158%nat)]);
  (172%nat,none (Goto 16%nat));
  (173%nat,Decisions [none (Goto 145%nat); none (Goto 96%nat); none (Goto 13%nat)]);
  (174%nat,Decisions [none (Goto 4%nat); none (Goto 91%nat)]);
  (175%nat,none (Goto 25%nat));
  (176%nat,none (Goto 69%nat));
  (177%nat,Decisions [none (Goto 60%nat); none (Goto 43%nat)]);
  (178%nat,Decisions [none (Fight (Details ((16)%Z)%Z 22%nat []) (Goto 52%nat)); none (Fight (Details ((16)%Z)%Z 22%nat []) (Goto 140%nat))]);
  (179%nat,Decisions [none (Goto 197%nat); none (Goto 92%nat)]);
  (180%nat,none (Conditionally [(HasDiscipline (MindBlast) , Goto 45%nat); (COr (HasDiscipline (SixthSense)) (HasDiscipline (Hunting)) , Randomly [(Goto 120%nat , (Q2Qc (3 / 10)%Q)); (Goto 193%nat , (Q2Qc (7 / 10)%Q))]); (Always true , Randomly [(Goto 120%nat , (Q2Qc (3 / 5)%Q)); (Goto 193%nat , (Q2Qc (2 / 5)%Q))])]));
  (181%nat,Decisions [none (Goto 14%nat); none (Goto 97%nat)]);
  (182%nat,can_take (Weapon Spear) 1%nat (can_take (Weapon BroadSword) 1%nat (Decisions [none (Goto 132%nat); none (Goto 115%nat)])));
  (183%nat,none (Simple [DamagePlayer 2%nat] (Goto 90%nat)));
  (184%nat,none (Goto 153%nat));
  (185%nat,none (Goto 25%nat));
  (186%nat,Decisions [none (Goto 52%nat); none (Goto 140%nat)]);
  (187%nat,none (Goto 17%nat));
  (188%nat,none (Conditionally [(HasItem (GenSpecial S6) 1%nat , Goto 172%nat); (Always true , Goto 72%nat)]));
  (189%nat,none (Goto 137%nat));
  (191%nat,Decisions [none (Goto 176%nat); none (Goto 142%nat)]);
  (192%nat,none (Simple [DamagePlayer 2%nat] (Goto 114%nat)));
  (193%nat,Decisions [none (Goto 78%nat); none (Goto 199%nat)]);
  (194%nat,none (Conditionally [(HasDiscipline (MindShield) , Fight (Details ((14)%Z)%Z 28%nat []) (Goto 35%nat)); (Always true , Fight (Details ((14)%Z)%Z 28%nat [CombatBonus (-3)%Z]) (Goto 35%nat))]));
  (195%nat,Decisions [none (Goto 11%nat); none (Goto 146%nat); none (Goto 190%nat); none (Goto 30%nat)]);
  (196%nat,Decisions [none (Goto 61%nat); none (Goto 109%nat)]);
  (197%nat,none (Goto 25%nat));
  (198%nat,none (Conditionally [(HasDiscipline (Hunting) , Randomly [(Goto 25%nat , (Q2Qc (2 / 5)%Q)); (Goto 141%nat , (Q2Qc (3 / 5)%Q))]); (Always true , Randomly [(Goto 25%nat , (Q2Qc (7 / 10)%Q)); (Goto 141%nat , (Q2Qc (3 / 10)%Q))])]));
  (199%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 39%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 9%nat)])]);
  (200%nat,none (Goto 201%nat));
  (201%nat,Decisions [none (Goto 273%nat); none (Goto 285%nat)]);
  (202%nat,Decisions [none (Goto 309%nat); none (Goto 248%nat); none (Goto 386%nat)]);
  (203%nat,none (Goto 221%nat));
  (204%nat,Decisions [none (Goto 268%nat); none (Goto 390%nat)]);
  (205%nat,none (Randomly [(Goto 234%nat , (Q2Qc (1 / 2)%Q)); (Goto 293%nat , (Q2Qc (1 / 2)%Q))]));
  (206%nat,none (Goto 331%nat));
  (207%nat,none (Goto 224%nat));
  (208%nat,Decisions [conditional (HasItem (GenBackpack S2) 1%nat) (none (Goto 321%nat)); none (Goto 270%nat)]);
  (209%nat,none (Goto 322%nat));
  (210%nat,Decisions [conditional (HasDiscipline (Healing)) (none (Goto 377%nat)); conditional (Not (HasDiscipline (Healing))) (Decisions [none (Goto 339%nat)])]);
  (211%nat,can_buy Potion4Hp 5%nat (Decisions [none (Simple [HealPlayer 2%nat] (Goto 318%nat)); none (Simple [HealPlayer 2%nat] (Goto 272%nat))]));
  (212%nat,Decisions [conditional (HasItem (Weapon Sommerswerd) 1%nat) (none (Goto 349%nat)); conditional (Not (HasItem (Weapon Sommerswerd) 1%nat)) (Decisions [none (Goto 355%nat)])]);
  (213%nat,none (Goto 361%nat));
  (214%nat,none (Goto 395%nat));
  (215%nat,Decisions [conditional (HasItem (GenSpecial S3) 1%nat) (none (Goto 246%nat)); conditional (Not (HasItem (GenSpecial S3) 1%nat)) (Decisions [none (Goto 301%nat); none (Goto 375%nat)])]);
  (216%nat,Decisions [none (Goto 284%nat); none (Goto 340%nat)]);
  (217%nat,none (Goto 343%nat));
  (218%nat,none (Goto 291%nat));
  (219%nat,Decisions [conditional (HasDiscipline (MindShield)) (none (Goto 253%nat)); conditional (Not (HasDiscipline (MindShield))) (Decisions [none (Goto 369%nat)])]);
  (220%nat,Decisions [none (Goto 391%nat); none (Goto 352%nat)]);
  (221%nat,none (Conditionally [(HasFlag ReceivedCrystalStarPendant , Goto 336%nat); (Always true , Goto 275%nat)]));
  (222%nat,none (Randomly [(Goto 378%nat , (Q2Qc (3 / 10)%Q)); (Goto 262%nat , (Q2Qc (7 / 10)%Q))]));
  (224%nat,none (Conditionally [(HasDiscipline (AnimalKinship) , Goto 308%nat); (HasItem (GenSpecial S11) 1%nat , Goto 319%nat); (HasLevel Aspirant , Randomly [(Goto 370%nat , (Q2Qc (1 / 5)%Q)); (Goto 240%nat , (Q2Qc (2 / 5)%Q)); (Goto 287%nat , (Q2Qc (2 / 5)%Q))]); (Always true , Randomly [(Goto 370%nat , (Q2Qc (3 / 10)%Q)); (Goto 240%nat , (Q2Qc (2 / 5)%Q)); (Goto 287%nat , (Q2Qc (1 / 5)%Q)); (Goto 257%nat , (Q2Qc (1 / 10)%Q))])]));
  (225%nat,Decisions [none (Goto 211%nat); none (Goto 318%nat)]);
  (226%nat,Decisions [none (Goto 401%nat); none (Goto 209%nat)]);
  (227%nat,Decisions [none (Goto 265%nat); none (Goto 388%nat)]);
  (228%nat,Decisions [none (Goto 352%nat); none (Goto 332%nat)]);
  (229%nat,none (Conditionally [(HasDiscipline (SixthSense) , Randomly [(Goto 385%nat , (Q2Qc (2 / 5)%Q)); (Goto 251%nat , (Q2Qc (3 / 5)%Q))]); (Always true , Randomly [(Goto 385%nat , (Q2Qc (7 / 10)%Q)); (Goto 251%nat , (Q2Qc (3 / 10)%Q))])]));
  (230%nat,none (GameLost));
  (232%nat,none (GameLost));
  (233%nat,none (Goto 289%nat));
  (234%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 220%nat)); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Goto 352%nat); none (Goto 391%nat)])]);
  (235%nat,Decisions [conditional (HasDiscipline (Healing)) (none (Goto 344%nat)); conditional (Not (HasDiscipline (Healing))) (Decisions [none (Goto 208%nat)])]);
  (236%nat,Decisions [none (Goto 207%nat); none (Goto 224%nat)]);
  (237%nat,none (Simple [HealPlayer 1%nat] (Goto 376%nat)));
  (238%nat,Decisions [none (Simple [DamagePlayer 1%nat] (Goto 381%nat)); none (Simple [DamagePlayer 1%nat] (Goto 317%nat))]);
  (239%nat,none (Conditionally [(HasItem (GenBackpack S1) 1%nat , Goto 260%nat); (CAnd (HasLevel Guardian) (CAnd (CAnd (HasDiscipline (Hunting)) (HasDiscipline (Tracking))) (HasDiscipline (Camouflage))) , Goto 303%nat); (CAnd (CAnd (HasDiscipline (Hunting)) (HasDiscipline (Tracking))) (HasDiscipline (Camouflage)) , Randomly [(Goto 324%nat , (Q2Qc (3 / 10)%Q)); (Goto 303%nat , (Q2Qc (7 / 10)%Q))]); (HasLevel Guardian , Randomly [(Goto 324%nat , (Q2Qc (1 / 5)%Q)); (Goto 303%nat , (Q2Qc (4 / 5)%Q))]); (Always true , Randomly [(Goto 324%nat , (Q2Qc (1 / 2)%Q)); (Goto 303%nat , (Q2Qc (1 / 2)%Q))])]));
  (241%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 365%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 225%nat); none (Goto 272%nat)])]);
  (242%nat,none (Conditionally [(CAnd (HasDiscipline (Camouflage)) (HasDiscipline (MindShield)) , Randomly [(Goto 262%nat , (Q2Qc (1 / 5)%Q)); (Goto 378%nat , (Q2Qc (4 / 5)%Q))]); (HasDiscipline (Camouflage) , Randomly [(Goto 262%nat , (Q2Qc (1 / 2)%Q)); (Goto 378%nat , (Q2Qc (1 / 2)%Q))]); (HasDiscipline (MindShield) , Randomly [(Goto 262%nat , (Q2Qc (2 / 5)%Q)); (Goto 378%nat , (Q2Qc (3 / 5)%Q))]); (Always true , Randomly [(Goto 262%nat , (Q2Qc (7 / 10)%Q)); (Goto 378%nat , (Q2Qc (3 / 10)%Q))])]));
  (243%nat,none (Goto 306%nat));
  (244%nat,none (OneRound (Details ((20)%Z)%Z 28%nat []) (Goto 347%nat) (Goto 271%nat) (Goto 327%nat)));
  (245%nat,none (Goto 289%nat));
  (246%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 220%nat)); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Goto 352%nat); none (Goto 391%nat)])]);
  (247%nat,none (Randomly [(Goto 337%nat , (Q2Qc (3 / 10)%Q)); (Goto 383%nat , (Q2Qc (7 / 10)%Q))]));
  (248%nat,Decisions [conditional (HasItem Gold 5%nat) (none (Simple [LoseItem Gold 5%nat] (Goto 328%nat))); none (Goto 274%nat)]);
  (249%nat,none (Goto 228%nat));
  (250%nat,Decisions [conditional (HasDiscipline (Healing)) (none (Goto 377%nat)); conditional (Not (HasDiscipline (Healing))) (Decisions [none (Goto 339%nat)])]);
  (251%nat,none (Simple [DamagePlayer 6%nat] (Goto 316%nat)));
  (252%nat,Decisions [none (Goto 396%nat); none (Goto 215%nat)]);
  (253%nat,none (Conditionally [(CAnd (HasItem (Weapon Mace) 1%nat) (HasFlag Special01) , Conditionally [(HasItem (Weapon Sommerswerd) 1%nat , Fight (Details ((20)%Z)%Z 40%nat []) (Goto 335%nat)); (HasDiscipline (WeaponSkill Mace) , Fight (Details ((20)%Z)%Z 40%nat [CombatBonus (5)%Z]) (Goto 335%nat)); (CAnd (HasDiscipline (WeaponSkill Dagger)) (HasItem (Weapon Dagger) 1%nat) , Fight (Details ((20)%Z)%Z 40%nat [CombatBonus (3)%Z]) (Goto 335%nat)); (CAnd (HasDiscipline (WeaponSkill Spear)) (HasItem (Weapon Spear) 1%nat) , Fight (Details ((20)%Z)%Z 40%nat [CombatBonus (3)%Z]) (Goto 335%nat)); (CAnd (HasDiscipline (WeaponSkill ShortSword)) (HasItem (Weapon ShortSword) 1%nat) , Fight (Details ((20)%Z)%Z 40%nat [CombatBonus (3)%Z]) (Goto 335%nat)); (CAnd (HasDiscipline (WeaponSkill Warhammer)) (HasItem (Weapon Warhammer) 1%nat) , Fight (Details ((20)%Z)%Z 40%nat [CombatBonus (3)%Z]) (Goto 335%nat)); (CAnd (HasDiscipline (WeaponSkill Sword)) (HasItem (Weapon Sword) 1%nat) , Fight (Details ((20)%Z)%Z 40%nat [CombatBonus (3)%Z]) (Goto 335%nat)); (CAnd (HasDiscipline (WeaponSkill Axe)) (HasItem (Weapon Axe) 1%nat) , Fight (Details ((20)%Z)%Z 40%nat [CombatBonus (3)%Z]) (Goto 335%nat)); (CAnd (HasDiscipline (WeaponSkill Quarterstaff)) (HasItem (Weapon Quarterstaff) 1%nat) , Fight (Details ((20)%Z)%Z 40%nat [CombatBonus (3)%Z]) (Goto 335%nat)); (CAnd (HasDiscipline (WeaponSkill BroadSword)) (HasItem (Weapon BroadSword) 1%nat) , Fight (Details ((20)%Z)%Z 40%nat [CombatBonus (3)%Z]) (Goto 335%nat)); (CAnd (HasDiscipline (WeaponSkill MagicSpear)) (HasItem (Weapon MagicSpear) 1%nat) , Fight (Details ((20)%Z)%Z 40%nat [CombatBonus (3)%Z]) (Goto 335%nat)); (Always true , Fight (Details ((20)%Z)%Z 40%nat [CombatBonus (5)%Z]) (Goto 335%nat))]); (Always true , Fight (Details ((20)%Z)%Z 40%nat []) (Goto 335%nat))]));
  (254%nat,Decisions [none (Simple [DamagePlayer 2%nat] (Goto 280%nat)); none (Simple [DamagePlayer 2%nat] (Goto 361%nat))]);
  (255%nat,Decisions [can_take (GenSpecial S8) 1%nat (none (Goto 228%nat)); none (Goto 228%nat)]);
  (256%nat,Decisions [none (Goto 307%nat); none (Goto 314%nat)]);
  (258%nat,none (Goto 267%nat));
  (259%nat,none (GameLost));
  (260%nat,none (Goto 395%nat));
  (261%nat,none (GameLost));
  (262%nat,Decisions [none (Goto 212%nat); none (Goto 393%nat)]);
  (263%nat,none (Goto 216%nat));
  (264%nat,Decisions [conditional (HasItem (Weapon Sommerswerd) 1%nat) (none (Conditionally [(HasDiscipline (MindBlast) , Goto 315%nat); (Always true , Simple [DamagePlayer 2%nat] (Goto 315%nat))])); conditional (Not (HasItem (Weapon Sommerswerd) 1%nat)) (Decisions [none (Conditionally [(HasDiscipline (MindBlast) , Goto 299%nat); (Always true , Simple [DamagePlayer 2%nat] (Goto 299%nat))])])]);
  (265%nat,Decisions [conditional (HasItem Gold 1%nat) (none (Simple [LoseItem Gold 1%nat] (Goto 397%nat))); none (Goto 256%nat)]);
  (266%nat,none (Goto 322%nat));
  (267%nat,Decisions [none (Goto 330%nat); none (Goto 394%nat)]);
  (268%nat,none (Goto 400%nat));
  (269%nat,none (Goto 352%nat));
  (270%nat,none (LoseItemFrom SBackpack 2%nat (Goto 241%nat)));
  (271%nat,none (Goto 221%nat));
  (272%nat,Decisions [none (Goto 376%nat); none (Goto 216%nat); none (Goto 342%nat)]);
  (273%nat,none (Simple [DamagePlayer 1%nat] (Goto 402%nat)));
  (274%nat,none (Goto 206%nat));
  (275%nat,none (Randomly [(Goto 374%nat , (Q2Qc (1 / 2)%Q)); (Goto 254%nat , (Q2Qc (2 / 5)%Q)); (Goto 261%nat , (Q2Qc (1 / 10)%Q))]));
  (276%nat,Decisions [conditional (HasItem Gold 5%nat) (none (Simple [LoseItem Gold 5%nat] (Goto 326%nat))); none (Goto 202%nat)]);
  (277%nat,none (Goto 352%nat));
  (278%nat,Decisions [conditional (HasDiscipline (MindShield)) (none (Simple [DamagePlayer 3%nat] (Goto 223%nat))); conditional (Not (HasDiscipline (MindShield))) (Decisions [none (Simple [DamagePlayer 3%nat] (Goto 379%nat))])]);
  (279%nat,Decisions [none (Goto 396%nat); none (Goto 215%nat)]);
  (281%nat,can_take (Weapon Mace) 1%nat (none (Simple [SetFlag Special01] (Goto 241%nat))));
  (282%nat,none (Conditionally [(HasDiscipline (MindOverMatter) , Goto 295%nat); (CAnd (HasLevel Warmarn) (COr (HasDiscipline (Camouflage)) (HasDiscipline (Hunting))) , Randomly [(Goto 389%nat , (Q2Qc (1 / 2)%Q)); (Goto 236%nat , (Q2Qc (1 / 2)%Q))]); (COr (HasDiscipline (Camouflage)) (HasDiscipline (Hunting)) , Randomly [(Goto 357%nat , (Q2Qc (3 / 10)%Q)); (Goto 389%nat , (Q2Qc (1 / 2)%Q)); (Goto 236%nat , (Q2Qc (1 / 5)%Q))]); (HasLevel Warmarn , Randomly [(Goto 357%nat , (Q2Qc (1 / 5)%Q)); (Goto 389%nat , (Q2Qc (1 / 2)%Q)); (Goto 236%nat , (Q2Qc (3 / 10)%Q))]); (Always true , Randomly [(Goto 357%nat , (Q2Qc (1 / 2)%Q)); (Goto 389%nat , (Q2Qc (1 / 2)%Q)); (Goto 236%nat , (Q2Qc (0 / 1)%Q))])]));
  (283%nat,Decisions [none (Goto 291%nat); none (Goto 359%nat)]);
  (284%nat,none (Simple [DamagePlayer 3%nat] (Goto 340%nat)));
  (285%nat,Decisions [none (Simple [DamagePlayer 2%nat] (Goto 381%nat)); none (Simple [DamagePlayer 2%nat] (Goto 317%nat))]);
  (286%nat,Decisions [conditional (HasDiscipline (MindOverMatter)) (none (Goto 214%nat)); conditional (Not (HasDiscipline (MindOverMatter))) (Decisions [none (Goto 239%nat)])]);
  (287%nat,none (Simple [DamagePlayer 1%nat] (Goto 343%nat)));
  (288%nat,none (Conditionally [(HasFlag ReceivedCrystalStarPendant , Goto 399%nat); (Always true , Goto 294%nat)]));
  (289%nat,Decisions [conditional (HasItem (Weapon Sommerswerd) 1%nat) (none (Goto 311%nat)); conditional (Not (HasItem (Weapon Sommerswerd) 1%nat)) (Decisions [none (Goto 219%nat)])]);
  (290%nat,Decisions [can_take (GenSpecial S8) 1%nat (none (Goto 246%nat)); none (Goto 246%nat)]);
  (291%nat,none (Goto 359%nat));
  (292%nat,none (Goto 206%nat));
  (293%nat,none (GameLost));
  (294%nat,none (Goto 323%nat));
  (295%nat,Decisions [none (Goto 207%nat); none (Goto 224%nat)]);
  (296%nat,Decisions [none (Goto 362%nat); none (Goto 388%nat)]);
  (297%nat,Decisions [none (Simple [DamagePlayer 4%nat] (Goto 334%nat)); none (Simple [DamagePlayer 4%nat] (Goto 209%nat))]);
  (298%nat,none (Goto 289%nat));
  (300%nat,Decisions [conditional (HasItem (GenSpecial S8) 1%nat) (none (Goto 229%nat)); conditional (Not (HasItem (GenSpecial S8) 1%nat)) (Decisions [none (Goto 247%nat)])]);
  (301%nat,none (Conditionally [(CAnd (HasLevel Guardian) (HasDiscipline (Hunting)) , Randomly [(Goto 363%nat , (Q2Qc (4 / 5)%Q)); (Goto 259%nat , (Q2Qc (1 / 5)%Q))]); (HasLevel Guardian , Randomly [(Goto 363%nat , (Q2Qc (7 / 10)%Q)); (Goto 259%nat , (Q2Qc (3 / 10)%Q))]); (HasDiscipline (Hunting) , Randomly [(Goto 363%nat , (Q2Qc (3 / 5)%Q)); (Goto 259%nat , (Q2Qc (2 / 5)%Q))]); (Always true , Randomly [(Goto 363%nat , (Q2Qc (1 / 2)%Q)); (Goto 259%nat , (Q2Qc (1 / 2)%Q))])]));
  (302%nat,Decisions [none (Simple [HealPlayer 3%nat] (Goto 392%nat)); none (Simple [HealPlayer 3%nat] (Goto 283%nat))]);
  (303%nat,none (Goto 395%nat));
  (304%nat,none (GameLost));
  (305%nat,none (Randomly [(Goto 293%nat , (Q2Qc (3 / 10)%Q)); (Goto 234%nat , (Q2Qc (7 / 10)%Q))]));
  (306%nat,none (Goto 247%nat));
  (307%nat,none (Goto 314%nat));
  (308%nat,none (Goto 343%nat));
  (309%nat,none (Goto 206%nat));
  (310%nat,can_take (GenSpecial S3) 1%nat (Decisions [none (Goto 246%nat); none (Goto 231%nat)]));
  (311%nat,Decisions [none (Goto 278%nat); none (Goto 350%nat); none (Goto 230%nat)]);
  (312%nat,none (Conditionally [(COr (HasDiscipline (Hunting)) (HasDiscipline (SixthSense)) , Goto 210%nat); (Always true , Randomly [(Goto 354%nat , (Q2Qc (1 / 2)%Q)); (Goto 371%nat , (Q2Qc (2 / 5)%Q)); (Goto 232%nat , (Q2Qc (1 / 10)%Q))])]));
  (313%nat,Decisions [conditional (HasItem (GenSpecial S1) 1%nat) (none (Goto 325%nat)); conditional (Not (HasItem (GenSpecial S1) 1%nat)) (Decisions [none (Goto 282%nat)])]);
  (314%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 358%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 263%nat)])]);
  (315%nat,none (Goto 221%nat));
  (317%nat,Decisions [none (Goto 338%nat); none (Goto 372%nat)]);
  (318%nat,none (Goto 272%nat));
  (319%nat,none (Goto 343%nat));
  (320%nat,none (Simple [MustEat NoHunt] (Goto 286%nat)));
  (321%nat,Decisions [none (Goto 356%nat); none (Goto 281%nat)]);
  (322%nat,Decisions [none (Goto 329%nat); none (Goto 387%nat)]);
  (323%nat,none (Randomly [(Goto 250%nat , (Q2Qc (3 / 10)%Q)); (Goto 312%nat , (Q2Qc (7 / 10)%Q))]));
  (325%nat,none (Conditionally [(COr (COr (COr (COr (COr (COr (COr (COr (COr (COr (HasDiscipline (WeaponSkill Dagger)) (HasDiscipline (WeaponSkill Spear))) (HasDiscipline (WeaponSkill Mace))) (HasDiscipline (WeaponSkill ShortSword))) (HasDiscipline (WeaponSkill Warhammer))) (HasDiscipline (WeaponSkill Sword))) (HasDiscipline (WeaponSkill Axe))) (HasDiscipline (WeaponSkill Quarterstaff))) (HasDiscipline (WeaponSkill BroadSword))) (HasDiscipline (WeaponSkill MagicSpear))) (HasDiscipline (WeaponSkill Sommerswerd)) , Randomly [(Goto 384%nat , (Q2Qc (1 / 5)%Q)); (Goto 398%nat , (Q2Qc (4 / 5)%Q))]); (Always true , Randomly [(Goto 384%nat , (Q2Qc (2 / 5)%Q)); (Goto 398%nat , (Q2Qc (3 / 5)%Q))])]));
  (326%nat,none (Goto 202%nat));
  (327%nat,none (Goto 221%nat));
  (328%nat,none (Goto 206%nat));
  (329%nat,Decisions [conditional (HasItem (GenBackpack S0) 1%nat) (none (Goto 305%nat)); conditional (Not (HasItem (GenBackpack S0) 1%nat)) (Decisions [none (Goto 387%nat)])]);
  (331%nat,none (Goto 373%nat));
  (332%nat,none (Goto 372%nat));
  (333%nat,Decisions [conditional (HasItem (Weapon Sommerswerd) 1%nat) (none (Goto 258%nat)); conditional (Not (HasItem (Weapon Sommerswerd) 1%nat)) (Decisions [none (Goto 348%nat)])]);
  (334%nat,evade_fight 0%nat 209%nat (Details ((17)%Z)%Z 32%nat []) (Goto 310%nat));
  (335%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 204%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 268%nat); none (Goto 390%nat)])]);
  (336%nat,none (Randomly [(Goto 374%nat , (Q2Qc (1 / 2)%Q)); (Goto 254%nat , (Q2Qc (2 / 5)%Q)); (Goto 261%nat , (Q2Qc (1 / 10)%Q))]));
  (337%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 365%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 225%nat); none (Goto 272%nat)])]);
  (338%nat,Decisions [none (Goto 372%nat); none (Goto 279%nat)]);
  (339%nat,none (Goto 302%nat));
  (340%nat,none (Goto 202%nat));
  (341%nat,can_take (GenSpecial S3) 1%nat (can_take (Weapon BroadSword) 1%nat (Decisions [none (Goto 246%nat); none (Goto 231%nat)])));
  (342%nat,Decisions [none (Goto 296%nat); none (Goto 227%nat)]);
  (343%nat,Decisions [none (Goto 264%nat); none (Goto 244%nat)]);
  (344%nat,Decisions [conditional (HasItem (GenBackpack S2) 1%nat) (none (Simple [LoseItem (GenBackpack S2) 1%nat] (Goto 321%nat))); none (Goto 270%nat)]);
  (345%nat,Decisions [none (Goto 381%nat); none (Goto 317%nat)]);
  (346%nat,none (Goto 206%nat));
  (347%nat,none (Goto 221%nat));
  (348%nat,none (Goto 267%nat));
  (349%nat,none (Goto 228%nat));
  (350%nat,Decisions [conditional (HasDiscipline (MindShield)) (none (Simple [DamagePlayer 3%nat; LoseItem (Weapon Sommerswerd) 1%nat] (Goto 253%nat))); conditional (Not (HasDiscipline (MindShield))) (Decisions [none (Simple [DamagePlayer 3%nat; LoseItem (Weapon Sommerswerd) 1%nat] (Goto 369%nat))])]);
  (351%nat,Decisions [none (Goto 276%nat); none (Goto 202%nat)]);
  (352%nat,none (Goto 313%nat));
  (354%nat,Decisions [conditional (HasDiscipline (Healing)) (none (Simple [DamagePlayer 2%nat] (Goto 377%nat))); conditional (Not (HasDiscipline (Healing))) (Decisions [none (Simple [DamagePlayer 2%nat] (Goto 339%nat))])]);
  (356%nat,none (Goto 281%nat));
  (357%nat,(special B05S357));
  (358%nat,Decisions [none (Goto 388%nat); none (Goto 376%nat); none (Goto 216%nat)]);
  (359%nat,none (Simple [HealPlayer 2%nat] (Goto 300%nat)));
  (360%nat,none (Conditionally [(HasDiscipline (Hunting) , Randomly [(Goto 334%nat , (Q2Qc (9 / 100)%Q)); (Goto 226%nat , (Q2Qc (11 / 20)%Q)); (Goto 297%nat , (Q2Qc (9 / 25)%Q))]); (Always true , Randomly [(Goto 334%nat , (Q2Qc (1 / 10)%Q)); (Goto 226%nat , (Q2Qc (9 / 20)%Q)); (Goto 297%nat , (Q2Qc (9 / 20)%Q))])]));
  (362%nat,Decisions [conditional (HasItem Gold 1%nat) (none (Simple [LoseItem Gold 1%nat] (Goto 237%nat))); none (Goto 388%nat)]);
  (363%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 220%nat)); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Goto 352%nat); none (Goto 391%nat)])]);
  (364%nat,none (Goto 380%nat));
  (365%nat,Decisions [none (Goto 225%nat); none (Goto 272%nat)]);
  (366%nat,none (GameLost));
  (367%nat,Decisions [none (Goto 376%nat); none (Goto 216%nat)]);
  (368%nat,Decisions [none (Simple [DamagePlayer 3%nat] (Goto 396%nat)); none (Simple [DamagePlayer 3%nat] (Goto 215%nat))]);
  (369%nat,none (Simple [DamagePlayer 6%nat] (Goto 253%nat)));
  (370%nat,none (Simple [DamagePlayer 3%nat] (Goto 403%nat)));
  (371%nat,Decisions [conditional (HasDiscipline (Healing)) (none (Simple [DamagePlayer 4%nat] (Goto 377%nat))); conditional (Not (HasDiscipline (Healing))) (Decisions [none (Simple [DamagePlayer 4%nat] (Goto 339%nat))])]);
  (372%nat,none (Simple [DamagePlayer 1%nat] (Conditionally [(HasDiscipline (MindOverMatter) , Goto 269%nat); (HasLevel Aspirant , Randomly [(Goto 366%nat , (Q2Qc (1 / 5)%Q)); (Goto 277%nat , (Q2Qc (4 / 5)%Q))]); (Always true , Randomly [(Goto 366%nat , (Q2Qc (2 / 5)%Q)); (Goto 277%nat , (Q2Qc (3 / 5)%Q))])])));
  (373%nat,none (Goto 320%nat));
  (374%nat,Decisions [none (Goto 280%nat); none (Goto 361%nat)]);
  (376%nat,Decisions [none (Goto 351%nat); none (Goto 202%nat)]);
  (377%nat,none (Goto 339%nat));
  (378%nat,none (Goto 228%nat));
  (379%nat,none (Simple [DamagePlayer 6%nat] (Goto 223%nat)));
  (380%nat,Decisions [conditional (HasItem (GenSpecial S8) 1%nat) (none (Simple [DamagePlayer 2%nat] (Goto 229%nat))); conditional (Not (HasItem (GenSpecial S8) 1%nat)) (Decisions [none (Simple [DamagePlayer 2%nat] (Goto 247%nat))])]);
  (381%nat,none (Conditionally [(HasDiscipline (Hunting) , Randomly [(Goto 368%nat , (Q2Qc (1 / 5)%Q)); (Goto 252%nat , (Q2Qc (4 / 5)%Q))]); (Always true , Randomly [(Goto 368%nat , (Q2Qc (1 / 2)%Q)); (Goto 252%nat , (Q2Qc (1 / 2)%Q))])]));
  (382%nat,none (Conditionally [(HasFlag ReceivedCrystalStarPendant , Goto 399%nat); (Always true , Goto 294%nat)]));
  (383%nat,Decisions [none (Goto 235%nat); none (Goto 272%nat)]);
  (384%nat,none (Goto 282%nat));
  (385%nat,none (Simple [DamagePlayer 12%nat] (Goto 316%nat)));
  (386%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 292%nat)); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Goto 206%nat); none (Goto 346%nat)])]);
  (387%nat,evade_fight 0%nat 205%nat (Details ((17)%Z)%Z 35%nat []) (Goto 341%nat));
  (388%nat,can_buy (Weapon Sword) 5%nat (can_buy (Weapon BroadSword) 9%nat (can_buy (Weapon Dagger) 3%nat (Decisions [none (Goto 216%nat); none (Goto 367%nat)]))));
  (390%nat,none (GameLost));
  (391%nat,none (Conditionally [(HasLevel Warmarn , Goto 242%nat); (Always true , Goto 222%nat)]));
  (392%nat,none (Conditionally [(CAnd (HasLevel Savant) (HasEndurance 26%nat) , Randomly [(Goto 364%nat , (Q2Qc (1 / 5)%Q)); (Goto 218%nat , (Q2Qc (4 / 5)%Q))]); (CAnd (HasLevel Savant) (HasEndurance 15%nat) , Randomly [(Goto 364%nat , (Q2Qc (2 / 5)%Q)); (Goto 218%nat , (Q2Qc (3 / 5)%Q))]); (HasLevel Savant , Randomly [(Goto 364%nat , (Q2Qc (3 / 5)%Q)); (Goto 218%nat , (Q2Qc (2 / 5)%Q))]); (HasEndurance 26%nat , Randomly [(Goto 364%nat , (Q2Qc (1 / 2)%Q)); (Goto 218%nat , (Q2Qc (1 / 2)%Q))]); (HasEndurance 15%nat , Randomly [(Goto 364%nat , (Q2Qc (7 / 10)%Q)); (Goto 218%nat , (Q2Qc (3 / 10)%Q))]); (Always true , Randomly [(Goto 364%nat , (Q2Qc (9 / 10)%Q)); (Goto 218%nat , (Q2Qc (1 / 10)%Q))])]));
  (393%nat,none (Conditionally [(HasDiscipline (MindShield) , Goto 405%nat); (Always true , Simple [DamagePlayer 2%nat] (Goto 405%nat))]));
  (394%nat,none (Goto 306%nat));
  (395%nat,Decisions [conditional (HasItem (GenSpecial S5) 1%nat) (none (Goto 233%nat)); conditional (Not (HasItem (GenSpecial S5) 1%nat)) (Decisions [conditional (HasItem (GenSpecial S9) 1%nat) (none (Goto 245%nat)); conditional (Not (HasItem (GenSpecial S9) 1%nat)) (Decisions [none (Goto 298%nat)])])]);
  (396%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 266%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 322%nat); none (Goto 360%nat)])]);
  (397%nat,Decisions [none (Goto 307%nat); none (Goto 314%nat)]);
  (398%nat,Decisions [none (Goto 207%nat); none (Goto 224%nat)]);
  (399%nat,none (Goto 323%nat));
  (400%nat,none (GameWon));
  (401%nat,evade_fight 0%nat 209%nat (Details ((17)%Z)%Z 32%nat [Timed 2%nat (PlayerInvulnerable)]) (Goto 310%nat));
  (402%nat,evade_fight 0%nat 238%nat (Details ((18)%Z)%Z 35%nat []) (Goto 345%nat));
  (404%nat,Decisions [none (Goto 207%nat); none (Goto 224%nat)]);
  (405%nat,evade_fight 3%nat 228%nat (Details ((16)%Z)%Z 25%nat [Timed 2%nat (CombatBonus (-2)%Z)]) (Goto 255%nat));
  (4%nat,can_take (Weapon Sword) 1%nat (none (Simple [SetFlag HadCombat] (Goto 406%nat))));
  (406%nat,none (Fight (Details ((14)%Z)%Z 21%nat [Timed 1%nat (EnemyInvulnerable); Timed 4%nat (OnNotYetWon 180%nat)]) (Goto 407%nat)));
  (407%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 165%nat))));
  (12%nat,none (Simple [SetFlag HadCombat] (Goto 408%nat)));
  (408%nat,none (Fight (Details ((17)%Z)%Z 11%nat [MindblastImmune; CombatBonus (-2)%Z]) (Goto 409%nat)));
  (409%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 95%nat))));
  (46%nat,none (Simple [SetFlag HadCombat] (Goto 410%nat)));
  (410%nat,none (Fight (Details ((14)%Z)%Z 24%nat []) (Goto 411%nat)));
  (411%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 3%nat))));
  (91%nat,none (Simple [SetFlag HadCombat] (Goto 412%nat)));
  (412%nat,none (Fight (Details ((14)%Z)%Z 21%nat [Timed 4%nat (OnNotYetWon 180%nat)]) (Goto 413%nat)));
  (413%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 65%nat))));
  (106%nat,none (Simple [SetFlag HadCombat] (Goto 414%nat)));
  (414%nat,none (Fight (Details ((16)%Z)%Z 23%nat [Timed 3%nat (CombatBonus (-2)%Z)]) (Goto 415%nat)));
  (415%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 189%nat))));
  (119%nat,none (Simple [SetFlag HadCombat] (Goto 416%nat)));
  (416%nat,none (Fight (Details ((16)%Z)%Z 30%nat [Timed 3%nat (PlayerInvulnerable)]) (Goto 417%nat)));
  (417%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 137%nat))));
  (135%nat,none (Simple [SetFlag HadCombat] (Goto 418%nat)));
  (418%nat,none (Fight (Details ((17)%Z)%Z 22%nat [CombatBonus (-2)%Z; OnLose 161%nat]) (Goto 419%nat)));
  (419%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 130%nat))));
  (168%nat,none (Simple [SetFlag HadCombat] (Goto 420%nat)));
  (420%nat,none (Fight (Details ((15)%Z)%Z 23%nat [Timed 3%nat (OnNotYetWon 46%nat)]) (Goto 421%nat)));
  (421%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 101%nat))));
  (190%nat,none (Simple [SetFlag HadCombat] (Goto 422%nat)));
  (422%nat,none (Fight (Details ((18)%Z)%Z 30%nat [CombatBonus (-2)%Z]) (Goto 423%nat)));
  (423%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 111%nat))));
  (223%nat,none (Simple [SetFlag HadCombat] (Goto 424%nat)));
  (424%nat,none (Fight (Details ((24)%Z)%Z 40%nat []) (Goto 425%nat)));
  (425%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 353%nat))));
  (231%nat,none (Simple [SetFlag HadCombat] (Goto 426%nat)));
  (426%nat,none (Fight (Details ((18)%Z)%Z 34%nat []) (Goto 427%nat)));
  (427%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 290%nat))));
  (240%nat,none (Simple [SetFlag HadCombat] (Goto 428%nat)));
  (428%nat,none (Fight (Details ((17)%Z)%Z 30%nat [DoubleDamage]) (Goto 429%nat)));
  (429%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 217%nat))));
  (280%nat,none (Simple [SetFlag HadCombat] (Goto 430%nat)));
  (430%nat,none (Fight (Details ((18)%Z)%Z 25%nat [Timed 1%nat (PlayerInvulnerable)]) (Goto 431%nat)));
  (431%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 213%nat))));
  (299%nat,none (Simple [SetFlag HadCombat] (Goto 432%nat)));
  (432%nat,none (Fight (Details ((17)%Z)%Z 25%nat [EnemyMindblast; MindblastImmune]) (Goto 433%nat)));
  (433%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 203%nat))));
  (316%nat,none (Simple [SetFlag HadCombat] (Goto 434%nat)));
  (434%nat,none (Fight (Details ((18)%Z)%Z 26%nat [Timed 3%nat (CombatBonus (-2)%Z)]) (Goto 435%nat)));
  (435%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 333%nat))));
  (324%nat,none (Simple [SetFlag HadCombat] (Goto 436%nat)));
  (436%nat,none (Fight (Details ((18)%Z)%Z 25%nat []) (Goto 437%nat)));
  (437%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 395%nat))));
  (330%nat,none (Simple [SetFlag HadCombat] (Goto 438%nat)));
  (438%nat,none (Fight (Details ((18)%Z)%Z 23%nat [Timed 2%nat (OnNotYetWon 394%nat)]) (Goto 439%nat)));
  (439%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 243%nat))));
  (353%nat,none (Simple [SetFlag HadCombat] (Goto 440%nat)));
  (440%nat,none (Fight (Details ((28)%Z)%Z 45%nat [EnemyMindblast]) (Goto 441%nat)));
  (441%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 400%nat))));
  (355%nat,none (Simple [SetFlag HadCombat] (Goto 442%nat)));
  (442%nat,none (Fight (Details ((17)%Z)%Z 26%nat [Timed 4%nat (OnNotYetWon 304%nat); EnemyMindblast; MindblastImmune]) (Goto 443%nat)));
  (443%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 249%nat))));
  (361%nat,none (Simple [SetFlag HadCombat] (Goto 444%nat)));
  (444%nat,none (Fight (Details ((18)%Z)%Z 25%nat [Timed 3%nat (OnNotYetWon 382%nat)]) (Goto 445%nat)));
  (445%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 288%nat))));
  (375%nat,none (Simple [SetFlag HadCombat] (Goto 446%nat)));
  (446%nat,none (Fight (Details ((17)%Z)%Z 22%nat [MindblastImmune]) (Goto 447%nat)));
  (447%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 396%nat))));
  (389%nat,none (Simple [SetFlag HadCombat] (Goto 448%nat)));
  (448%nat,none (Fight (Details ((15)%Z)%Z 23%nat []) (Goto 449%nat)));
  (449%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 404%nat))));
  (403%nat,none (Simple [SetFlag HadCombat] (Goto 450%nat)));
  (450%nat,none (Fight (Details ((17)%Z)%Z 30%nat [DoubleDamage]) (Goto 451%nat)));
  (451%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 217%nat))))].