Require Import chapters.
Require Import Stdlib.QArith.Qcanon.
Require Import Stdlib.QArith.QArith.
Require Import Stdlib.Lists.List.
Import ListNotations.
Definition chapters := [(1%nat,Decisions [none (Goto 160%nat); none (Goto 273%nat)]);
  (2%nat,Decisions [none (Goto 290%nat); none (Goto 76%nat)]);
  (3%nat,Decisions [none (Goto 280%nat); none (Goto 344%nat)]);
  (4%nat,can_take (Weapon Sword) 1%nat (can_take (GenSpecial S1) 1%nat (none (Goto 332%nat))));
  (5%nat,Decisions [none (Goto 295%nat); none (Goto 14%nat); none (Goto 132%nat)]);
  (6%nat,Decisions [none (Goto 224%nat); none (Goto 166%nat)]);
  (7%nat,Decisions [none (Goto 145%nat); none (Goto 242%nat)]);
  (8%nat,none (Simple [SetFlag Special04] (Goto 325%nat)));
  (9%nat,none (GameLost));
  (10%nat,can_take Backpack 1%nat (Decisions [conditional (HasFlag Knowledge01) (none (Conditionally [(COr (HasDiscipline (MindOverMatter)) (HasDiscipline (MindBlast)) , Randomly [(Simple [DamagePlayer 1%nat] (Goto 368%nat) , (Q2Qc (1 / 5)%Q)); (Simple [GainItem (GenBackpack S2) 1%nat] (Goto 368%nat) , (Q2Qc (4 / 5)%Q))]); (Always true , Randomly [(Simple [DamagePlayer 1%nat] (Goto 368%nat) , (Q2Qc (1 / 2)%Q)); (Simple [GainItem (GenBackpack S2) 1%nat] (Goto 368%nat) , (Q2Qc (1 / 2)%Q))])])); none (Goto 368%nat)]));
  (11%nat,Decisions [none (Goto 141%nat); none (Goto 159%nat); none (Goto 234%nat)]);
  (12%nat,can_take Meal 3%nat (can_take (GenBackpack S0) 1%nat (Decisions [none (Simple [MustEat NoHunt] (Goto 180%nat)); none (Simple [MustEat NoHunt] (Goto 259%nat))])));
  (13%nat,Decisions [none (Goto 128%nat); none (Goto 254%nat)]);
  (15%nat,none (Conditionally [(HasDiscipline (MindOverMatter) , Goto 185%nat); (COr (HasItem (Weapon Dagger) 1%nat) (HasItem (Weapon Sword) 1%nat) , Goto 86%nat); (Always true , Goto 323%nat)]));
  (16%nat,none (LoseItemFrom SBackpack 2%nat (Goto 63%nat)));
  (17%nat,Decisions [none (Simple [DamagePlayer 3%nat; LoseItemKind [SWeapon]] (Goto 62%nat)); none (Simple [DamagePlayer 3%nat; LoseItemKind [SWeapon]] (Goto 251%nat))]);
  (18%nat,Decisions [none (Goto 211%nat); none (Goto 95%nat)]);
  (19%nat,Decisions [none (Goto 327%nat); none (Goto 307%nat)]);
  (20%nat,none (Goto 254%nat));
  (21%nat,none (Simple [DamagePlayer 3%nat] (Goto 325%nat)));
  (22%nat,none (Goto 323%nat));
  (23%nat,none (Goto 235%nat));
  (24%nat,none (Goto 332%nat));
  (25%nat,can_take (GenSpecial S2) 1%nat (none (Goto 284%nat)));
  (26%nat,can_take (Weapon Dagger) 1%nat (can_take (Weapon Sword) 1%nat (can_take (Weapon Mace) 1%nat (Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 231%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 187%nat); none (Goto 63%nat)])]))));
  (27%nat,Decisions [none (Conditionally [(HasFlag Special04 , Goto 314%nat); (Always true , Simple [DamagePlayer 2%nat] (Goto 314%nat))]); none (Conditionally [(HasFlag Special04 , Goto 205%nat); (Always true , Simple [DamagePlayer 2%nat] (Goto 205%nat))])]);
  (28%nat,Decisions [none (Goto 210%nat); none (Goto 215%nat)]);
  (29%nat,none (Conditionally [(HasItem (Weapon Sommerswerd) 1%nat , Goto 43%nat); (HasDiscipline (MindOverMatter) , Goto 121%nat); (Always true , Randomly [(Goto 226%nat , (Q2Qc (1 / 2)%Q)); (Goto 266%nat , (Q2Qc (2 / 5)%Q)); (Goto 312%nat , (Q2Qc (1 / 10)%Q))])]));
  (30%nat,Decisions [none (Goto 203%nat); none (Goto 276%nat)]);
  (31%nat,Decisions [none (Goto 150%nat); none (Goto 306%nat)]);
  (32%nat,none (Conditionally [(HasFlag Special01 , Goto 364%nat); (Always true , Fight (Details ((11)%Z)%Z 35%nat [OnDamage 66%nat]) (Goto 364%nat))]));
  (33%nat,Decisions [conditional (COr (HasDiscipline (Tracking)) (HasDiscipline (SixthSense))) (none (Simple [DamagePlayer 1%nat] (Goto 348%nat))); conditional (Not (COr (HasDiscipline (Tracking)) (HasDiscipline (SixthSense)))) (Decisions [none (Simple [DamagePlayer 1%nat] (Goto 27%nat)); none (Simple [DamagePlayer 1%nat] (Goto 314%nat))])]);
  (34%nat,none (Goto 350%nat));
  (35%nat,none (Goto 291%nat));
  (36%nat,none (Conditionally [(CAnd (HasDiscipline (SixthSense)) (HasLevel Guardian) , Goto 341%nat); (HasDiscipline (SixthSense) , Goto 264%nat); (Always true , Goto 124%nat)]));
  (37%nat,none (GameLost));
  (38%nat,can_take Backpack 1%nat (can_take (GenBackpack S0) 1%nat (none (Goto 237%nat))));
  (39%nat,none (Goto 173%nat));
  (40%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 255%nat)); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Goto 125%nat); none (Goto 184%nat)])]);
  (41%nat,none (Goto 221%nat));
  (42%nat,Decisions [none (Goto 294%nat); none (Goto 145%nat)]);
  (43%nat,none (Simple [DamagePlayer 1%nat] (Goto 325%nat)));
  (44%nat,Decisions [conditional (HasItem (GenBackpack S2) 1%nat) (none (Goto 79%nat)); conditional (Not (HasItem (GenBackpack S2) 1%nat)) (Decisions [conditional (HasItem (GenBackpack S1) 1%nat) (none (Goto 157%nat)); conditional (Not (HasItem (GenBackpack S1) 1%nat)) (Decisions [none (Goto 270%nat)])])]);
  (45%nat,Decisions [conditional (HasItem (GenSpecial S0) 1%nat) (none (Goto 303%nat)); conditional (Not (HasItem (GenSpecial S0) 1%nat)) (Decisions [none (Goto 15%nat)])]);
  (46%nat,none (Goto 269%nat));
  (47%nat,none (Goto 323%nat));
  (48%nat,Decisions [none (Goto 215%nat); none (Goto 260%nat)]);
  (49%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Simple [LoseItemKind [SBackpack]; LoseItem Backpack 1%nat] (Goto 342%nat))); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Simple [LoseItemKind [SBackpack]; LoseItem Backpack 1%nat] (Goto 284%nat)); none (Simple [LoseItemKind [SBackpack]; LoseItem Backpack 1%nat] (Goto 199%nat))])]);
  (50%nat,none (Conditionally [(HasItem (GenSpecial S4) 1%nat , Goto 139%nat); (Always true , Goto 189%nat)]));
  (51%nat,Decisions [none (Goto 285%nat); none (Goto 261%nat)]);
  (52%nat,Decisions [none (Goto 169%nat); none (Goto 265%nat)]);
  (53%nat,none (GameLost));
  (55%nat,none (Simple [DamagePlayer 5%nat; SetFlag PermanentSkillReduction2] (Goto 182%nat)));
  (56%nat,none (Goto 192%nat));
  (57%nat,Decisions [conditional (HasDiscipline (Healing)) (none (Goto 17%nat)); conditional (Not (HasDiscipline (Healing))) (Decisions [none (Goto 251%nat)])]);
  (58%nat,none (Goto 252%nat));
  (59%nat,can_take (GenSpecial S2) 1%nat (none (Goto 235%nat)));
  (60%nat,Decisions [none (Goto 150%nat); none (Goto 31%nat); none (Goto 306%nat)]);
  (61%nat,none (GameLost));
  (62%nat,none (Simple [DamagePlayer 3%nat] (Goto 167%nat)));
  (63%nat,Decisions [none (Goto 323%nat); none (Goto 246%nat)]);
  (64%nat,Decisions [none (Goto 321%nat); none (Goto 275%nat)]);
  (65%nat,none (Goto 306%nat));
  (66%nat,none (GameLost));
  (67%nat,Decisions [conditional (HasItem (GenBackpack S0) 1%nat) (none (Goto 328%nat)); none (Goto 166%nat)]);
  (69%nat,Decisions [conditional (HasDiscipline (Camouflage)) (none (Goto 222%nat)); conditional (Not (HasDiscipline (Camouflage))) (Decisions [none (Goto 108%nat); none (Goto 198%nat)])]);
  (70%nat,none (Conditionally [(HasFlag Special04 , Goto 209%nat); (Always true , Goto 339%nat)]));
  (71%nat,none (Goto 320%nat));
  (72%nat,none (Goto 227%nat));
  (73%nat,none (Randomly [(Goto 119%nat , (Q2Qc (4 / 5)%Q)); (Goto 136%nat , (Q2Qc (1 / 5)%Q))]));
  (74%nat,none (Randomly [(Goto 48%nat , (Q2Qc (1 / 2)%Q)); (Goto 287%nat , (Q2Qc (1 / 2)%Q))]));
  (75%nat,Decisions [none (Goto 235%nat); none (Goto 114%nat)]);
  (76%nat,Decisions [conditional (COr (HasDiscipline (Hunting)) (HasDiscipline (AnimalKinship))) (none (Goto 51%nat)); conditional (Not (COr (HasDiscipline (Hunting)) (HasDiscipline (AnimalKinship)))) (Decisions [none (Goto 137%nat); none (Goto 261%nat)])]);
  (79%nat,none (Simple [LoseItem (GenBackpack S2) 1%nat; HealPlayer 6%nat] (Goto 301%nat)));
  (80%nat,none (Randomly [(Goto 123%nat , (Q2Qc (1 / 5)%Q)); (Goto 59%nat , (Q2Qc (4 / 5)%Q))]));
  (81%nat,Decisions [none (Goto 198%nat); none (Goto 69%nat)]);
  (82%nat,Decisions [conditional (HasDiscipline (AnimalKinship)) (none (Goto 329%nat)); conditional (Not (HasDiscipline (AnimalKinship))) (Decisions [none (Goto 138%nat); none (Goto 107%nat)])]);
  (84%nat,can_take (GenSpecial S2) 1%nat (none (Goto 221%nat)));
  (85%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 98%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 49%nat); none (Goto 212%nat)])]);
  (86%nat,none (Conditionally [(COr (COr (COr (COr (COr (COr (COr (COr (COr (COr (HasDiscipline (WeaponSkill Dagger)) (HasDiscipline (WeaponSkill Spear))) (HasDiscipline (WeaponSkill Mace))) (HasDiscipline (WeaponSkill ShortSword))) (HasDiscipline (WeaponSkill Warhammer))) (HasDiscipline (WeaponSkill Sword))) (HasDiscipline (WeaponSkill Axe))) (HasDiscipline (WeaponSkill Quarterstaff))) (HasDiscipline (WeaponSkill BroadSword))) (HasDiscipline (WeaponSkill MagicSpear))) (HasDiscipline (WeaponSkill Sommerswerd)) , Randomly [(Goto 47%nat , (Q2Qc (1 / 2)%Q)); (Goto 194%nat , (Q2Qc (1 / 2)%Q))]); (Always true , Randomly [(Goto 47%nat , (Q2Qc (4 / 5)%Q)); (Goto 194%nat , (Q2Qc (1 / 5)%Q))])]));
  (87%nat,Decisions [none (Goto 323%nat); none (Goto 246%nat)]);
  (91%nat,none (Simple [SetFlag Special04] (Goto 134%nat)));
  (92%nat,Decisions [conditional (HasItem (GenBackpack S0) 1%nat) (none (Goto 133%nat)); none (Goto 297%nat)]);
  (93%nat,none (GameLost));
  (94%nat,none (Randomly [(Simple [DamagePlayer 3%nat] (Goto 176%nat) , (Q2Qc (7 / 10)%Q)); (GameLost , (Q2Qc (3 / 10)%Q))]));
  (95%nat,none (GameLost));
  (96%nat,none (Conditionally [(HasFlag Special04 , Randomly [(Goto 59%nat , (Q2Qc (7 / 10)%Q)); (Goto 214%nat , (Q2Qc (3 / 10)%Q))]); (Always true , Randomly [(Goto 59%nat , (Q2Qc (9 / 10)%Q)); (Goto 214%nat , (Q2Qc (1 / 10)%Q))])]));
  (97%nat,Decisions [conditional (HasItem (GenSpecial S5) 1%nat) (none (Goto 24%nat)); conditional (Not (HasItem (GenSpecial S5) 1%nat)) (Decisions [none (Goto 152%nat); none (Goto 208%nat)])]);
  (98%nat,Decisions [none (Goto 49%nat); none (Goto 212%nat)]);
  (100%nat,Decisions [none (Goto 148%nat); none (Goto 61%nat)]);
  (101%nat,none (Goto 235%nat));
  (102%nat,can_take (GenSpecial S6) 1%nat (Decisions [none (Goto 65%nat); none (Goto 306%nat)]));
  (104%nat,Decisions [conditional (HasItem (GenSpecial S1) 1%nat) (none (Goto 135%nat)); conditional (Not (HasItem (GenSpecial S1) 1%nat)) (Decisions [none (Goto 330%nat)])]);
  (105%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 64%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 321%nat); none (Goto 275%nat)])]);
  (106%nat,evade_fight 0%nat 145%nat (Details ((19)%Z)%Z 36%nat [MindblastImmune]) (Goto 338%nat));
  (107%nat,Decisions [conditional (HasFlag Special04) (none (Goto 202%nat)); conditional (Not (HasFlag Special04)) (Decisions [none (Goto 284%nat); none (Goto 138%nat)])]);
  (108%nat,evade_fight 1%nat 366%nat (Details ((16)%Z)%Z 24%nat []) (Goto 282%nat));
  (109%nat,none (Goto 235%nat));
  (110%nat,Decisions [none (Goto 283%nat); none (Goto 256%nat)]);
  (111%nat,Decisions [none (Goto 254%nat); none (Goto 336%nat)]);
  (112%nat,none (Goto 291%nat));
  (113%nat,none (Goto 63%nat));
  (114%nat,Decisions [conditional (HasDiscipline (Hunting)) (none (Goto 279%nat)); conditional (Not (HasDiscipline (Hunting))) (Decisions [none (Goto 23%nat); none (Goto 101%nat)])]);
  (115%nat,Decisions [none (Goto 218%nat); none (Goto 52%nat)]);
  (116%nat,none (Goto 97%nat));
  (117%nat,Decisions [none (Goto 73%nat); none (Goto 162%nat); none (Goto 223%nat)]);
  (118%nat,none (Goto 56%nat));
  (119%nat,can_take Meal 5%nat (can_take (GenBackpack S0) 1%nat (Decisions [none (Goto 19%nat); none (Goto 257%nat)])));
  (120%nat,Decisions [none (Goto 274%nat); none (Goto 306%nat)]);
  (121%nat,none (Simple [DamagePlayer 1%nat] (Goto 325%nat)));
  (122%nat,none (Goto 173%nat));
  (124%nat,none (Goto 264%nat));
  (125%nat,Decisions [conditional (HasDiscipline (Camouflage)) (none (Goto 96%nat)); conditional (Not (HasDiscipline (Camouflage))) (Decisions [none (Goto 322%nat); none (Goto 207%nat)])]);
  (126%nat,Decisions [none (Goto 246%nat); none (Goto 323%nat)]);
  (127%nat,Decisions [none (Goto 308%nat); none (Goto 323%nat)]);
  (128%nat,Decisions [none (Goto 170%nat); none (Goto 11%nat); none (Goto 254%nat)]);
  (129%nat,none (Goto 155%nat));
  (130%nat,Decisions [none (Goto 198%nat); none (Goto 69%nat)]);
  (131%nat,Decisions [none (Goto 227%nat); none (Goto 306%nat)]);
  (132%nat,Decisions [conditional (COr (HasDiscipline (Tracking)) (HasDiscipline (AnimalKinship))) (none (Goto 229%nat)); none (Goto 88%nat)]);
  (133%nat,Decisions [none (Goto 201%nat); none (Goto 297%nat)]);
  (134%nat,none (Randomly [(Goto 57%nat , (Q2Qc (2 / 5)%Q)); (Goto 188%nat , (Q2Qc (3 / 10)%Q)); (Goto 331%nat , (Q2Qc (3 / 10)%Q))]));
  (135%nat,none (Goto 100%nat));
  (136%nat,none (GameLost));
  (137%nat,none (Conditionally [(HasDiscipline (MindBlast) , Fight (Details ((30)%Z)%Z 30%nat [CombatBonus (-1)%Z]) (Goto 28%nat)); (Always true , Fight (Details ((30)%Z)%Z 30%nat []) (Goto 28%nat))]));
  (138%nat,none (Simple [SetFlag Special03] (Goto 362%nat)));
  (139%nat,Decisions [conditional (HasItem Potion5Hp 1%nat) (none (Goto 116%nat)); conditional (Not (HasItem Potion5Hp 1%nat)) (Decisions [none (Goto 239%nat)])]);
  (140%nat,none (Simple [DamagePlayer 2%nat] (Goto 68%nat)));
  (141%nat,Decisions [none (Goto 170%nat); none (Goto 254%nat)]);
  (142%nat,none (Randomly [(Goto 284%nat , (Q2Qc (3 / 5)%Q)); (Goto 32%nat , (Q2Qc (2 / 5)%Q))]));
  (143%nat,none (GameLost));
  (144%nat,none (GameLost));
  (145%nat,Decisions [none (Goto 36%nat); none (Goto 278%nat)]);
  (146%nat,none (Goto 29%nat));
  (148%nat,none (GameLost));
  (149%nat,none (Conditionally [(COr (COr (HasDiscipline (Tracking)) (HasDiscipline (Hunting))) (HasDiscipline (SixthSense)) , Randomly [(Goto 286%nat , (Q2Qc (3 / 10)%Q)); (Goto 333%nat , (Q2Qc (7 / 10)%Q))]); (Always true , Randomly [(Goto 286%nat , (Q2Qc (1 / 2)%Q)); (Goto 333%nat , (Q2Qc (1 / 2)%Q))])]));
  (150%nat,none (Conditionally [(HasFlag Special04 , Conditionally [(HasItem (Weapon Sommerswerd) 1%nat , Goto 120%nat); (HasItem (GenSpecial S3) 1%nat , Goto 310%nat); (Always true , Goto 367%nat)]); (Always true , Simple [DamagePlayer 2%nat] (Conditionally [(HasItem (Weapon Sommerswerd) 1%nat , Goto 120%nat); (HasItem (GenSpecial S3) 1%nat , Goto 310%nat); (Always true , Goto 367%nat)]))]));
  (151%nat,none (Conditionally [(HasFlag Special04 , Goto 209%nat); (Always true , Goto 339%nat)]));
  (152%nat,Decisions [conditional (HasItem Gold 1%nat) (none (Simple [LoseItem Gold 1%nat] (Randomly [(Goto 319%nat , (Q2Qc (1 / 10)%Q)); (Goto 181%nat , (Q2Qc (9 / 10)%Q))]))); conditional (HasItem Gold 2%nat) (none (Simple [LoseItem Gold 2%nat] (Randomly [(Goto 319%nat , (Q2Qc (1 / 5)%Q)); (Goto 181%nat , (Q2Qc (4 / 5)%Q))]))); conditional (HasItem Gold 3%nat) (none (Simple [LoseItem Gold 3%nat] (Randomly [(Goto 319%nat , (Q2Qc (3 / 10)%Q)); (Goto 181%nat , (Q2Qc (7 / 10)%Q))]))); conditional (HasItem Gold 4%nat) (none (Simple [LoseItem Gold 4%nat] (Randomly [(Goto 319%nat , (Q2Qc (2 / 5)%Q)); (Goto 181%nat , (Q2Qc (3 / 5)%Q))]))); conditional (HasItem Gold 5%nat) (none (Simple [LoseItem Gold 5%nat] (Randomly [(Goto 319%nat , (Q2Qc (1 / 2)%Q)); (Goto 181%nat , (Q2Qc (1 / 2)%Q))]))); conditional (HasItem Gold 6%nat) (none (Simple [LoseItem Gold 6%nat] (Randomly [(Goto 319%nat , (Q2Qc (3 / 5)%Q)); (Goto 181%nat , (Q2Qc (2 / 5)%Q))]))); conditional (HasItem Gold 7%nat) (none (Simple [LoseItem Gold 7%nat] (Randomly [(Goto 319%nat , (Q2Qc (7 / 10)%Q)); (Goto 181%nat , (Q2Qc (3 / 10)%Q))]))); conditional (HasItem Gold 8%nat) (none (Simple [LoseItem Gold 8%nat] (Randomly [(Goto 319%nat , (Q2Qc (4 / 5)%Q)); (Goto 181%nat , (Q2Qc (1 / 5)%Q))]))); conditional (HasItem Gold 9%nat) (none (Simple [LoseItem Gold 9%nat] (Randomly [(Goto 319%nat , (Q2Qc (9 / 10)%Q)); (Goto 181%nat , (Q2Qc (1 / 10)%Q))]))); conditional (HasItem Gold 10%nat) (none (Simple [LoseItem Gold 10%nat] (Randomly [(Goto 319%nat , (Q2Qc (1 / 1)%Q)); (Goto 181%nat , (Q2Qc (0 / 1)%Q))])))]);
  (153%nat,none (GameLost));
  (154%nat,Decisions [none (Goto 145%nat); none (Goto 242%nat)]);
  (155%nat,none (Simple [MustEat NoHunt] (Conditionally [(HasEndurance 21%nat , Randomly [(Goto 248%nat , (Q2Qc (1 / 5)%Q)); (Goto 191%nat , (Q2Qc (4 / 5)%Q))]); (HasEndurance 10%nat , Randomly [(Goto 248%nat , (Q2Qc (3 / 10)%Q)); (Goto 191%nat , (Q2Qc (7 / 10)%Q))]); (Always true , Randomly [(Goto 248%nat , (Q2Qc (1 / 2)%Q)); (Goto 191%nat , (Q2Qc (1 / 2)%Q))])])));
  (157%nat,none (Simple [LoseItem (GenBackpack S1) 1%nat; HealPlayer 6%nat] (Goto 301%nat)));
  (158%nat,none (OneRound (Details ((20)%Z)%Z 28%nat []) (Goto 165%nat) (Goto 337%nat) (Goto 271%nat)));
  (159%nat,Decisions [none (Goto 170%nat); none (Goto 254%nat)]);
  (160%nat,Decisions [conditional (HasDiscipline (Hunting)) (none (Goto 204%nat)); conditional (Not (HasDiscipline (Hunting))) (Decisions [conditional (HasDiscipline (AnimalKinship)) (none (Goto 318%nat)); conditional (Not (HasDiscipline (AnimalKinship))) (Decisions [none (Goto 78%nat)])])]);
  (162%nat,Decisions [none (Goto 19%nat); none (Goto 257%nat)]);
  (163%nat,Decisions [none (Goto 38%nat); none (Goto 237%nat)]);
  (165%nat,none (Goto 68%nat));
  (166%nat,Decisions [none (Goto 111%nat); none (Goto 336%nat)]);
  (167%nat,none (Randomly [(Goto 85%nat , (Q2Qc (7 / 10)%Q)); (Goto 300%nat , (Q2Qc (3 / 10)%Q))]));
  (168%nat,none (Goto 60%nat));
  (169%nat,Decisions [conditional (HasItem (GenSpecial S2) 1%nat) (none (Goto 41%nat)); conditional (Not (HasItem (GenSpecial S2) 1%nat)) (Decisions [none (Goto 265%nat)])]);
  (170%nat,Decisions [conditional (HasItem (Weapon Sommerswerd) 1%nat) (none (Simple [DamagePlayer 6%nat] (Goto 304%nat))); conditional (Not (HasItem (Weapon Sommerswerd) 1%nat)) (Decisions [none (Simple [DamagePlayer 6%nat] (Goto 175%nat))])]);
  (172%nat,none (Goto 134%nat));
  (173%nat,Decisions [conditional (HasItem (GenSpecial S6) 1%nat) (none (Goto 34%nat)); conditional (Not (HasItem (GenSpecial S6) 1%nat)) (Decisions [none (Goto 164%nat); none (Goto 200%nat)])]);
  (174%nat,none (Goto 322%nat));
  (175%nat,none (GameLost));
  (176%nat,Decisions [none (Goto 5%nat); none (Goto 132%nat)]);
  (178%nat,none (Goto 105%nat));
  (179%nat,none (Randomly [(Goto 39%nat , (Q2Qc (1 / 2)%Q)); (Goto 296%nat , (Q2Qc (1 / 2)%Q))]));
  (181%nat,Decisions [none (Goto 208%nat); none (Goto 292%nat)]);
  (182%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 75%nat)); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Goto 114%nat); none (Goto 235%nat)])]);
  (183%nat,none (Conditionally [(HasDiscipline (Hunting) , Randomly [(Goto 89%nat , (Q2Qc (1 / 5)%Q)); (Goto 215%nat , (Q2Qc (4 / 5)%Q))]); (Always true , Randomly [(Goto 89%nat , (Q2Qc (2 / 5)%Q)); (Goto 215%nat , (Q2Qc (3 / 5)%Q))])]));
  (184%nat,Decisions [none (Goto 298%nat); none (Goto 315%nat); none (Goto 125%nat)]);
  (185%nat,none (Conditionally [(HasDiscipline (SixthSense) , Randomly [(Goto 22%nat , (Q2Qc (3 / 10)%Q)); (Goto 326%nat , (Q2Qc (7 / 10)%Q))]); (Always true , Randomly [(Goto 22%nat , (Q2Qc (1 / 2)%Q)); (Goto 326%nat , (Q2Qc (1 / 2)%Q))])]));
  (186%nat,none (Goto 320%nat));
  (187%nat,Decisions [conditional (HasDiscipline (MindShield)) (none (Goto 258%nat)); conditional (Not (HasDiscipline (MindShield))) (Decisions [none (Goto 93%nat)])]);
  (188%nat,Decisions [none (Goto 232%nat); none (Goto 346%nat)]);
  (189%nat,Decisions [none (Goto 292%nat); none (Goto 97%nat)]);
  (190%nat,Decisions [conditional (COr (HasDiscipline (Tracking)) (HasDiscipline (SixthSense))) (none (Goto 348%nat)); none (Goto 27%nat); none (Goto 314%nat)]);
  (191%nat,none (Goto 40%nat));
  (192%nat,Decisions [conditional (HasItem (GenSpecial S4) 1%nat) (none (Simple [DamagePlayer 2%nat] (Goto 267%nat))); conditional (Not (HasItem (GenSpecial S4) 1%nat)) (Decisions [none (Simple [DamagePlayer 2%nat] (Goto 44%nat))])]);
  (193%nat,none (Goto 235%nat));
  (194%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 127%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 308%nat); none (Goto 323%nat)])]);
  (195%nat,none (Goto 21%nat));
  (196%nat,none (Simple [DamagePlayer 2%nat; LoseItemKind [SWeapon]] (Goto 306%nat)));
  (197%nat,Decisions [none (Goto 125%nat); none (Goto 235%nat); none (Goto 109%nat)]);
  (198%nat,none (GameLost));
  (199%nat,Decisions [none (Goto 82%nat); none (Goto 284%nat)]);
  (201%nat,Decisions [none (Goto 110%nat); none (Goto 63%nat)]);
  (202%nat,Decisions [none (Goto 263%nat); none (Goto 277%nat)]);
  (203%nat,Decisions [none (Goto 56%nat); none (Goto 276%nat)]);
  (204%nat,none (Goto 134%nat));
  (205%nat,none (GameLost));
  (206%nat,Decisions [conditional (HasDiscipline (Camouflage)) (none (Simple [DamagePlayer 1%nat] (Goto 74%nat))); conditional (Not (HasDiscipline (Camouflage))) (Decisions [none (Simple [DamagePlayer 1%nat] (Goto 183%nat)); none (Simple [DamagePlayer 1%nat] (Goto 161%nat))])]);
  (207%nat,Decisions [none (Goto 80%nat); none (Goto 253%nat)]);
  (209%nat,none (Simple [DamagePlayer 2%nat] (Goto 155%nat)));
  (210%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 316%nat)); none (Goto 236%nat); none (Goto 215%nat)]);
  (211%nat,none (Conditionally [(HasEndurance 10%nat , Randomly [(Goto 95%nat , (Q2Qc (2 / 5)%Q)); (Goto 196%nat , (Q2Qc (3 / 5)%Q))]); (Always true , Randomly [(Goto 95%nat , (Q2Qc (7 / 10)%Q)); (Goto 196%nat , (Q2Qc (3 / 10)%Q))])]));
  (212%nat,none (Goto 238%nat));
  (213%nat,none (Goto 252%nat));
  (214%nat,Decisions [none (Simple [DamagePlayer 2%nat] (Goto 322%nat)); none (Simple [DamagePlayer 2%nat] (Goto 123%nat))]);
  (215%nat,Decisions [none (Goto 13%nat); none (Goto 254%nat)]);
  (216%nat,Decisions [none (Goto 158%nat); none (Goto 149%nat)]);
  (217%nat,none (Simple [DamagePlayer 10%nat] (Goto 154%nat)));
  (218%nat,can_take (GenSpecial S5) 1%nat (none (Goto 52%nat)));
  (219%nat,none (Goto 349%nat));
  (220%nat,Decisions [none (Goto 146%nat); none (Goto 29%nat)]);
  (221%nat,Decisions [none (Goto 38%nat); none (Goto 163%nat); none (Goto 237%nat)]);
  (222%nat,none (Goto 330%nat));
  (223%nat,can_take Meal 5%nat (can_take (GenBackpack S0) 1%nat (Decisions [none (Goto 327%nat); none (Goto 307%nat)])));
  (224%nat,Decisions [none (Goto 67%nat); none (Goto 166%nat)]);
  (226%nat,none (Simple [DamagePlayer 1%nat] (Goto 325%nat)));
  (227%nat,Decisions [none (Goto 102%nat); none (Goto 334%nat); none (Goto 299%nat)]);
  (228%nat,none (Goto 173%nat));
  (229%nat,Decisions [conditional (HasItem (GenSpecial S3) 1%nat) (none (Goto 46%nat)); conditional (Not (HasItem (GenSpecial S3) 1%nat)) (Decisions [none (Goto 88%nat)])]);
  (230%nat,none (Goto 166%nat));
  (231%nat,Decisions [none (Goto 187%nat); none (Goto 63%nat)]);
  (232%nat,none (Randomly [(Goto 85%nat , (Q2Qc (7 / 10)%Q)); (Goto 300%nat , (Q2Qc (3 / 10)%Q))]));
  (234%nat,Decisions [none (Goto 170%nat); none (Goto 254%nat)]);
  (235%nat,Decisions [none (Simple [ClearFlag Special03; ClearFlag Special02; ClearFlag Special01] (Goto 52%nat)); none (Simple [ClearFlag Special03; ClearFlag Special02; ClearFlag Special01] (Goto 115%nat))]);
  (236%nat,Decisions [conditional (HasDiscipline (MindShield)) (none (Goto 345%nat)); conditional (Not (HasDiscipline (MindShield))) (Decisions [none (Goto 9%nat)])]);
  (237%nat,Decisions [none (Simple [MustEat NoHunt] (Goto 92%nat)); none (Simple [MustEat NoHunt] (Goto 297%nat))]);
  (238%nat,none (Goto 117%nat));
  (239%nat,none (GameLost));
  (240%nat,none (Goto 284%nat));
  (242%nat,Decisions [conditional (HasItem (Weapon Sommerswerd) 1%nat) (none (Goto 42%nat)); conditional (Not (HasItem (Weapon Sommerswerd) 1%nat)) (Decisions [none (Goto 145%nat)])]);
  (243%nat,none (Goto 235%nat));
  (244%nat,Decisions [none (Goto 150%nat); none (Goto 306%nat)]);
  (245%nat,Decisions [none (Goto 91%nat); none (Goto 172%nat)]);
  (246%nat,Decisions [none (Goto 45%nat); none (Goto 323%nat)]);
  (247%nat,Decisions [conditional (HasItem (GenBackpack S0) 1%nat) (none (Goto 118%nat)); conditional (Not (HasItem (GenBackpack S0) 1%nat)) (Decisions [none (Goto 30%nat)])]);
  (248%nat,none (GameLost));
  (249%nat,none (Goto 104%nat));
  (251%nat,none (Simple [DamagePlayer 2%nat] (Goto 62%nat)));
  (252%nat,none (Goto 350%nat));
  (253%nat,none (GameLost));
  (254%nat,Decisions [none (Goto 56%nat); none (Goto 276%nat)]);
  (255%nat,Decisions [none (Goto 125%nat); none (Goto 184%nat)]);
  (256%nat,Decisions [none (Goto 217%nat); none (Goto 7%nat)]);
  (257%nat,Decisions [none (Goto 327%nat); none (Goto 307%nat)]);
  (258%nat,none (Conditionally [(COr (HasDiscipline (SixthSense)) (HasDiscipline (Hunting)) , Randomly [(Simple [DamagePlayer 0%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 0%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 1%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 2%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 3%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 4%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 5%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 6%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 7%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 8%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q))]); (Always true , Randomly [(Simple [DamagePlayer 1%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 2%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 3%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 4%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 5%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 6%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 7%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 8%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 9%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q)); (Simple [DamagePlayer 10%nat] (Goto 63%nat) , (Q2Qc (1 / 10)%Q))])]));
  (261%nat,none (Goto 290%nat));
  (262%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 71%nat)); conditional (Not (HasDiscipline (SixthSense))) (none (Randomly [(Goto 320%nat , (Q2Qc (7 / 10)%Q)); (Goto 140%nat , (Q2Qc (3 / 10)%Q))]))]);
  (263%nat,evade_fight 0%nat 277%nat (Details ((11)%Z)%Z 35%nat [OnDamage 66%nat]) (Simple [SetFlag Special01] (Goto 360%nat)));
  (264%nat,Decisions [none (Goto 60%nat); none (Goto 168%nat); none (Goto 244%nat)]);
  (266%nat,none (Goto 21%nat));
  (267%nat,none (Simple [LoseItem (GenSpecial S4) 1%nat] (Goto 44%nat)));
  (269%nat,Decisions [none (Goto 335%nat); none (Goto 182%nat)]);
  (271%nat,Decisions [none (Goto 241%nat); none (Goto 262%nat)]);
  (272%nat,none (Conditionally [(HasItem (Weapon Sommerswerd) 1%nat , Goto 213%nat); (Always true , Randomly [(Goto 143%nat , (Q2Qc (2 / 5)%Q)); (Goto 58%nat , (Q2Qc (3 / 5)%Q))])]));
  (273%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 35%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 112%nat)])]);
  (274%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 131%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 227%nat); none (Goto 306%nat)])]);
  (275%nat,Decisions [conditional (HasDiscipline (Hunting)) (none (Goto 293%nat)); conditional (Not (HasDiscipline (Hunting))) (Decisions [none (Goto 197%nat)])]);
  (276%nat,Decisions [conditional (COr (HasDiscipline (Hunting)) (HasDiscipline (Tracking))) (none (Goto 219%nat)); conditional (Not (COr (HasDiscipline (Hunting)) (HasDiscipline (Tracking)))) (Decisions [none (Goto 349%nat); none (Goto 50%nat)])]);
  (277%nat,Decisions [conditional (COr (COr (COr (COr (COr (COr (COr (COr (COr (COr (HasItem (Weapon Dagger) 1%nat) (HasItem (Weapon Spear) 1%nat)) (HasItem (Weapon Mace) 1%nat)) (HasItem (Weapon ShortSword) 1%nat)) (HasItem (Weapon Warhammer) 1%nat)) (HasItem (Weapon Sword) 1%nat)) (HasItem (Weapon Axe) 1%nat)) (HasItem (Weapon Quarterstaff) 1%nat)) (HasItem (Weapon BroadSword) 1%nat)) (HasItem (Weapon MagicSpear) 1%nat)) (HasItem (Weapon Sommerswerd) 1%nat)) (none (Goto 142%nat)); none (Goto 32%nat)]);
  (278%nat,none (Goto 36%nat));
  (279%nat,none (Goto 235%nat));
  (280%nat,can_take (GenSpecial S0) 1%nat (none (Simple [DamagePlayer 1%nat] (Goto 344%nat))));
  (281%nat,none (Goto 325%nat));
  (282%nat,can_take (Weapon Spear) 1%nat (can_take (GenSpecial S1) 1%nat (Decisions [none (Goto 104%nat); none (Goto 330%nat)])));
  (283%nat,none (Conditionally [(HasDiscipline (Hunting) , Randomly [(Goto 53%nat , (Q2Qc (1 / 5)%Q)); (Goto 16%nat , (Q2Qc (3 / 10)%Q)); (Goto 113%nat , (Q2Qc (1 / 2)%Q))]); (Always true , Randomly [(Goto 53%nat , (Q2Qc (1 / 2)%Q)); (Goto 16%nat , (Q2Qc (3 / 10)%Q)); (Goto 113%nat , (Q2Qc (1 / 5)%Q))])]));
  (284%nat,none (Conditionally [(CAnd (HasDiscipline (Hunting)) (HasEndurance 8%nat) , Randomly [(Goto 94%nat , (Q2Qc (1 / 5)%Q)); (Goto 176%nat , (Q2Qc (4 / 5)%Q))]); (HasDiscipline (Hunting) , Randomly [(Goto 94%nat , (Q2Qc (2 / 5)%Q)); (Goto 176%nat , (Q2Qc (3 / 5)%Q))]); (HasEndurance 8%nat , Randomly [(Goto 94%nat , (Q2Qc (2 / 5)%Q)); (Goto 176%nat , (Q2Qc (3 / 5)%Q))]); (Always true , Randomly [(Goto 94%nat , (Q2Qc (3 / 5)%Q)); (Goto 176%nat , (Q2Qc (2 / 5)%Q))])]));
  (285%nat,Decisions [none (Goto 261%nat); none (Goto 343%nat)]);
  (286%nat,none (Goto 68%nat));
  (287%nat,none (Goto 161%nat));
  (288%nat,none (Goto 167%nat));
  (290%nat,none (Conditionally [(COr (HasDiscipline (SixthSense)) (HasLevel Aspirant) , Goto 341%nat); (HasDiscipline (SixthSense) , Goto 124%nat); (Always true , Goto 264%nat)]));
  (291%nat,none (Randomly [(Goto 103%nat , (Q2Qc (1 / 2)%Q)); (Goto 220%nat , (Q2Qc (1 / 2)%Q))]));
  (292%nat,Decisions [none (Goto 83%nat); none (Goto 130%nat)]);
  (293%nat,Decisions [none (Goto 125%nat); none (Goto 235%nat); none (Goto 109%nat)]);
  (294%nat,none (Simple [MustEat NoHunt; MustEat NoHunt] (Goto 106%nat)));
  (295%nat,can_take (GenSpecial S3) 1%nat (none (Goto 132%nat)));
  (297%nat,Decisions [none (Goto 317%nat); none (Goto 126%nat)]);
  (298%nat,can_take (GenSpecial S2) 1%nat (Decisions [none (Goto 315%nat); none (Goto 125%nat)]));
  (299%nat,Decisions [none (Conditionally [(HasDiscipline (MindOverMatter) , Goto 65%nat); (Always true , Simple [DamagePlayer 2%nat] (Goto 65%nat))]); none (Conditionally [(HasDiscipline (MindOverMatter) , Goto 306%nat); (Always true , Simple [DamagePlayer 2%nat] (Goto 306%nat))])]);
  (300%nat,Decisions [none (Goto 12%nat); none (Goto 238%nat)]);
  (301%nat,Decisions [conditional (HasDiscipline (Camouflage)) (none (Goto 122%nat)); conditional (Not (HasDiscipline (Camouflage))) (Decisions [conditional (HasDiscipline (MindOverMatter)) (none (Goto 228%nat)); conditional (Not (HasDiscipline (MindOverMatter))) (Decisions [conditional (HasDiscipline (Hunting)) (none (Goto 347%nat)); conditional (Not (HasDiscipline (Hunting))) (Decisions [none (Goto 179%nat)])])])]);
  (302%nat,none (Conditionally [(HasDiscipline (Hunting) , Randomly [(Goto 37%nat , (Q2Qc (0 / 1)%Q)); (Goto 193%nat , (Q2Qc (3 / 5)%Q)); (Goto 243%nat , (Q2Qc (2 / 5)%Q))]); (Always true , Randomly [(Goto 37%nat , (Q2Qc (1 / 5)%Q)); (Goto 193%nat , (Q2Qc (3 / 5)%Q)); (Goto 243%nat , (Q2Qc (1 / 5)%Q))])]));
  (303%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Simple [LoseItem (GenSpecial S0) 1%nat] (Goto 127%nat))); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Simple [LoseItem (GenSpecial S0) 1%nat] (Goto 308%nat)); none (Simple [LoseItem (GenSpecial S0) 1%nat] (Goto 323%nat))])]);
  (305%nat,Decisions [none (Goto 8%nat); none (Goto 281%nat)]);
  (306%nat,Decisions [none (Goto 206%nat); none (Goto 6%nat)]);
  (307%nat,Decisions [none (Goto 327%nat); none (Goto 178%nat)]);
  (308%nat,can_take (GenSpecial S10) 1%nat (none (Goto 323%nat)));
  (309%nat,can_take (GenSpecial S2) 1%nat (can_take (GenSpecial S3) 1%nat (none (Goto 132%nat))));
  (310%nat,Decisions [none (Goto 306%nat); none (Goto 72%nat)]);
  (312%nat,none (GameLost));
  (313%nat,none (Goto 130%nat));
  (314%nat,none (Goto 240%nat));
  (315%nat,Decisions [none (Goto 302%nat); none (Goto 125%nat)]);
  (316%nat,Decisions [none (Goto 236%nat); none (Goto 215%nat)]);
  (317%nat,Decisions [none (Goto 10%nat); none (Goto 126%nat)]);
  (318%nat,none (Goto 134%nat));
  (319%nat,none (Goto 332%nat));
  (320%nat,Decisions [none (Goto 190%nat); none (Goto 33%nat)]);
  (321%nat,can_take (GenSpecial S2) 1%nat (none (Goto 235%nat)));
  (322%nat,none (Randomly [(Goto 153%nat , (Q2Qc (3 / 10)%Q)); (Goto 59%nat , (Q2Qc (7 / 10)%Q))]));
  (323%nat,none (Conditionally [(COr (COr (HasDiscipline (Hunting)) (HasDiscipline (Tracking))) (HasDiscipline (SixthSense)) , Randomly [(Goto 76%nat , (Q2Qc (1 / 5)%Q)); (Goto 2%nat , (Q2Qc (4 / 5)%Q))]); (Always true , Randomly [(Goto 76%nat , (Q2Qc (1 / 2)%Q)); (Goto 2%nat , (Q2Qc (1 / 2)%Q))])]));
  (324%nat,none (Goto 61%nat));
  (325%nat,none (Goto 216%nat));
  (326%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Simple [DamagePlayer 1%nat] (Goto 127%nat))); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Simple [DamagePlayer 1%nat] (Goto 308%nat)); none (Simple [DamagePlayer 1%nat] (Goto 323%nat))])]);
  (327%nat,none (Randomly [(Goto 105%nat , (Q2Qc (9 / 10)%Q)); (Goto 144%nat , (Q2Qc (1 / 10)%Q))]));
  (328%nat,Decisions [conditional (HasItem (Weapon Sommerswerd) 1%nat) (none (Simple [DamagePlayer 6%nat] (Goto 99%nat))); conditional (Not (HasItem (Weapon Sommerswerd) 1%nat)) (Decisions [none (Simple [DamagePlayer 6%nat] (Goto 175%nat))])]);
  (329%nat,Decisions [conditional (HasFlag Special04) (none (Goto 202%nat)); none (Goto 284%nat); none (Goto 138%nat)]);
  (330%nat,Decisions [conditional (HasItem (GenBackpack S0) 1%nat) (none (Goto 100%nat)); conditional (Not (HasItem (GenBackpack S0) 1%nat)) (none (Goto 148%nat)); none (Goto 61%nat)]);
  (331%nat,none (Conditionally [(HasDiscipline (Healing) , Randomly [(Goto 62%nat , (Q2Qc (1 / 2)%Q)); (Goto 288%nat , (Q2Qc (1 / 2)%Q))]); (Always true , Simple [DamagePlayer 6%nat] (Randomly [(Goto 62%nat , (Q2Qc (1 / 2)%Q)); (Goto 288%nat , (Q2Qc (1 / 2)%Q))]))]));
  (332%nat,Decisions [conditional (COr (HasDiscipline (SixthSense)) (HasDiscipline (Hunting))) (none (Goto 249%nat)); conditional (Not (COr (HasDiscipline (SixthSense)) (HasDiscipline (Hunting)))) (Decisions [none (Goto 104%nat); none (Goto 69%nat)])]);
  (333%nat,none (Goto 68%nat));
  (334%nat,can_take (GenSpecial S4) 1%nat (Decisions [none (Goto 65%nat); none (Goto 306%nat)]));
  (335%nat,Decisions [none (Goto 55%nat); none (Goto 182%nat)]);
  (336%nat,Decisions [none (Goto 247%nat); none (Goto 30%nat)]);
  (337%nat,none (Goto 68%nat));
  (338%nat,Decisions [none (Goto 87%nat); none (Goto 26%nat)]);
  (339%nat,none (GameLost));
  (340%nat,none (Simple [HealPlayer 6%nat] (Goto 301%nat)));
  (341%nat,none (Goto 264%nat));
  (342%nat,Decisions [none (Goto 199%nat); none (Goto 284%nat)]);
  (344%nat,Decisions [conditional (HasItem (GenSpecial S2) 1%nat) (none (Goto 41%nat)); conditional (Not (HasItem (GenSpecial S2) 1%nat)) (Decisions [none (Goto 147%nat)])]);
  (345%nat,none (Goto 215%nat));
  (346%nat,none (Conditionally [(HasDiscipline (Hunting) , Randomly [(Goto 195%nat , (Q2Qc (1 / 5)%Q)); (Goto 232%nat , (Q2Qc (4 / 5)%Q))]); (Always true , Randomly [(Goto 195%nat , (Q2Qc (2 / 5)%Q)); (Goto 232%nat , (Q2Qc (3 / 5)%Q))])]));
  (347%nat,none (Goto 173%nat));
  (348%nat,none (Goto 314%nat));
  (349%nat,none (Conditionally [(HasItem (GenSpecial S4) 1%nat , Goto 139%nat); (Always true , Goto 97%nat)]));
  (350%nat,none (GameWon));
  (360%nat,evade_fight 0%nat 277%nat (Details ((10)%Z)%Z 32%nat [OnDamage 66%nat]) (Simple [SetFlag Special02] (Goto 361%nat)));
  (361%nat,evade_fight 0%nat 277%nat (Details ((8)%Z)%Z 30%nat [OnDamage 66%nat]) (Simple [SetFlag Special03] (Goto 25%nat)));
  (362%nat,evade_fight 0%nat 277%nat (Details ((11)%Z)%Z 35%nat [OnDamage 66%nat]) (Simple [SetFlag Special01] (Goto 363%nat)));
  (363%nat,evade_fight 0%nat 277%nat (Details ((10)%Z)%Z 32%nat [OnDamage 66%nat]) (Simple [SetFlag Special02] (Goto 25%nat)));
  (364%nat,none (Conditionally [(HasFlag Special02 , Goto 365%nat); (Always true , Fight (Details ((10)%Z)%Z 32%nat [OnDamage 66%nat]) (Goto 365%nat))]));
  (365%nat,none (Conditionally [(HasFlag Special03 , Goto 25%nat); (Always true , Fight (Details ((8)%Z)%Z 30%nat [OnDamage 66%nat]) (Goto 25%nat))]));
  (366%nat,Decisions [none (Goto 330%nat); none (Goto 198%nat)]);
  (367%nat,Decisions [none (Goto 18%nat); none (Goto 211%nat)]);
  (368%nat,Decisions [conditional (HasDiscipline (Healing)) (can_take Potion5Hp 1%nat (none (Goto 369%nat))); conditional (Not (HasDiscipline (Healing))) (none (Goto 369%nat))]);
  (369%nat,Decisions [conditional (COr (HasDiscipline (Healing)) (HasDiscipline (SixthSense))) (can_take StrengthPotion4 1%nat (none (Goto 370%nat))); conditional (Not (COr (HasDiscipline (Healing)) (HasDiscipline (SixthSense)))) (none (Goto 370%nat))]);
  (370%nat,Decisions [conditional (COr (HasDiscipline (AnimalKinship)) (HasLevel Aspirant)) (can_take (GenBackpack S1) 1%nat (none (Goto 126%nat))); conditional (Not (COr (HasDiscipline (AnimalKinship)) (HasLevel Aspirant))) (none (Goto 126%nat))]);
  (14%nat,none (Simple [SetFlag HadCombat] (Goto 371%nat)));
  (371%nat,none (Fight (Details ((15)%Z)%Z 14%nat []) (Goto 372%nat)));
  (372%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 309%nat))));
  (68%nat,none (Simple [SetFlag HadCombat] (Goto 373%nat)));
  (373%nat,none (Fight (Details ((18)%Z)%Z 28%nat []) (Goto 374%nat)));
  (374%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 186%nat))));
  (78%nat,none (Simple [SetFlag HadCombat] (Goto 375%nat)));
  (375%nat,none (Fight (Details ((19)%Z)%Z 30%nat []) (Goto 376%nat)));
  (376%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 245%nat))));
  (83%nat,none (Simple [SetFlag HadCombat] (Goto 377%nat)));
  (377%nat,none (Fight (Details ((18)%Z)%Z 24%nat [MindblastImmune; EnemyMindblast]) (Goto 378%nat)));
  (378%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 313%nat))));
  (88%nat,none (Simple [SetFlag HadCombat] (Goto 379%nat)));
  (379%nat,none (Fight (Details ((15)%Z)%Z 15%nat [Poisonous (Q2Qc (1 / 10)%Q)]) (Goto 380%nat)));
  (380%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 269%nat))));
  (89%nat,none (Simple [SetFlag HadCombat] (Goto 381%nat)));
  (381%nat,none (Fight (Details ((15)%Z)%Z 24%nat [MultiFight]) (Goto 382%nat)));
  (382%nat,none (Fight (Details ((14)%Z)%Z 23%nat [MultiFight]) (Goto 383%nat)));
  (383%nat,none (Fight (Details ((14)%Z)%Z 20%nat []) (Goto 384%nat)));
  (384%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 161%nat))));
  (99%nat,none (Simple [SetFlag HadCombat] (Goto 385%nat)));
  (385%nat,none (Fight (Details ((22)%Z)%Z 30%nat [MindblastImmune; EnemyMindblast; Undead; NoPotion]) (Goto 386%nat)));
  (386%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 230%nat))));
  (103%nat,none (Simple [SetFlag HadCombat] (Goto 387%nat)));
  (387%nat,none (Fight (Details ((19)%Z)%Z 30%nat []) (Goto 388%nat)));
  (388%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 305%nat))));
  (123%nat,none (Simple [SetFlag HadCombat] (Goto 389%nat)));
  (389%nat,none (Fight (Details ((11)%Z)%Z 30%nat [OnDamage 66%nat]) (Goto 390%nat)));
  (390%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 174%nat))));
  (147%nat,none (Simple [SetFlag HadCombat] (Goto 391%nat)));
  (391%nat,none (Fight (Details ((10)%Z)%Z 28%nat [OnDamage 66%nat]) (Goto 392%nat)));
  (392%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 84%nat))));
  (161%nat,none (Simple [SetFlag HadCombat] (Goto 393%nat)));
  (393%nat,none (Fight (Details ((17)%Z)%Z 29%nat [MindblastImmune]) (Goto 394%nat)));
  (394%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 210%nat))));
  (164%nat,none (Simple [SetFlag HadCombat] (Goto 395%nat)));
  (395%nat,none (Fight (Details ((23)%Z)%Z 50%nat [Undead]) (Goto 396%nat)));
  (396%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 272%nat))));
  (180%nat,none (Simple [SetFlag HadCombat] (Goto 397%nat)));
  (397%nat,none (Fight (Details ((11)%Z)%Z 35%nat [Dpr 3%nat]) (Goto 398%nat)));
  (398%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 70%nat))));
  (200%nat,none (Simple [SetFlag HadCombat] (Goto 399%nat)));
  (399%nat,none (Fight (Details ((22)%Z)%Z 50%nat [Timed 7%nat (OnNotYetWon 324%nat)]) (Goto 400%nat)));
  (400%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 272%nat))));
  (208%nat,none (Simple [SetFlag HadCombat] (Goto 401%nat)));
  (401%nat,none (Fight (Details ((17)%Z)%Z 30%nat [Timed 4%nat (OnNotYetWon 81%nat)]) (Goto 402%nat)));
  (402%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 4%nat))));
  (241%nat,none (Simple [SetFlag HadCombat] (Goto 403%nat)));
  (403%nat,none (Fight (Details ((18)%Z)%Z 28%nat [Timed 2%nat (PlayerInvulnerable)]) (Goto 404%nat)));
  (404%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 186%nat))));
  (259%nat,none (Simple [SetFlag HadCombat] (Goto 405%nat)));
  (405%nat,none (Fight (Details ((11)%Z)%Z 35%nat [OnDamage 129%nat]) (Goto 406%nat)));
  (406%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 151%nat))));
  (260%nat,none (Simple [SetFlag HadCombat] (Goto 407%nat)));
  (407%nat,none (Fight (Details ((17)%Z)%Z 29%nat []) (Goto 408%nat)));
  (408%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 210%nat))));
  (265%nat,none (Simple [SetFlag HadCombat] (Goto 409%nat)));
  (409%nat,none (Fight (Details ((15)%Z)%Z 30%nat [MindblastImmune]) (Goto 410%nat)));
  (410%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 3%nat))));
  (270%nat,none (Simple [SetFlag HadCombat] (Goto 411%nat)));
  (411%nat,none (Fight (Details ((14)%Z)%Z 25%nat []) (Goto 412%nat)));
  (412%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 340%nat))));
  (296%nat,none (Simple [SetFlag HadCombat] (Goto 413%nat)));
  (413%nat,none (Fight (Details ((17)%Z)%Z 30%nat []) (Goto 414%nat)));
  (414%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 173%nat))));
  (304%nat,none (Simple [SetFlag HadCombat] (Goto 415%nat)));
  (415%nat,none (Fight (Details ((22)%Z)%Z 30%nat [MindblastImmune; EnemyMindblast; Undead]) (Goto 416%nat)));
  (416%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 20%nat))));
  (343%nat,none (Simple [SetFlag HadCombat] (Goto 417%nat)));
  (417%nat,none (Fight (Details ((15)%Z)%Z 24%nat [MultiFight]) (Goto 418%nat)));
  (418%nat,none (Fight (Details ((14)%Z)%Z 23%nat [MultiFight]) (Goto 419%nat)));
  (419%nat,none (Fight (Details ((14)%Z)%Z 20%nat [MultiFight]) (Goto 420%nat)));
  (420%nat,none (Fight (Details ((17)%Z)%Z 29%nat [MindblastImmune]) (Goto 421%nat)));
  (421%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 28%nat))))].