Require Import chapters.
Require Import Stdlib.QArith.Qcanon.
Require Import Stdlib.QArith.QArith.
Require Import Stdlib.Lists.List.
Import ListNotations.
Definition chapters := [(1%nat,Decisions [can_take (GenSpecial S3) 1%nat (none (Goto 273%nat)); can_take (GenSpecial S3) 1%nat (none (Goto 160%nat))]);
  (2%nat,none (Conditionally [(HasDiscipline (SixthSense) , Goto 42%nat); (Always true , Goto 168%nat)]));
  (3%nat,Decisions [none (Goto 150%nat); none (Goto 19%nat)]);
  (4%nat,Decisions [none (Goto 104%nat); none (Goto 342%nat); none (Goto 276%nat)]);
  (6%nat,Decisions [none (Goto 266%nat); none (Goto 310%nat)]);
  (8%nat,none (GameLost));
  (9%nat,none (Goto 196%nat));
  (10%nat,can_take (GenSpecial S0) 1%nat (none (Randomly [(Goto 51%nat , (Q2Qc (2 / 5)%Q)); (Goto 195%nat , (Q2Qc (3 / 10)%Q)); (Goto 339%nat , (Q2Qc (3 / 10)%Q))])));
  (11%nat,none (GameLost));
  (12%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Randomly [(Goto 58%nat , (Q2Qc (1 / 5)%Q)); (Goto 167%nat , (Q2Qc (3 / 10)%Q)); (Goto 329%nat , (Q2Qc (1 / 2)%Q))])); conditional (Not (HasDiscipline (SixthSense))) (none (Randomly [(Goto 58%nat , (Q2Qc (2 / 5)%Q)); (Goto 167%nat , (Q2Qc (3 / 10)%Q)); (Goto 329%nat , (Q2Qc (3 / 10)%Q))]))]);
  (13%nat,none (Goto 155%nat));
  (14%nat,none (Goto 305%nat));
  (15%nat,can_take Backpack 1%nat (can_take (Weapon BroadSword) 1%nat (can_take (Weapon Mace) 1%nat (can_take (Weapon Quarterstaff) 1%nat (can_take Potion4Hp 1%nat (can_take Meal 3%nat (can_take Gold 12%nat (none (Simple [SetFlag Knowledge01] (Goto 244%nat))))))))));
  (16%nat,none (Goto 268%nat));
  (17%nat,none (Simple [DamagePlayer 5%nat] (Fight (Details ((22)%Z)%Z 30%nat [Undead; MindblastImmune]) (Goto 166%nat))));
  (18%nat,Decisions [none (Goto 173%nat); none (Goto 266%nat); none (Goto 310%nat)]);
  (19%nat,none (Goto 71%nat));
  (20%nat,none (Goto 186%nat));
  (21%nat,can_take (Weapon Dagger) 1%nat (none (Randomly [(Simple [GainItem Gold 2%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 5%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 8%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 11%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 14%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 17%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 20%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 23%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 26%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 29%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q))])));
  (22%nat,none (Randomly [(Goto 119%nat , (Q2Qc (1 / 2)%Q)); (Goto 341%nat , (Q2Qc (1 / 2)%Q))]));
  (23%nat,none (Conditionally [(HasDiscipline (AnimalKinship) , Goto 144%nat); (Always true , Goto 295%nat)]));
  (24%nat,Decisions [none (Goto 177%nat); none (Goto 253%nat); none (Goto 319%nat)]);
  (25%nat,none (Conditionally [(COr (HasDiscipline (SixthSense)) (HasDiscipline (MindOverMatter)) , Goto 116%nat); (Always true , Goto 153%nat)]));
  (26%nat,Decisions [none (Goto 248%nat); none (Goto 66%nat)]);
  (27%nat,none (Simple [HealPlayer 2%nat] (Goto 312%nat)));
  (28%nat,Decisions [none (Goto 106%nat); none (Goto 320%nat)]);
  (29%nat,none (Simple [DamagePlayer 2%nat] (Goto 222%nat)));
  (31%nat,can_take Backpack 1%nat (none (Simple [HealPlayer 6%nat] (Randomly [(Goto 176%nat , (Q2Qc (1 / 2)%Q)); (Goto 254%nat , (Q2Qc (1 / 2)%Q))]))));
  (32%nat,Decisions [none (Simple [MustEat Hunt] (Goto 136%nat)); none (Simple [MustEat Hunt] (Goto 238%nat))]);
  (33%nat,Decisions [none (Conditionally [(HasItem Gold 12%nat , Simple [LoseItemKind [SPouch]; GainItem Gold 12%nat] (Goto 296%nat)); (Always true , Goto 296%nat)]); none (Conditionally [(HasItem Gold 12%nat , Simple [LoseItemKind [SPouch]; GainItem Gold 12%nat] (Goto 88%nat)); (Always true , Goto 88%nat)])]);
  (35%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 13%nat)); conditional (Not (HasDiscipline (Tracking))) (none (Goto 155%nat)); conditional (Not (HasDiscipline (Tracking))) (none (Goto 293%nat))]);
  (36%nat,none (Conditionally [(HasItem Laumspur 1%nat , Goto 145%nat); (HasDiscipline (Healing) , Goto 210%nat); (Always true , Goto 275%nat)]));
  (37%nat,Decisions [none (Simple [MustEat Hunt] (Goto 122%nat)); none (Simple [MustEat Hunt] (Goto 323%nat)); none (Simple [MustEat Hunt] (Goto 257%nat))]);
  (38%nat,Decisions [none (Goto 269%nat); none (Goto 313%nat)]);
  (39%nat,none (Conditionally [(HasItem (GenSpecial S0) 1%nat , Goto 346%nat); (Always true , Goto 156%nat)]));
  (40%nat,none (Simple [FullHeal; GainItem Potion5Hp 1%nat] (Conditionally [(HasDiscipline (SixthSense) , Goto 97%nat); (Always true , Goto 242%nat)])));
  (41%nat,Decisions [none (Simple [HealPlayer 1%nat] (Goto 194%nat)); none (Goto 251%nat)]);
  (42%nat,none (Goto 168%nat));
  (43%nat,none (Goto 286%nat));
  (44%nat,none (GameLost));
  (45%nat,none (Randomly [(Goto 311%nat , (Q2Qc (4 / 5)%Q)); (Goto 159%nat , (Q2Qc (1 / 5)%Q))]));
  (46%nat,Decisions [none (Goto 214%nat); none (Goto 230%nat)]);
  (47%nat,none (Conditionally [(HasFlag Knowledge01 , Goto 111%nat); (Always true , Goto 307%nat)]));
  (48%nat,none (Goto 268%nat));
  (49%nat,none (Goto 100%nat));
  (50%nat,none (Goto 249%nat));
  (51%nat,Decisions [none (Goto 103%nat); none (Goto 249%nat)]);
  (52%nat,none (Conditionally [(HasItem (Weapon MagicSpear) 1%nat , Goto 338%nat); (Always true , Goto 234%nat)]));
  (53%nat,Decisions [none (Goto 321%nat); none (Goto 154%nat)]);
  (54%nat,none (GameLost));
  (55%nat,can_buy (Weapon BroadSword) 12%nat (Decisions [none (Goto 347%nat); none (Goto 3%nat)]));
  (56%nat,none (Goto 127%nat));
  (57%nat,none (Randomly [(Simple [LoseItem Gold 1%nat] (Goto 282%nat) , (Q2Qc (1 / 10)%Q)); (Simple [LoseItem Gold 2%nat] (Goto 282%nat) , (Q2Qc (1 / 10)%Q)); (Simple [LoseItem Gold 3%nat] (Goto 282%nat) , (Q2Qc (1 / 10)%Q)); (Simple [LoseItem Gold 4%nat] (Goto 282%nat) , (Q2Qc (1 / 10)%Q)); (Simple [LoseItem Gold 5%nat] (Goto 282%nat) , (Q2Qc (1 / 10)%Q)); (Simple [LoseItem Gold 6%nat] (Goto 282%nat) , (Q2Qc (1 / 10)%Q)); (Simple [LoseItem Gold 7%nat] (Goto 282%nat) , (Q2Qc (1 / 10)%Q)); (Simple [LoseItem Gold 8%nat] (Goto 282%nat) , (Q2Qc (1 / 10)%Q)); (Simple [LoseItem Gold 9%nat] (Goto 282%nat) , (Q2Qc (1 / 10)%Q)); (Simple [LoseItem Gold 10%nat] (Goto 282%nat) , (Q2Qc (1 / 10)%Q))]));
  (58%nat,none (Simple [LoseItem Gold 10%nat] (Goto 197%nat)));
  (59%nat,none (Conditionally [(HasItem (Weapon MagicSpear) 1%nat , Goto 332%nat); (Always true , Goto 311%nat)]));
  (61%nat,none (Goto 181%nat));
  (63%nat,Decisions [conditional (HasDiscipline (AnimalKinship)) (none (Goto 264%nat)); conditional (Not (HasDiscipline (AnimalKinship))) (none (Goto 188%nat)); conditional (Not (HasDiscipline (AnimalKinship))) (none (Goto 201%nat))]);
  (64%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 229%nat)); conditional (Not (HasDiscipline (SixthSense))) (none (Goto 134%nat)); conditional (Not (HasDiscipline (SixthSense))) (none (Goto 208%nat))]);
  (65%nat,none (Goto 32%nat));
  (67%nat,none (Goto 300%nat));
  (68%nat,none (Goto 306%nat));
  (69%nat,none (Conditionally [(HasDiscipline (MindShield) , Goto 311%nat); (Always true , Simple [DamagePlayer 2%nat] (Goto 311%nat))]));
  (70%nat,none (Conditionally [(HasItem (GenSpecial S1) 1%nat , Goto 219%nat); (Always true , Goto 44%nat)]));
  (71%nat,Decisions [none (Goto 11%nat); none (Goto 54%nat); none (Goto 235%nat)]);
  (72%nat,Decisions [none (Simple [HealPlayer 1%nat] (Goto 226%nat)); conditional (HasItem Gold 2%nat) (none (Simple [HealPlayer 1%nat; LoseItem Gold 2%nat] (Goto 56%nat))); none (Simple [HealPlayer 1%nat] (Goto 276%nat))]);
  (73%nat,none (Goto 336%nat));
  (74%nat,none (Goto 240%nat));
  (76%nat,can_take (Weapon Dagger) 1%nat (can_take Gold 2%nat (none (Goto 33%nat))));
  (77%nat,Decisions [none (Goto 320%nat); none (Goto 28%nat)]);
  (78%nat,Decisions [none (Simple [DamagePlayer 1%nat; LoseItem BodyArmor 99%nat] (Goto 278%nat)); none (Simple [DamagePlayer 1%nat; LoseItem BodyArmor 99%nat] (Goto 337%nat))]);
  (79%nat,can_take (Weapon Sommerswerd) 1%nat (none (Goto 40%nat)));
  (80%nat,Decisions [conditional (HasItem (GenSpecial S3) 1%nat) (none (Goto 15%nat)); none (Goto 189%nat)]);
  (81%nat,none (Randomly [(Goto 260%nat , (Q2Qc (1 / 2)%Q)); (Goto 281%nat , (Q2Qc (1 / 2)%Q))]));
  (82%nat,Decisions [none (Goto 55%nat); none (Goto 347%nat)]);
  (83%nat,Decisions [none (Goto 227%nat); none (Goto 297%nat)]);
  (86%nat,can_take (Weapon Mace) 1%nat (can_take Gold 3%nat (Decisions [none (Goto 215%nat); none (Goto 303%nat); none (Goto 129%nat)])));
  (87%nat,none (GameLost));
  (88%nat,Decisions [conditional (HasDiscipline (Camouflage)) (none (Goto 179%nat)); conditional (Not (HasDiscipline (Camouflage))) (none (Goto 150%nat)); conditional (Not (HasDiscipline (Camouflage))) (none (Goto 71%nat))]);
  (89%nat,Decisions [none (Goto 233%nat); none (Goto 212%nat)]);
  (91%nat,Decisions [can_take Backpack 1%nat (can_take Meal 1%nat (none (Goto 245%nat))); can_take (Weapon Quarterstaff) 1%nat (can_take Backpack 1%nat (none (Goto 245%nat))); can_take (Weapon Quarterstaff) 1%nat (can_take Meal 1%nat (none (Goto 245%nat))); can_take Meal 1%nat (can_take Meal 1%nat (none (Goto 245%nat))); can_take (Weapon Dagger) 1%nat (can_take Backpack 1%nat (none (Goto 245%nat))); can_take (Weapon Dagger) 1%nat (can_take (Weapon Quarterstaff) 1%nat (none (Goto 245%nat))); can_take (Weapon Dagger) 1%nat (can_take Meal 1%nat (none (Goto 245%nat)))]);
  (92%nat,none (Goto 183%nat));
  (93%nat,none (Goto 137%nat));
  (94%nat,none (Goto 240%nat));
  (95%nat,none (Conditionally [(HasDiscipline (Healing) , Goto 239%nat); (Always true , Goto 28%nat)]));
  (96%nat,none (Goto 112%nat));
  (97%nat,none (Goto 152%nat));
  (98%nat,Decisions [none (Goto 244%nat); none (Goto 115%nat)]);
  (99%nat,none (Randomly [(Goto 326%nat , (Q2Qc (1 / 2)%Q)); (Goto 163%nat , (Q2Qc (1 / 2)%Q))]));
  (100%nat,Decisions [none (Goto 30%nat); none (Goto 267%nat)]);
  (101%nat,none (Goto 222%nat));
  (102%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 325%nat)); conditional (Not (HasDiscipline (Tracking))) (none (Goto 64%nat)); conditional (Not (HasDiscipline (Tracking))) (none (Goto 164%nat))]);
  (103%nat,Decisions [none (Simple [HealPlayer 3%nat] (Goto 249%nat)); can_take Laumspur 1%nat (none (Goto 249%nat))]);
  (104%nat,Decisions [none (Goto 231%nat); none (Goto 177%nat)]);
  (105%nat,none (Randomly [(Goto 286%nat , (Q2Qc (1 / 2)%Q)); (Goto 120%nat , (Q2Qc (1 / 2)%Q))]));
  (106%nat,can_take (Weapon MagicSpear) 1%nat (none (Simple [DamagePlayer 2%nat] (Fight (Details ((22)%Z)%Z 30%nat [EnemyMindblast; Undead; MindblastImmune]) (Goto 320%nat)))));
  (107%nat,none (Conditionally [(HasDiscipline (Healing) , Goto 74%nat); (Always true , Goto 294%nat)]));
  (108%nat,none (Simple [DamagePlayer 2%nat] (Conditionally [(HasDiscipline (SixthSense) , Goto 343%nat); (Always true , Goto 168%nat)])));
  (109%nat,none (Goto 120%nat));
  (110%nat,evade_fight 0%nat 65%nat (Details ((15)%Z)%Z 22%nat []) (Goto 331%nat));
  (111%nat,none (Goto 265%nat));
  (112%nat,none (Goto 230%nat));
  (113%nat,Decisions [none (Goto 73%nat); none (Goto 267%nat)]);
  (114%nat,none (Randomly [(Goto 206%nat , (Q2Qc (2 / 5)%Q)); (Goto 63%nat , (Q2Qc (2 / 5)%Q)); (Goto 8%nat , (Q2Qc (1 / 5)%Q))]));
  (115%nat,Decisions [none (Goto 80%nat); none (Goto 324%nat); none (Goto 162%nat)]);
  (116%nat,none (Randomly [(Simple [GainItem Gold 5%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 6%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 7%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 8%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 9%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 10%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 11%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 12%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 13%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q)); (Simple [GainItem Gold 14%nat] (Goto 314%nat) , (Q2Qc (1 / 10)%Q))]));
  (117%nat,Decisions [conditional (HasItem Gold 3%nat) (none (Simple [LoseItem Gold 3%nat] (Goto 37%nat))); conditional (HasItem Gold 1%nat) (none (Simple [LoseItem Gold 1%nat] (Goto 148%nat))); none (Goto 292%nat)]);
  (118%nat,Decisions [conditional (HasDiscipline (AnimalKinship)) (none (Goto 279%nat)); conditional (Not (HasDiscipline (AnimalKinship))) (none (Goto 23%nat)); conditional (Not (HasDiscipline (AnimalKinship))) (none (Goto 340%nat))]);
  (119%nat,none (Goto 240%nat));
  (120%nat,none (Goto 225%nat));
  (121%nat,none (Goto 186%nat));
  (122%nat,none (Conditionally [(HasDiscipline (SixthSense) , Goto 96%nat); (Always true , Randomly [(Goto 46%nat , (Q2Qc (1 / 2)%Q)); (Goto 112%nat , (Q2Qc (1 / 2)%Q))])]));
  (123%nat,can_take (Weapon Sommerswerd) 1%nat (none (Goto 40%nat)));
  (124%nat,can_take (Weapon ShortSword) 1%nat (can_take Gold 42%nat (can_take (Weapon Dagger) 1%nat (none (Goto 33%nat)))));
  (125%nat,none (Goto 300%nat));
  (127%nat,Decisions [none (Simple [MustEat Hunt] (Goto 217%nat)); none (Simple [MustEat Hunt] (Goto 143%nat))]);
  (129%nat,none (Goto 4%nat));
  (130%nat,none (Goto 314%nat));
  (132%nat,can_take (Weapon Spear) 1%nat (Decisions [none (Goto 317%nat); none (Goto 150%nat)]));
  (133%nat,none (Goto 268%nat));
  (134%nat,none (Conditionally [(HasItem (Weapon MagicSpear) 1%nat , Goto 38%nat); (Always true , Goto 304%nat)]));
  (135%nat,none (Goto 244%nat));
  (136%nat,none (Simple [LoseItem Gold 20%nat] (Goto 10%nat)));
  (137%nat,Decisions [none (Goto 259%nat); none (Goto 20%nat)]);
  (138%nat,Decisions [none (Goto 232%nat); none (Goto 244%nat)]);
  (139%nat,can_take Meal 2%nat (Decisions [none (Goto 27%nat); none (Goto 114%nat)]));
  (140%nat,none (Goto 265%nat));
  (141%nat,Decisions [none (Simple [DamagePlayer 2%nat; LoseItem BodyArmor 99%nat] (Goto 278%nat)); none (Simple [DamagePlayer 2%nat; LoseItem BodyArmor 99%nat] (Goto 337%nat))]);
  (143%nat,Decisions [none (Goto 289%nat); none (Goto 186%nat)]);
  (144%nat,can_take Meal 2%nat (none (Simple [LoseItemKind [SPouch]] (Goto 349%nat))));
  (145%nat,none (Simple [DamagePlayer 5%nat] (Goto 200%nat)));
  (147%nat,none (Goto 47%nat));
  (148%nat,Decisions [none (Simple [MustEat Hunt] (Goto 122%nat)); none (Simple [MustEat Hunt] (Goto 323%nat)); none (Simple [MustEat Hunt] (Goto 257%nat))]);
  (149%nat,Decisions [conditional (HasItem (GenSpecial S3) 1%nat) (none (Goto 223%nat)); none (Goto 250%nat)]);
  (150%nat,Decisions [none (Simple [MustEat Hunt] (Goto 261%nat)); none (Simple [MustEat Hunt] (Goto 334%nat))]);
  (151%nat,none (Randomly [(Goto 262%nat , (Q2Qc (1 / 2)%Q)); (Goto 110%nat , (Q2Qc (1 / 2)%Q))]));
  (152%nat,none (Randomly [(Goto 216%nat , (Q2Qc (2 / 5)%Q)); (Goto 49%nat , (Q2Qc (3 / 10)%Q)); (Goto 193%nat , (Q2Qc (3 / 10)%Q))]));
  (153%nat,Decisions [none (Goto 241%nat); none (Goto 130%nat)]);
  (154%nat,Decisions [none (Simple [DamagePlayer 2%nat] (Goto 308%nat)); none (Simple [DamagePlayer 2%nat] (Goto 197%nat))]);
  (155%nat,none (Goto 265%nat));
  (156%nat,none (Goto 213%nat));
  (157%nat,evade_fight 0%nat 65%nat (Details ((15)%Z)%Z 22%nat []) (Goto 331%nat));
  (159%nat,none (GameLost));
  (160%nat,none (Goto 268%nat));
  (161%nat,none (Goto 186%nat));
  (162%nat,evade_fight 0%nat 244%nat (Details ((20)%Z)%Z 27%nat []) (Goto 302%nat));
  (163%nat,none (Goto 240%nat));
  (164%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 172%nat)); conditional (Not (HasDiscipline (SixthSense))) (none (Goto 52%nat)); conditional (Not (HasDiscipline (SixthSense))) (none (Goto 256%nat))]);
  (165%nat,none (Simple [LoseItem (GenSpecial S3) 1%nat] (Goto 186%nat)));
  (166%nat,Decisions [none (Goto 328%nat); none (Goto 267%nat)]);
  (167%nat,none (Goto 197%nat));
  (168%nat,none (Conditionally [(HasItem Gold 1%nat , Simple [LoseItem Gold 1%nat] (Goto 314%nat)); (Always true , Goto 25%nat)]));
  (169%nat,none (Randomly [(Goto 39%nat , (Q2Qc (2 / 5)%Q)); (Goto 249%nat , (Q2Qc (3 / 10)%Q)); (Goto 339%nat , (Q2Qc (3 / 10)%Q))]));
  (171%nat,Decisions [none (Goto 27%nat); none (Goto 114%nat)]);
  (172%nat,Decisions [none (Goto 52%nat); none (Goto 256%nat)]);
  (173%nat,Decisions [none (Goto 91%nat); none (Goto 6%nat); none (Goto 283%nat)]);
  (174%nat,none (Goto 162%nat));
  (175%nat,none (Randomly [(Goto 53%nat , (Q2Qc (1 / 2)%Q)); (Goto 209%nat , (Q2Qc (1 / 2)%Q))]));
  (176%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 322%nat)); conditional (Not (HasDiscipline (SixthSense))) (none (Goto 45%nat)); conditional (Not (HasDiscipline (SixthSense))) (none (Goto 277%nat))]);
  (177%nat,Decisions [none (Goto 276%nat); none (Goto 342%nat)]);
  (178%nat,none (Goto 200%nat));
  (179%nat,Decisions [none (Goto 82%nat); none (Goto 150%nat); none (Goto 71%nat)]);
  (180%nat,none (Goto 337%nat));
  (181%nat,can_buy Backpack 1%nat (can_buy (Weapon Mace) 4%nat (can_buy (Weapon Spear) 5%nat (can_buy (Weapon Warhammer) 6%nat (can_buy (Weapon ShortSword) 3%nat (can_buy (Weapon Dagger) 2%nat (can_buy (Weapon Sword) 4%nat (none (Goto 186%nat)))))))));
  (182%nat,none (Goto 177%nat));
  (183%nat,none (Randomly [(Goto 311%nat , (Q2Qc (9 / 10)%Q)); (Goto 159%nat , (Q2Qc (1 / 10)%Q))]));
  (184%nat,none (Goto 240%nat));
  (186%nat,(special Cartwheel));
  (187%nat,can_take Gold 6%nat (can_take (Weapon Spear) 2%nat (can_take (Weapon Sword) 2%nat (none (Goto 265%nat)))));
  (188%nat,none (Goto 312%nat));
  (189%nat,Decisions [none (Simple [DamagePlayer 2%nat] (Goto 162%nat)); none (Simple [DamagePlayer 2%nat] (Goto 244%nat))]);
  (190%nat,none (GameLost));
  (192%nat,none (Goto 32%nat));
  (193%nat,none (Goto 100%nat));
  (194%nat,Decisions [none (Simple [LoseItemKind [SPouch; SBackpack; SWeapon; SSpecial]] (Goto 215%nat)); none (Simple [LoseItemKind [SPouch; SBackpack; SWeapon; SSpecial]] (Goto 303%nat)); none (Simple [LoseItemKind [SPouch; SBackpack; SWeapon; SSpecial]] (Goto 129%nat)); none (Simple [LoseItemKind [SPouch; SBackpack; SWeapon; SSpecial]] (Goto 86%nat))]);
  (195%nat,none (Conditionally [(HasItem Gold 1%nat , Simple [LoseItem Gold 1%nat] (Goto 249%nat)); (Always true , Goto 50%nat)]));
  (196%nat,none (Simple [LoseItem (GenSpecial S3) 1%nat] (Conditionally [(HasDiscipline (SixthSense) , Goto 79%nat); (Always true , Goto 123%nat)])));
  (197%nat,none (Randomly [(Goto 78%nat , (Q2Qc (2 / 5)%Q)); (Goto 141%nat , (Q2Qc (1 / 2)%Q)); (Goto 247%nat , (Q2Qc (1 / 10)%Q))]));
  (198%nat,none (Simple [DamagePlayer 1%nat] (Goto 138%nat)));
  (199%nat,none (Goto 143%nat));
  (200%nat,Decisions [none (Goto 60%nat); none (Goto 85%nat); none (Goto 158%nat)]);
  (201%nat,none (Randomly [(Goto 285%nat , (Q2Qc (1 / 2)%Q)); (Goto 70%nat , (Q2Qc (1 / 2)%Q))]));
  (202%nat,none (Goto 31%nat));
  (203%nat,none (Goto 268%nat));
  (204%nat,Decisions [none (Goto 73%nat); none (Goto 267%nat)]);
  (205%nat,none (Goto 213%nat));
  (206%nat,none (Goto 312%nat));
  (207%nat,none (Goto 47%nat));
  (208%nat,none (Goto 134%nat));
  (209%nat,none (Goto 197%nat));
  (210%nat,none (Randomly [(Goto 275%nat , (Q2Qc (1 / 2)%Q)); (Goto 330%nat , (Q2Qc (1 / 2)%Q))]));
  (212%nat,none (GameLost));
  (213%nat,none (GameLost));
  (214%nat,none (GameLost));
  (215%nat,Decisions [none (Goto 4%nat); none (Goto 83%nat)]);
  (216%nat,none (Goto 100%nat));
  (217%nat,Decisions [conditional (HasItem Gold 1%nat) (none (Simple [LoseItem Gold 1%nat] (Goto 199%nat))); none (Goto 143%nat)]);
  (218%nat,Decisions [none (Goto 43%nat); none (Goto 105%nat)]);
  (219%nat,none (Simple [DamagePlayer 3%nat] (Goto 312%nat)));
  (220%nat,can_take Gold 23%nat (none (Goto 33%nat)));
  (221%nat,none (Goto 88%nat));
  (222%nat,Decisions [none (Goto 175%nat); none (Goto 315%nat)]);
  (223%nat,none (Goto 265%nat));
  (224%nat,Decisions [none (Goto 146%nat); none (Goto 34%nat)]);
  (225%nat,none (Goto 350%nat));
  (226%nat,Decisions [conditional (HasItem Gold 2%nat) (none (Simple [LoseItem Gold 2%nat] (Goto 56%nat))); none (Goto 276%nat)]);
  (227%nat,none (Goto 4%nat));
  (228%nat,Decisions [none (Goto 27%nat); none (Goto 114%nat)]);
  (229%nat,Decisions [none (Goto 134%nat); none (Goto 208%nat); none (Goto 164%nat)]);
  (230%nat,Decisions [none (Goto 93%nat); none (Goto 137%nat)]);
  (231%nat,can_take (Weapon Dagger) 1%nat (can_take Gold 5%nat (can_take (GenSpecial S3) 1%nat (Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 182%nat)); conditional (Not (HasDiscipline (Tracking))) (none (Goto 177%nat)); conditional (Not (HasDiscipline (Tracking))) (none (Goto 24%nat)); conditional (Not (HasDiscipline (Tracking))) (none (Goto 253%nat)); conditional (Not (HasDiscipline (Tracking))) (none (Goto 319%nat))]))));
  (232%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 149%nat)); none (Goto 250%nat); none (Goto 68%nat); conditional (HasItem (GenSpecial S3) 1%nat) (none (Goto 223%nat))]);
  (233%nat,Decisions [conditional (HasItem Gold 3%nat) (none (Simple [LoseItem Gold 3%nat] (Goto 37%nat))); conditional (HasItem Gold 1%nat) (none (Simple [LoseItem Gold 1%nat] (Goto 148%nat))); none (Goto 292%nat)]);
  (234%nat,none (GameLost));
  (235%nat,can_take (Weapon ShortSword) 1%nat (Decisions [none (Goto 132%nat); none (Goto 90%nat)]));
  (236%nat,none (Goto 222%nat));
  (238%nat,(special Cartwheel));
  (239%nat,none (Conditionally [(HasDiscipline (Camouflage) , Goto 77%nat); (Always true , Goto 28%nat)]));
  (240%nat,Decisions [conditional (HasDiscipline (Healing)) (Decisions [none (Simple [FullHeal] (Goto 29%nat)); none (Simple [FullHeal] (Goto 236%nat)); none (Simple [FullHeal] (Goto 101%nat))]); conditional (Not (HasDiscipline (Healing))) (Decisions [none (Simple [HalfHeal] (Goto 29%nat)); none (Simple [HalfHeal] (Goto 236%nat)); none (Simple [HalfHeal] (Goto 101%nat))])]);
  (242%nat,none (Goto 152%nat));
  (243%nat,none (Goto 240%nat));
  (244%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 147%nat)); conditional (Not (HasDiscipline (Tracking))) (none (Goto 47%nat)); conditional (Not (HasDiscipline (Tracking))) (none (Goto 207%nat))]);
  (245%nat,Decisions [none (Goto 266%nat); none (Goto 310%nat)]);
  (247%nat,none (GameLost));
  (248%nat,none (GameLost));
  (249%nat,none (Goto 39%nat));
  (250%nat,Decisions [none (Goto 244%nat); none (Goto 68%nat); conditional (HasItem (GenSpecial S3) 1%nat) (none (Goto 223%nat))]);
  (251%nat,none (Goto 194%nat));
  (253%nat,Decisions [none (Goto 303%nat); none (Goto 177%nat)]);
  (254%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 344%nat)); conditional (Not (HasDiscipline (SixthSense))) (none (Goto 69%nat)); conditional (Not (HasDiscipline (SixthSense))) (none (Goto 183%nat))]);
  (255%nat,none (Goto 268%nat));
  (256%nat,none (Goto 134%nat));
  (257%nat,Decisions [none (Goto 335%nat); none (Goto 181%nat)]);
  (258%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 272%nat)); conditional (Not (HasDiscipline (SixthSense))) (none (Goto 17%nat)); conditional (Not (HasDiscipline (SixthSense))) (none (Goto 5%nat))]);
  (259%nat,none (Goto 161%nat));
  (260%nat,can_take (Weapon Sword) 1%nat (none (Goto 240%nat)));
  (261%nat,Decisions [none (Goto 95%nat); none (Goto 198%nat)]);
  (262%nat,can_take Meal 1%nat (can_take Gold 6%nat (can_take (Weapon Quarterstaff) 1%nat (can_take (Weapon Mace) 1%nat (can_take (Weapon Sword) 1%nat (none (Goto 65%nat)))))));
  (264%nat,none (Goto 312%nat));
  (265%nat,none (Conditionally [(HasItem (GenSpecial S3) 1%nat , Goto 202%nat); (Always true , GameLost)]));
  (266%nat,can_sell (Weapon Quarterstaff) 2%nat (can_sell (Weapon Axe) 2%nat (can_sell (Weapon Mace) 3%nat (can_sell (Weapon Spear) 4%nat (can_sell (Weapon Warhammer) 5%nat (can_sell (Weapon ShortSword) 2%nat (can_sell (Weapon BroadSword) 6%nat (can_sell (Weapon Dagger) 1%nat (can_buy (Weapon Quarterstaff) 3%nat (can_buy (Weapon Axe) 3%nat (can_buy (Weapon Mace) 4%nat (can_buy (Weapon Spear) 5%nat (can_buy (Weapon Warhammer) 6%nat (can_buy (Weapon ShortSword) 3%nat (can_buy (Weapon BroadSword) 7%nat (can_buy (Weapon Dagger) 2%nat (can_buy (Weapon Sword) 4%nat (can_sell (Weapon Sword) 3%nat (none (Goto 32%nat))))))))))))))))))));
  (267%nat,Decisions [none (Goto 128%nat); none (Goto 309%nat)]);
  (268%nat,evade_fight 2%nat 125%nat (Details ((16)%Z)%Z 25%nat []) (Goto 333%nat));
  (269%nat,none (Goto 349%nat));
  (271%nat,Decisions [conditional (HasDiscipline (Camouflage)) (none (Goto 151%nat)); conditional (Not (HasDiscipline (Camouflage))) (none (Goto 157%nat)); conditional (Not (HasDiscipline (Camouflage))) (none (Goto 65%nat))]);
  (272%nat,none (Goto 5%nat));
  (273%nat,none (Goto 160%nat));
  (274%nat,can_take Gold 6%nat (can_take (Weapon Mace) 1%nat (can_take (Weapon Sword) 1%nat (none (Goto 132%nat)))));
  (275%nat,none (GameLost));
  (276%nat,Decisions [conditional (HasDiscipline (MindBlast)) (none (Goto 14%nat)); conditional (Not (HasDiscipline (MindBlast))) (none (Fight (Details ((18)%Z)%Z 25%nat [FakeFight 192%nat]) (Goto 305%nat)))]);
  (277%nat,Decisions [none (Goto 311%nat); none (Goto 59%nat)]);
  (278%nat,none (Randomly [(Goto 41%nat , (Q2Qc (7 / 10)%Q)); (Goto 180%nat , (Q2Qc (3 / 10)%Q))]));
  (279%nat,Decisions [none (Goto 23%nat); none (Goto 340%nat)]);
  (280%nat,none (Randomly [(Goto 2%nat , (Q2Qc (1 / 2)%Q)); (Goto 108%nat , (Q2Qc (1 / 2)%Q))]));
  (281%nat,none (Goto 240%nat));
  (283%nat,can_buy Backpack 1%nat (can_buy Meal 2%nat (can_buy Meal 2%nat (can_buy Meal 2%nat (can_buy (Weapon Spear) 5%nat (can_buy (Weapon BroadSword) 6%nat (can_buy (Weapon Dagger) 2%nat (can_buy (Weapon Sword) 4%nat (none (Goto 245%nat))))))))));
  (284%nat,none (Simple [MustEat Hunt] (Goto 9%nat)));
  (285%nat,none (Goto 312%nat));
  (286%nat,none (Goto 109%nat));
  (287%nat,none (Goto 175%nat));
  (288%nat,none (Goto 244%nat));
  (289%nat,Decisions [none (Simple [LoseItem (GenSpecial S3) 1%nat; GainItem Gold 40%nat] (Goto 165%nat)); none (Goto 186%nat)]);
  (290%nat,none (Simple [MustEat NoHunt] (Goto 200%nat)));
  (291%nat,none (Goto 244%nat));
  (292%nat,none (GameLost));
  (293%nat,none (Goto 155%nat));
  (294%nat,none (Goto 240%nat));
  (295%nat,none (Goto 340%nat));
  (297%nat,none (Goto 32%nat));
  (299%nat,Decisions [none (Simple [LoseItem (Weapon MagicSpear) 1%nat] (Goto 118%nat)); conditional (HasItem (Weapon MagicSpear) 1%nat) (none (Goto 102%nat))]);
  (300%nat,none (Randomly [(Goto 224%nat , (Q2Qc (1 / 5)%Q)); (Goto 316%nat , (Q2Qc (1 / 5)%Q)); (Goto 81%nat , (Q2Qc (1 / 5)%Q)); (Goto 22%nat , (Q2Qc (1 / 5)%Q)); (Goto 99%nat , (Q2Qc (1 / 5)%Q))]));
  (301%nat,can_take Gold 3%nat (can_take (Weapon Dagger) 2%nat (can_take (Weapon ShortSword) 1%nat (none (Goto 20%nat)))));
  (302%nat,can_take Backpack 1%nat (can_take Gold 12%nat (can_take (Weapon Mace) 1%nat (can_take Potion4Hp 1%nat (can_take (Weapon BroadSword) 1%nat (can_take (Weapon Quarterstaff) 1%nat (can_take Meal 3%nat (none (Goto 15%nat)))))))));
  (303%nat,Decisions [none (Goto 173%nat); none (Goto 18%nat)]);
  (304%nat,none (GameLost));
  (305%nat,can_take Gold 5%nat (none (Goto 32%nat)));
  (307%nat,Decisions [none (Goto 57%nat); conditional (HasItem (GenSpecial S3) 1%nat) (none (Goto 140%nat)); none (Goto 282%nat)]);
  (308%nat,(special Portholes));
  (309%nat,none (Goto 26%nat));
  (310%nat,none (Goto 32%nat));
  (311%nat,none (Goto 299%nat));
  (312%nat,Decisions [none (Goto 117%nat); none (Goto 89%nat)]);
  (313%nat,none (Simple [DamagePlayer 4%nat] (Goto 349%nat)));
  (314%nat,Decisions [conditional (HasDiscipline (Hunting)) (none (Conditionally [(HasItem Gold 12%nat , Simple [LoseItemKind [SPouch]; GainItem Gold 12%nat] (Goto 290%nat)); (Always true , Goto 290%nat)])); conditional (Not (HasDiscipline (Hunting))) (none (Conditionally [(HasItem Gold 12%nat , Simple [LoseItemKind [SPouch]; GainItem Gold 12%nat] (Goto 36%nat)); (Always true , Goto 36%nat)])); conditional (Not (HasDiscipline (Hunting))) (none (Conditionally [(HasItem Gold 12%nat , Simple [LoseItemKind [SPouch]; GainItem Gold 12%nat] (Simple [MustEat NoHunt] (Goto 178%nat))); (Always true , Simple [MustEat NoHunt] (Goto 178%nat))]))]);
  (315%nat,Decisions [conditional (HasDiscipline (MindOverMatter)) (none (Goto 287%nat)); conditional (Not (HasDiscipline (MindOverMatter))) (none (Goto 190%nat)); conditional (Not (HasDiscipline (MindOverMatter))) (none (Goto 175%nat))]);
  (316%nat,none (Randomly [(Goto 107%nat , (Q2Qc (1 / 2)%Q)); (Goto 94%nat , (Q2Qc (1 / 2)%Q))]));
  (317%nat,none (GameLost));
  (319%nat,Decisions [none (Goto 271%nat); none (Goto 177%nat)]);
  (320%nat,none (Goto 138%nat));
  (321%nat,Decisions [conditional (HasItem Meal 1%nat) (Decisions [none (Simple [LoseItem Meal 1%nat] (Goto 12%nat)); none (Simple [LoseItem Meal 1%nat] (Goto 197%nat))]); conditional (Not (HasItem Meal 1%nat)) (Decisions [none (Simple [DamagePlayer 2%nat] (Goto 12%nat)); none (Simple [DamagePlayer 2%nat] (Goto 197%nat))])]);
  (322%nat,none (Goto 277%nat));
  (323%nat,Decisions [none (Goto 131%nat); none (Goto 298%nat); none (Goto 121%nat)]);
  (324%nat,Decisions [none (Goto 135%nat); none (Goto 174%nat); none (Goto 288%nat)]);
  (325%nat,Decisions [none (Goto 64%nat); none (Goto 164%nat)]);
  (328%nat,Decisions [conditional (HasItem (GenSpecial S1) 1%nat) (none (Goto 113%nat)); conditional (HasDiscipline (Tracking)) (none (Goto 204%nat)); conditional (Not (HasDiscipline (Tracking))) (none (Goto 73%nat)); conditional (Not (HasDiscipline (Tracking))) (none (Goto 267%nat))]);
  (329%nat,can_take Gold 10%nat (none (Goto 197%nat)));
  (330%nat,none (Simple [DamagePlayer 5%nat] (Goto 200%nat)));
  (331%nat,can_take Gold 3%nat (can_take (Weapon Dagger) 1%nat (can_take (Weapon Sword) 1%nat (none (Goto 65%nat)))));
  (332%nat,evade_fight 0%nat 92%nat (Details ((21)%Z)%Z 30%nat [EnemyMindblast; Undead; MindblastImmune]) (Goto 183%nat));
  (333%nat,Decisions [none (Goto 300%nat); none (Goto 67%nat)]);
  (334%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 98%nat)); conditional (Not (HasDiscipline (Tracking))) (none (Goto 115%nat)); conditional (Not (HasDiscipline (Tracking))) (none (Goto 291%nat))]);
  (335%nat,Decisions [none (Goto 161%nat); none (Goto 61%nat)]);
  (336%nat,Decisions [none (Goto 109%nat); none (Goto 185%nat)]);
  (337%nat,Decisions [conditional (HasDiscipline (Hunting)) (none (Simple [LoseItemKind [SBackpack; SWeapon]] (Goto 139%nat))); conditional (Not (HasDiscipline (Hunting))) (none (Simple [LoseItemKind [SBackpack; SWeapon]] (Goto 228%nat))); conditional (Not (HasDiscipline (Hunting))) (none (Simple [DamagePlayer 3%nat; LoseItemKind [SBackpack; SWeapon]] (Goto 171%nat)))]);
  (338%nat,Decisions [none (Simple [DamagePlayer 2%nat] (Goto 269%nat)); none (Simple [DamagePlayer 2%nat] (Goto 349%nat))]);
  (339%nat,none (Conditionally [(HasItem Gold 1%nat , Simple [LoseItem Gold 1%nat] (Goto 249%nat)); (Always true , Goto 50%nat)]));
  (340%nat,Decisions [none (Goto 64%nat); none (Goto 164%nat)]);
  (341%nat,none (Goto 240%nat));
  (342%nat,Decisions [conditional (HasItem Gold 1%nat) (none (Simple [LoseItem Gold 1%nat] (Goto 72%nat))); conditional (HasItem Gold 2%nat) (none (Simple [LoseItem Gold 2%nat] (Goto 56%nat))); none (Goto 226%nat)]);
  (343%nat,none (Goto 168%nat));
  (344%nat,none (Goto 183%nat));
  (346%nat,Decisions [conditional (HasItem Gold 2%nat) (none (Simple [LoseItem Gold 2%nat] (Goto 280%nat))); conditional (HasItem Gold 1%nat) (none (Simple [LoseItem Gold 1%nat] (Simple [MustEat NoHunt] (Goto 280%nat)))); none (Simple [MustEat NoHunt] (Goto 205%nat))]);
  (347%nat,none (Simple [DamagePlayer 1%nat] (Goto 150%nat)));
  (348%nat,evade_fight 2%nat 125%nat (Details ((16)%Z)%Z 25%nat []) (Goto 333%nat));
  (349%nat,Decisions [none (Goto 87%nat); none (Goto 284%nat)]);
  (350%nat,none (GameWon));
  (5%nat,none (Simple [SetFlag HadCombat] (Goto 351%nat)));
  (351%nat,none (Fight (Details ((22)%Z)%Z 20%nat [Undead; MindblastImmune]) (Goto 352%nat)));
  (352%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 166%nat))));
  (7%nat,none (Simple [SetFlag HadCombat] (Goto 353%nat)));
  (353%nat,none (Fight (Details ((28)%Z)%Z 30%nat [MindblastImmune; Timed 1%nat (CombatBonus (2)%Z)]) (Goto 354%nat)));
  (354%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 33%nat))));
  (30%nat,none (Simple [SetFlag HadCombat] (Goto 355%nat)));
  (355%nat,none (Fight (Details ((13)%Z)%Z 16%nat [Undead; MindblastImmune]) (Goto 356%nat)));
  (356%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 258%nat))));
  (34%nat,none (Simple [SetFlag HadCombat] (Goto 357%nat)));
  (357%nat,none (Fight (Details ((16)%Z)%Z 14%nat []) (Goto 358%nat)));
  (358%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 345%nat))));
  (60%nat,none (Simple [SetFlag HadCombat] (Goto 359%nat)));
  (359%nat,none (Fight (Details ((8)%Z)%Z 11%nat [Timed 2%nat (PlayerInvulnerable)]) (Goto 360%nat)));
  (360%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 76%nat))));
  (66%nat,none (Simple [SetFlag HadCombat] (Goto 361%nat)));
  (361%nat,none (Fight (Details ((15)%Z)%Z 15%nat [MindblastImmune; Undead]) (Goto 362%nat)));
  (362%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 218%nat))));
  (85%nat,none (Simple [SetFlag HadCombat] (Goto 363%nat)));
  (363%nat,none (Fight (Details ((24)%Z)%Z 27%nat []) (Goto 364%nat)));
  (364%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 124%nat))));
  (90%nat,evade_fight 0%nat 132%nat (Details ((10)%Z)%Z 16%nat []) (Simple [SetFlag HadCombat] (Goto 365%nat)));
  (365%nat,none (Fight (Details ((6)%Z)%Z 9%nat [MultiFight]) (Goto 366%nat)));
  (366%nat,none (Fight (Details ((11)%Z)%Z 14%nat [MultiFight]) (Goto 367%nat)));
  (367%nat,none (Fight (Details ((5)%Z)%Z 8%nat [MultiFight]) (Goto 368%nat)));
  (368%nat,none (Fight (Details ((11)%Z)%Z 17%nat []) (Goto 369%nat)));
  (369%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 274%nat))));
  (128%nat,none (Simple [SetFlag HadCombat] (Goto 370%nat)));
  (370%nat,none (Fight (Details ((13)%Z)%Z 19%nat [Undead]) (Goto 371%nat)));
  (371%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 237%nat))));
  (131%nat,evade_fight 0%nat 121%nat (Details ((15)%Z)%Z 23%nat [BareHanded]) (Simple [SetFlag HadCombat] (Goto 372%nat)));
  (372%nat,none (Fight (Details ((13)%Z)%Z 21%nat [MultiFight; BareHanded]) (Goto 373%nat)));
  (373%nat,none (Fight (Details ((13)%Z)%Z 20%nat [BareHanded]) (Goto 374%nat)));
  (374%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 301%nat))));
  (146%nat,none (Simple [SetFlag HadCombat] (Goto 375%nat)));
  (375%nat,none (Fight (Details ((15)%Z)%Z 15%nat []) (Goto 376%nat)));
  (376%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 345%nat))));
  (158%nat,none (Simple [SetFlag HadCombat] (Goto 377%nat)));
  (377%nat,none (Fight (Details ((16)%Z)%Z 23%nat []) (Goto 378%nat)));
  (378%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 220%nat))));
  (185%nat,evade_fight 0%nat 286%nat (Details ((17)%Z)%Z 25%nat []) (Simple [SetFlag HadCombat] (Goto 379%nat)));
  (379%nat,none (Fight (Details ((16)%Z)%Z 26%nat []) (Goto 380%nat)));
  (380%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 120%nat))));
  (237%nat,none (Simple [SetFlag HadCombat] (Goto 381%nat)));
  (381%nat,none (Fight (Details ((23)%Z)%Z 30%nat [Undead; MindblastImmune]) (Goto 382%nat)));
  (382%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 309%nat))));
  (241%nat,none (Simple [SetFlag HadCombat] (Goto 383%nat)));
  (383%nat,none (Fight (Details ((17)%Z)%Z 25%nat []) (Goto 384%nat)));
  (384%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 21%nat))));
  (270%nat,none (Simple [SetFlag HadCombat] (Goto 385%nat)));
  (385%nat,none (Fight (Details ((28)%Z)%Z 30%nat [MindblastImmune; Timed 1%nat (CombatBonus (2)%Z)]) (Goto 386%nat)));
  (386%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 33%nat))));
  (282%nat,none (Simple [SetFlag HadCombat] (Goto 387%nat)));
  (387%nat,none (Fight (Details ((16)%Z)%Z 24%nat [MultiFight]) (Goto 388%nat)));
  (388%nat,none (Fight (Details ((16)%Z)%Z 22%nat []) (Goto 389%nat)));
  (389%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 187%nat))));
  (296%nat,evade_fight 0%nat 88%nat (Details ((13)%Z)%Z 22%nat []) (Simple [SetFlag HadCombat] (Goto 390%nat)));
  (390%nat,none (Fight (Details ((12)%Z)%Z 20%nat [MultiFight]) (Goto 391%nat)));
  (391%nat,none (Fight (Details ((11)%Z)%Z 19%nat [MultiFight]) (Goto 392%nat)));
  (392%nat,none (Fight (Details ((11)%Z)%Z 19%nat [MultiFight]) (Goto 393%nat)));
  (393%nat,none (Fight (Details ((10)%Z)%Z 18%nat [MultiFight]) (Goto 394%nat)));
  (394%nat,none (Fight (Details ((10)%Z)%Z 17%nat []) (Goto 395%nat)));
  (395%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 221%nat))));
  (298%nat,evade_fight 0%nat 121%nat (Details ((15)%Z)%Z 23%nat [BareHanded]) (Simple [SetFlag HadCombat] (Goto 396%nat)));
  (396%nat,none (Fight (Details ((13)%Z)%Z 21%nat [MultiFight; BareHanded]) (Goto 397%nat)));
  (397%nat,none (Fight (Details ((13)%Z)%Z 20%nat [BareHanded]) (Goto 398%nat)));
  (398%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 301%nat))));
  (306%nat,none (Simple [SetFlag HadCombat] (Goto 399%nat)));
  (399%nat,none (Fight (Details ((16)%Z)%Z 24%nat [DoubleDamage]) (Goto 400%nat)));
  (400%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 35%nat))));
  (326%nat,none (Simple [SetFlag HadCombat] (Goto 401%nat)));
  (401%nat,none (Fight (Details ((15)%Z)%Z 25%nat []) (Goto 402%nat)));
  (402%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 184%nat))));
  (345%nat,none (Simple [SetFlag HadCombat] (Goto 403%nat)));
  (403%nat,none (Fight (Details ((16)%Z)%Z 24%nat []) (Goto 404%nat)));
  (404%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 243%nat))))].