Require Import chapters.
Require Import Stdlib.QArith.Qcanon.
Require Import Stdlib.QArith.QArith.
Require Import Stdlib.Lists.List.
Import ListNotations.
Definition chapters := [(1%nat,Decisions [none (Goto 160%nat); none (Goto 273%nat)]);
  (2%nat,can_take Backpack 1%nat (can_take Gold 12%nat (can_take Meal 2%nat (can_take (Weapon Sword) 1%nat (can_take (Weapon Mace) 1%nat (can_take (Weapon Dagger) 1%nat (can_take (Weapon Warhammer) 1%nat (none (Goto 200%nat)))))))));
  (3%nat,none (Simple [DamagePlayer 1%nat] (Goto 62%nat)));
  (4%nat,none (Goto 40%nat));
  (5%nat,none (Goto 186%nat));
  (6%nat,Decisions [none (Goto 80%nat); none (Goto 175%nat)]);
  (7%nat,none (Goto 154%nat));
  (8%nat,Decisions [none (Goto 151%nat); none (Goto 240%nat)]);
  (9%nat,Decisions [none (Goto 112%nat); none (Goto 342%nat)]);
  (10%nat,can_take (GenSpecial S11) 1%nat (none (Goto 59%nat)));
  (11%nat,none (Randomly [(Goto 97%nat , (Q2Qc (1 / 2)%Q)); (Goto 190%nat , (Q2Qc (1 / 2)%Q))]));
  (12%nat,can_take Backpack 1%nat (can_take Laumspur 1%nat (can_take (Weapon Sword) 1%nat (can_take (Weapon Spear) 1%nat (none (Goto 140%nat))))));
  (13%nat,none (Randomly [(Goto 171%nat , (Q2Qc (1 / 2)%Q)); (Goto 25%nat , (Q2Qc (1 / 2)%Q))]));
  (14%nat,evade_fight 0%nat 31%nat (Details ((17)%Z)%Z 28%nat []) (Goto 146%nat));
  (15%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 264%nat)); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Goto 134%nat)])]);
  (16%nat,Decisions [none (Goto 123%nat); none (Goto 169%nat)]);
  (17%nat,none (GameLost));
  (18%nat,none (Goto 150%nat));
  (19%nat,none (Simple [MustEat NoHunt] (Goto 233%nat)));
  (20%nat,none (Goto 341%nat));
  (21%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 264%nat)); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Goto 134%nat); none (Goto 191%nat)])]);
  (22%nat,none (LoseItemFrom SBackpack 1%nat (Goto 157%nat)));
  (23%nat,Decisions [conditional (HasItem (GenSpecial S0) 1%nat) (none (Simple [LoseItem (GenSpecial S0) 1%nat] (Goto 282%nat))); conditional (Not (HasItem (GenSpecial S0) 1%nat)) (Decisions [none (Simple [LoseItem (GenSpecial S0) 1%nat] (Goto 105%nat))])]);
  (24%nat,Decisions [conditional (HasDiscipline (Healing)) (none (Goto 238%nat)); none (Goto 223%nat); none (Goto 207%nat)]);
  (25%nat,Decisions [none (Goto 290%nat); none (Goto 141%nat)]);
  (27%nat,none (Goto 200%nat));
  (28%nat,none (Goto 348%nat));
  (29%nat,Decisions [conditional (HasItem (GenSpecial S1) 1%nat) (none (Goto 168%nat)); conditional (Not (HasItem (GenSpecial S1) 1%nat)) (Decisions [none (Goto 246%nat); none (Goto 183%nat)])]);
  (30%nat,none (Goto 176%nat));
  (31%nat,none (Randomly [(Goto 272%nat , (Q2Qc (1 / 2)%Q)); (Goto 329%nat , (Q2Qc (1 / 2)%Q))]));
  (32%nat,none (Goto 309%nat));
  (33%nat,Decisions [none (Goto 74%nat); none (Goto 139%nat); none (Goto 251%nat)]);
  (34%nat,Decisions [none (Goto 235%nat); none (Goto 183%nat)]);
  (35%nat,none (Conditionally [(COr (HasDiscipline (Hunting)) (HasLevel Guardian) , Randomly [(Goto 147%nat , (Q2Qc (1 / 2)%Q)); (Goto 231%nat , (Q2Qc (1 / 2)%Q))]); (Always true , Randomly [(Goto 147%nat , (Q2Qc (4 / 5)%Q)); (Goto 231%nat , (Q2Qc (1 / 5)%Q))])]));
  (37%nat,Decisions [none (Goto 182%nat); none (Goto 247%nat)]);
  (38%nat,Decisions [none (Goto 297%nat); none (Goto 15%nat)]);
  (39%nat,none (Goto 148%nat));
  (40%nat,Decisions [conditional (CAnd (HasDiscipline (Tracking)) (HasLevel Aspirant)) (none (Goto 349%nat)); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Goto 55%nat); none (Goto 291%nat)])]);
  (41%nat,none (Goto 276%nat));
  (42%nat,none (GameLost));
  (43%nat,none (Conditionally [(CAnd (COr (HasDiscipline (MindOverMatter)) (COr (COr (COr (COr (COr (COr (COr (COr (COr (COr (HasDiscipline (WeaponSkill Dagger)) (HasDiscipline (WeaponSkill Spear))) (HasDiscipline (WeaponSkill Mace))) (HasDiscipline (WeaponSkill ShortSword))) (HasDiscipline (WeaponSkill Warhammer))) (HasDiscipline (WeaponSkill Sword))) (HasDiscipline (WeaponSkill Axe))) (HasDiscipline (WeaponSkill Quarterstaff))) (HasDiscipline (WeaponSkill BroadSword))) (HasDiscipline (WeaponSkill MagicSpear))) (HasDiscipline (WeaponSkill Sommerswerd)))) (COr (HasDiscipline (Hunting)) (HasDiscipline (SixthSense))) , Randomly [(Goto 262%nat , (Q2Qc (2 / 5)%Q)); (Goto 111%nat , (Q2Qc (3 / 5)%Q))]); (COr (HasDiscipline (MindOverMatter)) (COr (COr (COr (COr (COr (COr (COr (COr (COr (COr (HasDiscipline (WeaponSkill Dagger)) (HasDiscipline (WeaponSkill Spear))) (HasDiscipline (WeaponSkill Mace))) (HasDiscipline (WeaponSkill ShortSword))) (HasDiscipline (WeaponSkill Warhammer))) (HasDiscipline (WeaponSkill Sword))) (HasDiscipline (WeaponSkill Axe))) (HasDiscipline (WeaponSkill Quarterstaff))) (HasDiscipline (WeaponSkill BroadSword))) (HasDiscipline (WeaponSkill MagicSpear))) (HasDiscipline (WeaponSkill Sommerswerd))) , Randomly [(Goto 262%nat , (Q2Qc (3 / 5)%Q)); (Goto 111%nat , (Q2Qc (2 / 5)%Q))]); (COr (HasDiscipline (Hunting)) (HasDiscipline (SixthSense)) , Randomly [(Goto 262%nat , (Q2Qc (1 / 2)%Q)); (Goto 111%nat , (Q2Qc (1 / 2)%Q))]); (Always true , Randomly [(Goto 262%nat , (Q2Qc (7 / 10)%Q)); (Goto 111%nat , (Q2Qc (3 / 10)%Q))])]));
  (44%nat,can_take Gold 12%nat (can_take Meal 2%nat (Decisions [conditional (HasDiscipline (Healing)) (none (Goto 149%nat)); conditional (Not (HasDiscipline (Healing))) (Decisions [none (Goto 188%nat)])])));
  (45%nat,none (Goto 307%nat));
  (48%nat,none (Goto 145%nat));
  (49%nat,none (Goto 204%nat));
  (50%nat,none (Simple [LoseItem (GenSpecial S0) 1%nat] (Randomly [(Goto 184%nat , (Q2Qc (7 / 10)%Q)); (Goto 267%nat , (Q2Qc (3 / 10)%Q))])));
  (51%nat,Decisions [conditional (HasDiscipline (AnimalKinship)) (none (Goto 227%nat)); conditional (Not (HasDiscipline (AnimalKinship))) (Decisions [none (Goto 328%nat); none (Goto 120%nat)])]);
  (52%nat,none (Simple [DamagePlayer 1%nat] (Goto 248%nat)));
  (54%nat,Decisions [conditional (CAnd (HasDiscipline (Healing)) (HasLevel Warmarn)) (none (Simple [LoseItem (GenBackpack S3) 1%nat; LoseItem (GenBackpack S4) 1%nat] (Goto 4%nat))); conditional (Not (HasDiscipline (Healing))) (Decisions [none (Simple [LoseItem (GenBackpack S3) 1%nat; LoseItem (GenBackpack S4) 1%nat] (Goto 65%nat)); none (Simple [LoseItem (GenBackpack S3) 1%nat; LoseItem (GenBackpack S4) 1%nat] (Goto 201%nat))])]);
  (55%nat,Decisions [none (Goto 161%nat); none (Goto 286%nat)]);
  (57%nat,none (Conditionally [(CAnd (HasItem (Weapon Sword) 1%nat) (HasFlag Special01) , Goto 327%nat); (Always true , Goto 289%nat)]));
  (58%nat,Decisions [none (Goto 222%nat); none (Goto 110%nat)]);
  (59%nat,none (Randomly [(Goto 193%nat , (Q2Qc (1 / 2)%Q)); (Goto 260%nat , (Q2Qc (1 / 2)%Q))]));
  (60%nat,none (Goto 199%nat));
  (61%nat,Decisions [none (Goto 304%nat); none (Goto 136%nat); none (Goto 189%nat)]);
  (63%nat,none (Randomly [(Goto 259%nat , (Q2Qc (1 / 2)%Q)); (Goto 95%nat , (Q2Qc (1 / 2)%Q))]));
  (64%nat,Decisions [none (Goto 170%nat); none (Goto 228%nat)]);
  (66%nat,none (Goto 124%nat));
  (67%nat,none (Simple [DamagePlayer 1%nat] (Conditionally [(HasItem (Weapon Sommerswerd) 1%nat , Goto 292%nat); (COr (HasDiscipline (Hunting)) (HasDiscipline (MindOverMatter)) , Randomly [(Goto 242%nat , (Q2Qc (3 / 10)%Q)); (Goto 263%nat , (Q2Qc (2 / 5)%Q)); (Goto 278%nat , (Q2Qc (3 / 10)%Q))]); (Always true , Randomly [(Goto 242%nat , (Q2Qc (1 / 2)%Q)); (Goto 263%nat , (Q2Qc (2 / 5)%Q)); (Goto 278%nat , (Q2Qc (1 / 10)%Q))])])));
  (68%nat,Decisions [none (Goto 180%nat); none (Goto 213%nat)]);
  (69%nat,Decisions [none (Goto 125%nat); none (Goto 348%nat)]);
  (70%nat,none (Conditionally [(HasItem (GenSpecial S11) 1%nat , Goto 305%nat); (CAnd (HasDiscipline (Camouflage)) (HasLevel Guardian) , Goto 49%nat); (Always true , Goto 159%nat)]));
  (71%nat,none (Goto 348%nat));
  (72%nat,none (Goto 211%nat));
  (73%nat,Decisions [conditional (HasItem (GenBackpack S0) 1%nat) (none (Goto 283%nat)); conditional (Not (HasItem (GenBackpack S0) 1%nat)) (Decisions [none (Goto 325%nat)])]);
  (74%nat,Decisions [none (Simple [HealPlayer 1%nat] (Goto 38%nat)); none (Simple [HealPlayer 1%nat] (Goto 175%nat)); none (Simple [HealPlayer 1%nat] (Goto 293%nat))]);
  (75%nat,none (Simple [DamagePlayer 2%nat] (Conditionally [(HasDiscipline (Camouflage) , Randomly [(Goto 192%nat , (Q2Qc (3 / 10)%Q)); (Goto 16%nat , (Q2Qc (7 / 10)%Q))]); (Always true , Randomly [(Goto 192%nat , (Q2Qc (3 / 5)%Q)); (Goto 16%nat , (Q2Qc (2 / 5)%Q))])])));
  (76%nat,Decisions [none (Goto 268%nat); none (Goto 64%nat)]);
  (77%nat,evade_fight 2%nat 98%nat (Details ((22)%Z)%Z 28%nat [MindblastImmune; EnemyMindblast]) (Goto 10%nat));
  (78%nat,can_take (GenBackpack S0) 1%nat (none (Simple [MustEat Hunt] (Goto 233%nat))));
  (79%nat,can_take (GenBackpack S2) 1%nat (can_take (GenBackpack S1) 5%nat (none (Goto 117%nat))));
  (80%nat,none (Goto 175%nat));
  (81%nat,Decisions [none (Goto 173%nat); none (Goto 224%nat)]);
  (82%nat,Decisions [none (Goto 337%nat); none (Goto 297%nat); none (Goto 15%nat)]);
  (83%nat,none (Goto 199%nat));
  (84%nat,can_take (GenSpecial S2) 1%nat (none (Goto 273%nat)));
  (85%nat,none (GameLost));
  (86%nat,none (Goto 186%nat));
  (87%nat,Decisions [conditional (COr (HasDiscipline (SixthSense)) (HasDiscipline (Tracking))) (none (Goto 60%nat)); conditional (Not (COr (HasDiscipline (SixthSense)) (HasDiscipline (Tracking)))) (Decisions [none (Goto 199%nat); none (Goto 208%nat)])]);
  (91%nat,Decisions [none (Goto 254%nat); none (Goto 191%nat)]);
  (92%nat,Decisions [conditional (HasDiscipline (SixthSense)) (none (Goto 210%nat)); conditional (Not (HasDiscipline (SixthSense))) (Decisions [none (Goto 132%nat); none (Goto 301%nat)])]);
  (94%nat,none (Simple [LoseItemKind [SBackpack]] (Goto 219%nat)));
  (95%nat,Decisions [none (Goto 259%nat); none (Goto 195%nat)]);
  (96%nat,none (Randomly [(Goto 47%nat , (Q2Qc (1 / 2)%Q)); (Goto 234%nat , (Q2Qc (2 / 5)%Q)); (Goto 334%nat , (Q2Qc (1 / 10)%Q))]));
  (97%nat,none (Goto 199%nat));
  (98%nat,none (Goto 59%nat));
  (99%nat,none (GameLost));
  (100%nat,none (Goto 215%nat));
  (101%nat,Decisions [none (Goto 343%nat); none (Goto 115%nat)]);
  (102%nat,can_take Gold 12%nat (can_take Meal 2%nat (Decisions [conditional (HasDiscipline (Healing)) (none (Goto 19%nat)); conditional (Not (HasDiscipline (Healing))) (Decisions [none (Goto 339%nat)])])));
  (103%nat,none (Simple [DamagePlayer 4%nat] (Goto 59%nat)));
  (104%nat,Decisions [none (Goto 303%nat); none (Goto 342%nat)]);
  (105%nat,Decisions [none (Goto 285%nat); none (Goto 267%nat)]);
  (106%nat,Decisions [none (Goto 67%nat); none (Goto 236%nat)]);
  (107%nat,Decisions [none (Goto 59%nat); none (Goto 310%nat)]);
  (108%nat,evade_fight 0%nat 271%nat (Details ((20)%Z)%Z 30%nat []) (Goto 28%nat));
  (109%nat,can_take Gold 3%nat (can_take (Weapon Dagger) 1%nat (can_take (Weapon Sword) 1%nat (Decisions [none (Goto 347%nat); none (Goto 258%nat)]))));
  (110%nat,none (Goto 165%nat));
  (111%nat,Decisions [none (Goto 90%nat); none (Goto 163%nat)]);
  (112%nat,none (Conditionally [(HasEndurance 21%nat , Randomly [(Goto 42%nat , (Q2Qc (1 / 5)%Q)); (Goto 303%nat , (Q2Qc (4 / 5)%Q))]); (HasEndurance 10%nat , Randomly [(Goto 42%nat , (Q2Qc (1 / 2)%Q)); (Goto 303%nat , (Q2Qc (1 / 2)%Q))]); (Always true , Randomly [(Goto 42%nat , (Q2Qc (4 / 5)%Q)); (Goto 303%nat , (Q2Qc (1 / 5)%Q))])]));
  (113%nat,Decisions [conditional (HasLevel Warmarn) (none (Goto 166%nat)); conditional (Not (HasLevel Warmarn)) (Decisions [none (Goto 14%nat); none (Goto 316%nat); none (Goto 232%nat)])]);
  (115%nat,Decisions [none (Simple [LoseItem (GenBackpack S3) 1%nat; LoseItem (GenBackpack S4) 1%nat] (Goto 8%nat)); none (Simple [LoseItem (GenBackpack S3) 1%nat; LoseItem (GenBackpack S4) 1%nat] (Goto 240%nat))]);
  (116%nat,none (Goto 318%nat));
  (117%nat,none (Conditionally [(COr (CAnd (HasItem (GenBackpack S2) 1%nat) (HasItem (GenBackpack S1) 1%nat)) (HasItem (GenSpecial S1) 1%nat) , Goto 22%nat); (COr (HasDiscipline (SixthSense)) (HasDiscipline (Tracking)) , Randomly [(Goto 99%nat , (Q2Qc (2 / 5)%Q)); (Goto 256%nat , (Q2Qc (3 / 5)%Q))]); (Always true , Randomly [(Goto 99%nat , (Q2Qc (7 / 10)%Q)); (Goto 256%nat , (Q2Qc (3 / 10)%Q))])]));
  (118%nat,Decisions [none (Goto 308%nat); none (Goto 170%nat); none (Goto 228%nat)]);
  (119%nat,Decisions [none (Goto 296%nat); none (Goto 73%nat)]);
  (120%nat,Decisions [none (Goto 33%nat); none (Goto 92%nat)]);
  (121%nat,none (Goto 248%nat));
  (122%nat,none (Simple [DamagePlayer 1%nat] (Conditionally [(HasDiscipline (MindBlast) , Fight (Details ((25)%Z)%Z 29%nat [MindblastImmune]) (Goto 350%nat)); (Always true , Fight (Details ((25)%Z)%Z 29%nat [MindblastImmune; CombatBonus (-4)%Z]) (Goto 350%nat))])));
  (123%nat,can_take (GenBackpack S2) 1%nat (can_take (GenBackpack S1) 5%nat (none (Goto 315%nat))));
  (124%nat,Decisions [none (Goto 333%nat); none (Goto 107%nat)]);
  (126%nat,none (Simple [MustEat Hunt] (Randomly [(Goto 25%nat , (Q2Qc (1 / 2)%Q)); (Goto 171%nat , (Q2Qc (1 / 2)%Q))])));
  (127%nat,Decisions [none (Simple [SetFlag FoughtElix] (Goto 178%nat)); none (Simple [SetFlag FoughtElix] (Goto 245%nat))]);
  (128%nat,none (Conditionally [(HasDiscipline (Hunting) , Randomly [(Goto 103%nat , (Q2Qc (1 / 5)%Q)); (Goto 98%nat , (Q2Qc (4 / 5)%Q))]); (Always true , Randomly [(Goto 103%nat , (Q2Qc (1 / 2)%Q)); (Goto 98%nat , (Q2Qc (1 / 2)%Q))])]));
  (129%nat,none (Simple [MustEat NoHunt] (Goto 309%nat)));
  (130%nat,Decisions [none (Goto 68%nat); none (Goto 331%nat)]);
  (131%nat,none (Goto 185%nat));
  (132%nat,Decisions [none (Goto 67%nat); none (Goto 287%nat)]);
  (133%nat,evade_fight 0%nat 307%nat (Details ((18)%Z)%Z 35%nat [OnDamage 17%nat]) (Goto 265%nat));
  (134%nat,Decisions [none (Goto 91%nat); none (Goto 191%nat)]);
  (135%nat,Decisions [none (Goto 284%nat); none (Goto 211%nat); none (Goto 30%nat)]);
  (136%nat,Decisions [conditional (HasDiscipline (Healing)) (none (Goto 313%nat)); conditional (Not (HasDiscipline (Healing))) (Decisions [none (Goto 216%nat)])]);
  (137%nat,none (Goto 12%nat));
  (138%nat,evade_fight 0%nat 81%nat (Details ((13)%Z)%Z 29%nat []) (Goto 152%nat));
  (139%nat,Decisions [none (Simple [MustEat Hunt] (Goto 206%nat)); none (Simple [MustEat Hunt] (Goto 330%nat)); none (Simple [MustEat Hunt] (Goto 92%nat))]);
  (140%nat,Decisions [none (Goto 70%nat); none (Goto 314%nat)]);
  (141%nat,none (Simple [MustEat Hunt] (Goto 253%nat)));
  (142%nat,Decisions [none (Goto 183%nat); none (Goto 270%nat)]);
  (144%nat,none (GameLost));
  (145%nat,Decisions [none (Goto 322%nat); none (Goto 162%nat)]);
  (146%nat,none (Goto 272%nat));
  (148%nat,none (Goto 137%nat));
  (149%nat,none (Goto 188%nat));
  (150%nat,Decisions [none (Goto 164%nat); none (Goto 288%nat); none (Goto 6%nat)]);
  (151%nat,Decisions [none (Goto 320%nat); none (Goto 197%nat)]);
  (152%nat,can_take Gold 6%nat (can_take (Weapon Sword) 1%nat (can_take Meal 2%nat (none (Goto 81%nat)))));
  (154%nat,none (Randomly [(Goto 120%nat , (Q2Qc (3 / 10)%Q)); (Goto 51%nat , (Q2Qc (7 / 10)%Q))]));
  (155%nat,none (Goto 225%nat));
  (156%nat,Decisions [none (Goto 212%nat); none (Goto 101%nat)]);
  (157%nat,none (Simple [HealPlayer 1%nat] (Goto 309%nat)));
  (158%nat,none (Simple [DamagePlayer 3%nat; LoseItemKind [SBackpack]] (Goto 219%nat)));
  (159%nat,none (Simple [DamagePlayer 2%nat] (Goto 204%nat)));
  (160%nat,Decisions [none (Goto 84%nat); none (Goto 205%nat); none (Goto 306%nat)]);
  (161%nat,Decisions [none (Goto 27%nat); none (Goto 144%nat); none (Goto 294%nat)]);
  (162%nat,Decisions [none (Goto 214%nat); none (Goto 117%nat)]);
  (163%nat,none (Goto 249%nat));
  (164%nat,Decisions [none (Goto 299%nat); none (Goto 52%nat)]);
  (165%nat,Decisions [none (Goto 319%nat); none (Simple [MustEat NoHunt] (Goto 13%nat))]);
  (166%nat,none (Goto 232%nat));
  (167%nat,can_take Backpack 1%nat (can_take Meal 2%nat (none (Goto 185%nat))));
  (168%nat,Decisions [conditional (HasItem (Weapon Sommerswerd) 1%nat) (none (Goto 34%nat)); conditional (Not (HasItem (Weapon Sommerswerd) 1%nat)) (Decisions [none (Goto 85%nat)])]);
  (170%nat,Decisions [none (Goto 228%nat); none (Goto 221%nat)]);
  (171%nat,Decisions [none (Goto 63%nat); none (Goto 141%nat)]);
  (172%nat,none (Goto 55%nat));
  (173%nat,none (Simple [LoseItem (GenBackpack S3) 1%nat; LoseItem (GenBackpack S4) 1%nat] (Conditionally [(HasItem (Weapon Sommerswerd) 1%nat , Goto 275%nat); (CAnd (HasItem (GenBackpack S3) 1%nat) (HasItem (GenBackpack S4) 1%nat) , Randomly [(Goto 143%nat , (Q2Qc (1 / 2)%Q)); (Goto 179%nat , (Q2Qc (1 / 2)%Q))]); (Always true , Randomly [(Goto 143%nat , (Q2Qc (7 / 10)%Q)); (Goto 179%nat , (Q2Qc (3 / 10)%Q))])])));
  (174%nat,none (Goto 148%nat));
  (175%nat,none (Goto 297%nat));
  (176%nat,none (Simple [DamagePlayer 3%nat] (Fight (Details ((17)%Z)%Z 25%nat []) (Goto 7%nat))));
  (177%nat,none (GameLost));
  (178%nat,none (Goto 245%nat));
  (179%nat,none (Goto 335%nat));
  (180%nat,none (Goto 241%nat));
  (181%nat,none (GameLost));
  (182%nat,Decisions [none (Conditionally [(COr (HasDiscipline (Tracking)) (HasDiscipline (Hunting)) , Goto 332%nat); (Always true , Goto 58%nat)]); none (Goto 165%nat)]);
  (183%nat,none (Conditionally [(HasDiscipline (Camouflage) , Randomly [(Goto 198%nat , (Q2Qc (3 / 10)%Q)); (Goto 338%nat , (Q2Qc (7 / 10)%Q))]); (Always true , Randomly [(Goto 198%nat , (Q2Qc (7 / 10)%Q)); (Goto 338%nat , (Q2Qc (3 / 10)%Q))])]));
  (184%nat,Decisions [none (Goto 202%nat); none (Goto 342%nat)]);
  (185%nat,none (Simple [MustEat NoHunt] (Goto 40%nat)));
  (186%nat,evade_fight 0%nat 66%nat (Details ((18)%Z)%Z 25%nat []) (Goto 243%nat));
  (187%nat,none (Goto 164%nat));
  (188%nat,none (Simple [MustEat Hunt] (Goto 233%nat)));
  (189%nat,none (Randomly [(Goto 234%nat , (Q2Qc (1 / 2)%Q)); (Goto 47%nat , (Q2Qc (1 / 2)%Q))]));
  (190%nat,none (Goto 335%nat));
  (191%nat,Decisions [none (Goto 337%nat); none (Goto 297%nat)]);
  (192%nat,none (GameLost));
  (194%nat,none (Randomly [(Fight (Details ((16)%Z)%Z 37%nat [Timed 1%nat (ForceEMindblast)]) (Goto 32%nat) , (Q2Qc (1 / 10)%Q)); (Fight (Details ((16)%Z)%Z 37%nat [Timed 2%nat (ForceEMindblast)]) (Goto 32%nat) , (Q2Qc (1 / 10)%Q)); (Fight (Details ((16)%Z)%Z 37%nat [Timed 3%nat (ForceEMindblast)]) (Goto 32%nat) , (Q2Qc (1 / 10)%Q)); (Fight (Details ((16)%Z)%Z 37%nat [Timed 4%nat (ForceEMindblast)]) (Goto 32%nat) , (Q2Qc (1 / 10)%Q)); (Fight (Details ((16)%Z)%Z 37%nat [Timed 5%nat (ForceEMindblast)]) (Goto 32%nat) , (Q2Qc (1 / 10)%Q)); (Fight (Details ((16)%Z)%Z 37%nat [Timed 6%nat (ForceEMindblast)]) (Goto 32%nat) , (Q2Qc (1 / 10)%Q)); (Fight (Details ((16)%Z)%Z 37%nat [Timed 7%nat (ForceEMindblast)]) (Goto 32%nat) , (Q2Qc (1 / 10)%Q)); (Fight (Details ((16)%Z)%Z 37%nat [Timed 8%nat (ForceEMindblast)]) (Goto 32%nat) , (Q2Qc (1 / 10)%Q)); (Fight (Details ((16)%Z)%Z 37%nat [Timed 9%nat (ForceEMindblast)]) (Goto 32%nat) , (Q2Qc (1 / 10)%Q)); (Fight (Details ((16)%Z)%Z 37%nat [Timed 10%nat (ForceEMindblast)]) (Goto 32%nat) , (Q2Qc (1 / 10)%Q))]));
  (195%nat,Decisions [none (Goto 239%nat); none (Goto 266%nat); none (Goto 324%nat)]);
  (197%nat,Decisions [none (Goto 268%nat); none (Goto 76%nat); none (Goto 64%nat)]);
  (199%nat,Decisions [none (Goto 271%nat); none (Goto 56%nat)]);
  (200%nat,Decisions [conditional (COr (HasDiscipline (Hunting)) (HasFlag Special02)) (none (Goto 45%nat)); conditional (Not (COr (HasDiscipline (Hunting)) (HasFlag Special02))) (Decisions [none (Goto 133%nat); none (Goto 307%nat)])]);
  (201%nat,none (Goto 65%nat));
  (203%nat,Decisions [none (Goto 108%nat); none (Goto 271%nat)]);
  (204%nat,none (Simple [MustEat Hunt] (Goto 142%nat)));
  (205%nat,none (Goto 84%nat));
  (206%nat,Decisions [none (Goto 82%nat); none (Goto 226%nat)]);
  (207%nat,none (Conditionally [(COr (COr (COr (COr (COr (COr (COr (COr (COr (COr (HasDiscipline (WeaponSkill Dagger)) (HasDiscipline (WeaponSkill Spear))) (HasDiscipline (WeaponSkill Mace))) (HasDiscipline (WeaponSkill ShortSword))) (HasDiscipline (WeaponSkill Warhammer))) (HasDiscipline (WeaponSkill Sword))) (HasDiscipline (WeaponSkill Axe))) (HasDiscipline (WeaponSkill Quarterstaff))) (HasDiscipline (WeaponSkill BroadSword))) (HasDiscipline (WeaponSkill MagicSpear))) (HasDiscipline (WeaponSkill Sommerswerd)) , Randomly [(Goto 336%nat , (Q2Qc (3 / 10)%Q)); (Goto 218%nat , (Q2Qc (7 / 10)%Q))]); (Always true , Randomly [(Goto 336%nat , (Q2Qc (1 / 2)%Q)); (Goto 218%nat , (Q2Qc (1 / 2)%Q))])]));
  (209%nat,none (Conditionally [(HasLevel Aspirant , Goto 111%nat); (Always true , Goto 43%nat)]));
  (210%nat,Decisions [none (Goto 67%nat); none (Goto 132%nat); none (Goto 301%nat)]);
  (211%nat,none (Randomly [(Goto 51%nat , (Q2Qc (1 / 2)%Q)); (Goto 120%nat , (Q2Qc (1 / 2)%Q))]));
  (212%nat,Decisions [conditional (HasDiscipline (AnimalKinship)) (none (Goto 41%nat)); conditional (Not (HasDiscipline (AnimalKinship))) (Decisions [none (Goto 276%nat)])]);
  (213%nat,can_take (GenBackpack S2) 1%nat (can_take (GenBackpack S1) 1%nat (can_take (GenBackpack S3) 1%nat (can_take (GenBackpack S4) 1%nat (can_take (Weapon Axe) 1%nat (none (Goto 180%nat)))))));
  (214%nat,Decisions [none (Goto 46%nat); none (Goto 117%nat)]);
  (215%nat,Decisions [none (Goto 296%nat); none (Goto 119%nat)]);
  (216%nat,Decisions [none (Goto 304%nat); none (Goto 189%nat)]);
  (217%nat,none (Goto 345%nat));
  (218%nat,none (Goto 223%nat));
  (219%nat,Decisions [none (Goto 167%nat); none (Goto 185%nat)]);
  (220%nat,Decisions [none (Goto 90%nat); none (Goto 163%nat)]);
  (221%nat,Decisions [none (Goto 50%nat); none (Goto 228%nat); none (Goto 342%nat)]);
  (222%nat,can_take (Weapon Sword) 1%nat (none (Goto 165%nat)));
  (223%nat,Decisions [none (Goto 77%nat); none (Goto 128%nat)]);
  (224%nat,Decisions [conditional (COr (HasDiscipline (Tracking)) (HasDiscipline (SixthSense))) (none (Simple [LoseItem (GenBackpack S3) 1%nat; LoseItem (GenBackpack S4) 1%nat] (Goto 60%nat))); none (Simple [LoseItem (GenBackpack S3) 1%nat; LoseItem (GenBackpack S4) 1%nat] (Goto 199%nat)); none (Simple [LoseItem (GenBackpack S3) 1%nat; LoseItem (GenBackpack S4) 1%nat] (Goto 208%nat))]);
  (225%nat,none (Randomly [(Goto 20%nat , (Q2Qc (1 / 2)%Q)); (Goto 300%nat , (Q2Qc (2 / 5)%Q)); (Goto 181%nat , (Q2Qc (1 / 10)%Q))]));
  (226%nat,Decisions [none (Goto 21%nat); none (Goto 82%nat)]);
  (227%nat,Decisions [none (Goto 328%nat); none (Goto 120%nat)]);
  (228%nat,Decisions [none (Goto 23%nat); none (Goto 105%nat)]);
  (229%nat,none (Goto 235%nat));
  (230%nat,can_take Gold 9%nat (can_take Meal 2%nat (can_take (Weapon Sword) 1%nat (can_take (Weapon Dagger) 1%nat (none (Goto 224%nat))))));
  (231%nat,can_take Gold 3%nat (can_take Meal 1%nat (can_take (Weapon Sword) 1%nat (none (Goto 348%nat)))));
  (232%nat,Decisions [none (Goto 68%nat); none (Goto 130%nat)]);
  (234%nat,none (Goto 194%nat));
  (235%nat,Decisions [none (Goto 177%nat); none (Goto 100%nat)]);
  (236%nat,Decisions [none (Simple [DamagePlayer 4%nat] (Goto 123%nat)); none (Simple [DamagePlayer 4%nat] (Goto 169%nat))]);
  (237%nat,none (Goto 348%nat));
  (238%nat,none (Goto 223%nat));
  (239%nat,none (Goto 324%nat));
  (240%nat,none (Randomly [(Goto 94%nat , (Q2Qc (1 / 2)%Q)); (Goto 158%nat , (Q2Qc (1 / 2)%Q))]));
  (241%nat,Decisions [none (Goto 343%nat); none (Goto 115%nat)]);
  (242%nat,none (GameLost));
  (243%nat,none (Goto 124%nat));
  (244%nat,Decisions [conditional (COr (HasDiscipline (SixthSense)) (HasDiscipline (Tracking))) (none (Simple [LoseItem (GenBackpack S3) 1%nat; LoseItem (GenBackpack S4) 1%nat] (Goto 250%nat))); conditional (Not (COr (HasDiscipline (SixthSense)) (HasDiscipline (Tracking)))) (Decisions [none (Simple [LoseItem (GenBackpack S3) 1%nat; LoseItem (GenBackpack S4) 1%nat] (Goto 335%nat)); none (Simple [LoseItem (GenBackpack S3) 1%nat; LoseItem (GenBackpack S4) 1%nat] (Goto 11%nat))])]);
  (245%nat,Decisions [none (Goto 346%nat); none (Goto 83%nat)]);
  (246%nat,none (Simple [DamagePlayer 8%nat] (Conditionally [(HasItem (Weapon Sommerswerd) 1%nat , Goto 34%nat); (Always true , Goto 85%nat)])));
  (247%nat,none (Simple [MustEat Hunt] (Randomly [(Goto 171%nat , (Q2Qc (1 / 2)%Q)); (Goto 25%nat , (Q2Qc (1 / 2)%Q))])));
  (248%nat,none (Goto 254%nat));
  (249%nat,none (Conditionally [(COr (COr (COr (COr (COr (COr (COr (COr (COr (COr (HasDiscipline (WeaponSkill Dagger)) (HasDiscipline (WeaponSkill Spear))) (HasDiscipline (WeaponSkill Mace))) (HasDiscipline (WeaponSkill ShortSword))) (HasDiscipline (WeaponSkill Warhammer))) (HasDiscipline (WeaponSkill Sword))) (HasDiscipline (WeaponSkill Axe))) (HasDiscipline (WeaponSkill Quarterstaff))) (HasDiscipline (WeaponSkill BroadSword))) (HasDiscipline (WeaponSkill MagicSpear))) (HasDiscipline (WeaponSkill Sommerswerd)) , Randomly [(Goto 153%nat , (Q2Qc (1 / 5)%Q)); (Goto 323%nat , (Q2Qc (2 / 5)%Q)); (Goto 39%nat , (Q2Qc (2 / 5)%Q))]); (Always true , Randomly [(Goto 153%nat , (Q2Qc (2 / 5)%Q)); (Goto 323%nat , (Q2Qc (2 / 5)%Q)); (Goto 39%nat , (Q2Qc (1 / 5)%Q))])]));
  (250%nat,none (Goto 335%nat));
  (251%nat,Decisions [none (Goto 175%nat); none (Goto 38%nat); none (Goto 293%nat)]);
  (252%nat,Decisions [none (Goto 68%nat); none (Goto 130%nat)]);
  (253%nat,none (Conditionally [(HasLevel Warmarn , Goto 72%nat); (Always true , Goto 135%nat)]));
  (254%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 326%nat)); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Goto 156%nat); none (Goto 101%nat)])]);
  (255%nat,none (Goto 186%nat));
  (256%nat,none (Goto 309%nat));
  (257%nat,Decisions [none (Goto 302%nat); none (Goto 131%nat)]);
  (258%nat,Decisions [conditional (HasItem (GenSpecial S11) 1%nat) (none (Goto 305%nat)); conditional (Not (HasItem (GenSpecial S11) 1%nat)) (Decisions [conditional (CAnd (HasDiscipline (Camouflage)) (HasLevel Guardian)) (none (Goto 49%nat)); conditional (Not (HasDiscipline (Camouflage))) (Decisions [none (Goto 159%nat)])])]);
  (259%nat,none (Goto 141%nat));
  (261%nat,none (Goto 348%nat));
  (262%nat,none (GameLost));
  (263%nat,Decisions [none (Simple [DamagePlayer 4%nat] (Goto 123%nat)); none (Simple [DamagePlayer 4%nat] (Goto 169%nat))]);
  (264%nat,Decisions [none (Goto 134%nat); none (Goto 191%nat)]);
  (265%nat,none (Goto 307%nat));
  (266%nat,none (Goto 324%nat));
  (267%nat,none (GameLost));
  (268%nat,can_take Gold 4%nat (can_take Meal 2%nat (can_take (Weapon Spear) 1%nat (can_take (Weapon BroadSword) 1%nat (can_take (GenSpecial S0) 1%nat (can_take Laumspur 1%nat (Decisions [none (Goto 118%nat); none (Goto 170%nat); none (Goto 228%nat)])))))));
  (269%nat,none (Simple [MustEat NoHunt] (Goto 145%nat)));
  (270%nat,none (Conditionally [(CAnd (HasItem (GenBackpack S2) 1%nat) (HasItem (GenBackpack S1) 1%nat) , Goto 29%nat); (HasItem (GenSpecial S1) 1%nat , Goto 168%nat); (Always true , Goto 361%nat)]));
  (271%nat,none (Conditionally [(HasDiscipline (Hunting) , Randomly [(Goto 9%nat , (Q2Qc (1 / 2)%Q)); (Goto 104%nat , (Q2Qc (1 / 2)%Q))]); (Always true , Randomly [(Goto 9%nat , (Q2Qc (7 / 10)%Q)); (Goto 104%nat , (Q2Qc (3 / 10)%Q))])]));
  (272%nat,none (LoseItemFrom SWeapon 1%nat (Simple [DamagePlayer 5%nat] (Goto 79%nat))));
  (273%nat,Decisions [none (Goto 37%nat); none (Goto 126%nat)]);
  (274%nat,Decisions [conditional (HasItem (GenBackpack S0) 1%nat) (none (Goto 283%nat)); conditional (Not (HasItem (GenBackpack S0) 1%nat)) (Decisions [none (Goto 325%nat)])]);
  (275%nat,none (Simple [DamagePlayer 1%nat] (Goto 335%nat)));
  (276%nat,Decisions [none (Goto 88%nat); none (Goto 26%nat)]);
  (278%nat,Decisions [none (Goto 123%nat); none (Goto 169%nat)]);
  (279%nat,none (Conditionally [(CAnd (HasItem (Weapon Sword) 1%nat) (HasFlag Special01) , Goto 327%nat); (Always true , Goto 289%nat)]));
  (280%nat,none (Goto 231%nat));
  (281%nat,none (Goto 185%nat));
  (282%nat,none (Goto 257%nat));
  (283%nat,none (Simple [DamagePlayer 3%nat] (Goto 350%nat)));
  (284%nat,none (Simple [DamagePlayer 3%nat] (Goto 362%nat)));
  (286%nat,none (Goto 200%nat));
  (288%nat,Decisions [none (Goto 254%nat); none (Goto 187%nat)]);
  (289%nat,Decisions [conditional (HasLevel Warmarn) (none (Goto 255%nat)); conditional (Not (HasLevel Warmarn)) (none (Goto 5%nat)); conditional (Not (HasLevel Warmarn)) (none (Goto 86%nat))]);
  (290%nat,Decisions [none (Goto 44%nat); none (Goto 102%nat); none (Goto 78%nat)]);
  (291%nat,Decisions [conditional (HasDiscipline (Camouflage)) (none (Goto 172%nat)); conditional (Not (HasDiscipline (Camouflage))) (Decisions [none (Goto 93%nat); none (Goto 55%nat)])]);
  (292%nat,Decisions [none (Goto 123%nat); none (Goto 169%nat)]);
  (293%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 18%nat)); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Goto 150%nat)])]);
  (294%nat,none (Goto 200%nat));
  (295%nat,none (Goto 345%nat));
  (296%nat,Decisions [conditional (HasItem (Weapon Sommerswerd) 1%nat) (none (Goto 122%nat)); conditional (Not (HasItem (Weapon Sommerswerd) 1%nat)) (Decisions [none (Goto 274%nat)])]);
  (297%nat,Decisions [none (Goto 113%nat); none (Goto 252%nat)]);
  (298%nat,none (Goto 185%nat));
  (300%nat,none (Goto 341%nat));
  (301%nat,Decisions [conditional (HasDiscipline (AnimalKinship)) (none (Goto 106%nat)); conditional (Not (HasDiscipline (AnimalKinship))) (Decisions [none (Goto 236%nat)])]);
  (302%nat,can_take Laumspur 2%nat (can_take StrengthPotion 1%nat (can_take (GenBackpack S0) 1%nat (none (Goto 131%nat)))));
  (303%nat,none (Simple [DamagePlayer 2%nat] (Goto 348%nat)));
  (304%nat,none (Randomly [(Goto 47%nat , (Q2Qc (1 / 2)%Q)); (Goto 234%nat , (Q2Qc (1 / 2)%Q))]));
  (305%nat,none (Goto 204%nat));
  (306%nat,none (Goto 84%nat));
  (307%nat,Decisions [none (Goto 225%nat); none (Goto 36%nat)]);
  (309%nat,none (Conditionally [(HasDiscipline (Camouflage) , Randomly [(Goto 138%nat , (Q2Qc (2 / 5)%Q)); (Goto 244%nat , (Q2Qc (3 / 5)%Q))]); (Always true , Randomly [(Goto 138%nat , (Q2Qc (4 / 5)%Q)); (Goto 244%nat , (Q2Qc (1 / 5)%Q))])]));
  (311%nat,Decisions [none (Goto 90%nat); none (Goto 3%nat)]);
  (312%nat,none (Randomly [(Goto 120%nat , (Q2Qc (3 / 10)%Q)); (Goto 51%nat , (Q2Qc (7 / 10)%Q))]));
  (313%nat,none (Goto 96%nat));
  (314%nat,Decisions [none (Goto 53%nat); none (Goto 258%nat)]);
  (315%nat,Decisions [conditional (HasDiscipline (Tracking)) (none (Goto 48%nat)); conditional (Not (HasDiscipline (Tracking))) (Decisions [none (Goto 269%nat); none (Goto 145%nat)])]);
  (316%nat,evade_fight 0%nat 31%nat (Details ((16)%Z)%Z 26%nat []) (Goto 146%nat));
  (317%nat,none (Goto 348%nat));
  (318%nat,Decisions [conditional (HasItem (GenSpecial S2) 1%nat) (none (Goto 279%nat)); conditional (Not (HasItem (GenSpecial S2) 1%nat)) (Decisions [none (Goto 57%nat)])]);
  (319%nat,none (Randomly [(Goto 25%nat , (Q2Qc (1 / 2)%Q)); (Goto 171%nat , (Q2Qc (1 / 2)%Q))]));
  (320%nat,Decisions [none (Goto 268%nat); none (Goto 76%nat)]);
  (321%nat,none (Goto 309%nat));
  (322%nat,can_take (GenBackpack S3) 1%nat (can_take (GenBackpack S4) 1%nat (Decisions [none (Simple [HealPlayer 2%nat] (Goto 54%nat)); none (Simple [HealPlayer 2%nat] (Goto 129%nat))])));
  (323%nat,none (Goto 148%nat));
  (324%nat,Decisions [none (Simple [MustEat Hunt] (Goto 114%nat)); none (Simple [MustEat Hunt] (Goto 196%nat))]);
  (326%nat,none (Goto 101%nat));
  (327%nat,none (Simple [LoseItem (Weapon Sword) 1%nat; ClearFlag Special01] (Goto 289%nat)));
  (328%nat,none (Goto 120%nat));
  (329%nat,none (GameLost));
  (330%nat,Decisions [none (Goto 38%nat); none (Goto 175%nat); none (Goto 293%nat)]);
  (331%nat,Decisions [conditional (HasDiscipline (AnimalKinship)) (none (Goto 41%nat)); conditional (Not (HasDiscipline (AnimalKinship))) (Decisions [none (Goto 276%nat)])]);
  (332%nat,none (Goto 222%nat));
  (333%nat,none (OneRound (Details ((20)%Z)%Z 28%nat []) (Goto 209%nat) (Goto 344%nat) (Goto 220%nat)));
  (334%nat,none (GameLost));
  (335%nat,Decisions [conditional (HasDiscipline (Camouflage)) (none (Goto 35%nat)); conditional (Not (HasDiscipline (Camouflage))) (Decisions [conditional (HasDiscipline (MindOverMatter)) (none (Goto 317%nat)); conditional (Not (HasDiscipline (MindOverMatter))) (Decisions [none (Goto 147%nat)])])]);
  (336%nat,none (Goto 223%nat));
  (337%nat,none (Goto 297%nat));
  (338%nat,none (Goto 235%nat));
  (339%nat,none (Goto 233%nat));
  (340%nat,none (Simple [DamagePlayer 2%nat] (Goto 32%nat)));
  (341%nat,none (Simple [DamagePlayer 4%nat] (Goto 116%nat)));
  (342%nat,none (Simple [LoseItem (GenSpecial S0) 1%nat] (Simple [LoseItemKind [SBackpack]] (Goto 219%nat))));
  (343%nat,none (Conditionally [(HasEndurance 20%nat , Randomly [(Goto 194%nat , (Q2Qc (2 / 5)%Q)); (Goto 61%nat , (Q2Qc (3 / 5)%Q))]); (HasEndurance 12%nat , Randomly [(Goto 194%nat , (Q2Qc (7 / 10)%Q)); (Goto 61%nat , (Q2Qc (3 / 10)%Q))]); (Always true , Randomly [(Goto 194%nat , (Q2Qc (9 / 10)%Q)); (Goto 61%nat , (Q2Qc (1 / 10)%Q))])]));
  (344%nat,none (Conditionally [(HasLevel Aspirant , Goto 111%nat); (Always true , Goto 43%nat)]));
  (345%nat,none (Randomly [(Goto 51%nat , (Q2Qc (7 / 10)%Q)); (Goto 120%nat , (Q2Qc (3 / 10)%Q))]));
  (346%nat,none (Goto 335%nat));
  (347%nat,none (GameLost));
  (348%nat,none (Goto 185%nat));
  (349%nat,none (Goto 55%nat));
  (350%nat,none (GameWon));
  (360%nat,Decisions [none (Goto 87%nat); none (Fight (Details ((15)%Z)%Z 21%nat []) (Goto 230%nat))]);
  (361%nat,Decisions [none (Goto 246%nat); none (Goto 183%nat)]);
  (362%nat,evade_fight 0%nat 89%nat (Details ((16)%Z)%Z 25%nat []) (Goto 7%nat));
  (26%nat,none (Simple [SetFlag HadCombat] (Goto 363%nat)));
  (363%nat,none (Fight (Details ((15)%Z)%Z 38%nat [MindblastImmune]) (Goto 364%nat)));
  (364%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 321%nat))));
  (36%nat,none (Simple [SetFlag HadCombat] (Goto 365%nat)));
  (365%nat,none (Fight (Details ((17)%Z)%Z 25%nat [Timed 3%nat (OnNotYetWon 277%nat)]) (Goto 366%nat)));
  (366%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 155%nat))));
  (46%nat,none (Simple [SetFlag HadCombat] (Goto 367%nat)));
  (367%nat,none (Fight (Details ((20)%Z)%Z 10%nat []) (Goto 368%nat)));
  (368%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 281%nat))));
  (47%nat,none (Simple [SetFlag HadCombat] (Goto 369%nat)));
  (369%nat,none (Fight (Details ((16)%Z)%Z 37%nat [Timed 5%nat (OnNotYetWon 340%nat)]) (Goto 370%nat)));
  (370%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 32%nat))));
  (53%nat,none (Simple [SetFlag HadCombat] (Goto 371%nat)));
  (371%nat,none (Fight (Details ((13)%Z)%Z 16%nat []) (Goto 372%nat)));
  (372%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 109%nat))));
  (56%nat,none (Simple [SetFlag HadCombat] (Goto 373%nat)));
  (373%nat,none (Fight (Details ((12)%Z)%Z 18%nat [Timed 3%nat (OnNotYetWon 203%nat)]) (Goto 374%nat)));
  (374%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 69%nat))));
  (62%nat,none (Simple [SetFlag HadCombat] (Goto 375%nat)));
  (375%nat,none (Fight (Details ((17)%Z)%Z 24%nat [Timed 3%nat (CombatBonus (-2)%Z)]) (Goto 376%nat)));
  (376%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 148%nat))));
  (65%nat,none (Simple [SetFlag HadCombat] (Goto 377%nat)));
  (377%nat,none (Fight (Details ((20)%Z)%Z 10%nat []) (Goto 378%nat)));
  (378%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 298%nat))));
  (88%nat,none (Simple [SetFlag HadCombat] (Goto 379%nat)));
  (379%nat,none (Fight (Details ((15)%Z)%Z 38%nat [MindblastImmune]) (Goto 380%nat)));
  (380%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 321%nat))));
  (89%nat,none (Simple [SetFlag HadCombat] (Goto 381%nat)));
  (381%nat,none (Fight (Details ((17)%Z)%Z 26%nat []) (Goto 382%nat)));
  (382%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 7%nat))));
  (90%nat,none (Simple [SetFlag HadCombat] (Goto 383%nat)));
  (383%nat,none (Fight (Details ((17)%Z)%Z 24%nat []) (Goto 384%nat)));
  (384%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 249%nat))));
  (93%nat,none (Simple [SetFlag HadCombat] (Goto 385%nat)));
  (385%nat,none (Fight (Details ((15)%Z)%Z 26%nat []) (Goto 386%nat)));
  (386%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 2%nat))));
  (114%nat,none (Simple [SetFlag HadCombat] (Goto 387%nat)));
  (387%nat,none (Fight (Details ((16)%Z)%Z 25%nat []) (Goto 388%nat)));
  (388%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 295%nat))));
  (125%nat,none (Simple [SetFlag HadCombat] (Goto 389%nat)));
  (389%nat,none (Fight (Details ((20)%Z)%Z 30%nat [MultiFight]) (Goto 390%nat)));
  (390%nat,none (Fight (Details ((18)%Z)%Z 26%nat [MultiFight]) (Goto 391%nat)));
  (391%nat,none (Fight (Details ((16)%Z)%Z 24%nat []) (Goto 392%nat)));
  (392%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 261%nat))));
  (143%nat,none (Simple [SetFlag HadCombat] (Goto 393%nat)));
  (393%nat,none (Fight (Details ((16)%Z)%Z 22%nat []) (Goto 394%nat)));
  (394%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 360%nat))));
  (147%nat,none (Simple [SetFlag HadCombat] (Goto 395%nat)));
  (395%nat,none (Fight (Details ((14)%Z)%Z 23%nat [Timed 1%nat (PlayerInvulnerable)]) (Goto 396%nat)));
  (396%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 280%nat))));
  (153%nat,none (Simple [SetFlag HadCombat] (Goto 397%nat)));
  (397%nat,none (Fight (Details ((17)%Z)%Z 26%nat [Timed 2%nat (CombatBonus (-4)%Z)]) (Goto 398%nat)));
  (398%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 174%nat))));
  (169%nat,none (Simple [SetFlag HadCombat] (Goto 399%nat)));
  (399%nat,none (Fight (Details ((16)%Z)%Z 24%nat []) (Goto 400%nat)));
  (400%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 123%nat))));
  (193%nat,none (Simple [SetFlag HadCombat] (Goto 401%nat)));
  (401%nat,none (Fight (Details ((17)%Z)%Z 30%nat [Timed 2%nat (StopFight 311%nat)]) (Goto 402%nat)));
  (402%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 311%nat))));
  (196%nat,none (Simple [SetFlag HadCombat] (Goto 403%nat)));
  (403%nat,none (Fight (Details ((16)%Z)%Z 23%nat []) (Goto 404%nat)));
  (404%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 217%nat))));
  (198%nat,none (Simple [SetFlag HadCombat] (Goto 405%nat)));
  (405%nat,none (Fight (Details ((18)%Z)%Z 30%nat []) (Goto 406%nat)));
  (406%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 229%nat))));
  (202%nat,evade_fight 0%nat 342%nat (Details ((18)%Z)%Z 23%nat []) (Simple [SetFlag HadCombat] (Goto 407%nat)));
  (407%nat,none (Fight (Details ((15)%Z)%Z 24%nat [MultiFight]) (Goto 408%nat)));
  (408%nat,none (Fight (Details ((15)%Z)%Z 21%nat [MultiFight]) (Goto 409%nat)));
  (409%nat,none (Fight (Details ((16)%Z)%Z 25%nat [MultiFight]) (Goto 410%nat)));
  (410%nat,none (Fight (Details ((14)%Z)%Z 24%nat [MultiFight]) (Goto 411%nat)));
  (411%nat,none (Fight (Details ((14)%Z)%Z 22%nat []) (Goto 412%nat)));
  (412%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 237%nat))));
  (208%nat,none (Simple [SetFlag HadCombat] (Goto 413%nat)));
  (413%nat,none (Fight (Details ((15)%Z)%Z 25%nat [MultiFight]) (Goto 414%nat)));
  (414%nat,none (Fight (Details ((15)%Z)%Z 24%nat [MultiFight]) (Goto 415%nat)));
  (415%nat,none (Fight (Details ((14)%Z)%Z 22%nat []) (Goto 416%nat)));
  (416%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 199%nat))));
  (233%nat,none (Simple [SetFlag HadCombat] (Goto 417%nat)));
  (417%nat,none (Fight (Details ((17)%Z)%Z 26%nat []) (Goto 418%nat)));
  (418%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 312%nat))));
  (260%nat,none (Simple [SetFlag HadCombat] (Goto 419%nat)));
  (419%nat,none (Fight (Details ((18)%Z)%Z 30%nat []) (Goto 420%nat)));
  (420%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 311%nat))));
  (277%nat,none (Simple [SetFlag HadCombat] (Goto 421%nat)));
  (421%nat,none (Fight (Details ((22)%Z)%Z 35%nat []) (Goto 422%nat)));
  (422%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 155%nat))));
  (285%nat,none (Simple [SetFlag HadCombat] (Goto 423%nat)));
  (423%nat,none (Fight (Details ((16)%Z)%Z 28%nat []) (Goto 424%nat)));
  (424%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 71%nat))));
  (287%nat,none (Simple [SetFlag HadCombat] (Goto 425%nat)));
  (425%nat,none (Fight (Details ((17)%Z)%Z 27%nat []) (Goto 426%nat)));
  (426%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 75%nat))));
  (299%nat,none (Simple [SetFlag HadCombat] (Goto 427%nat)));
  (427%nat,none (Fight (Details ((19)%Z)%Z 29%nat []) (Goto 428%nat)));
  (428%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 121%nat))));
  (308%nat,none (Simple [LoseItem (GenSpecial S0) 1%nat] (Simple [SetFlag HadCombat] (Goto 429%nat))));
  (429%nat,none (Fight (Details ((17)%Z)%Z 30%nat []) (Goto 430%nat)));
  (430%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 127%nat))));
  (310%nat,none (Simple [SetFlag HadCombat] (Goto 431%nat)));
  (431%nat,none (Fight (Details ((18)%Z)%Z 25%nat []) (Goto 432%nat)));
  (432%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 24%nat))));
  (325%nat,none (Simple [SetFlag HadCombat] (Goto 433%nat)));
  (433%nat,none (Fight (Details ((25)%Z)%Z 29%nat [MindblastImmune]) (Goto 434%nat)));
  (434%nat,after_combat (none (Simple [SetFlag HadCombat] (Goto 350%nat))))].